### PR TITLE
[netfilter] Added error handling code to regex

### LINKED ISSUE #5125: Netfilter: "Error reading log line from pubsub" causing bans to clear several times a day
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [x] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Several times a day the netfilter container will log the following error: "Error reading log line from pubsub". Immediately after throwing this error, it will clear all bans from fail2ban. This is essentially making the netfilter container useless as within a few hours of an IP being banned, the container will almost certainly encounter this error and the IP will be unbanned anyway. Sometimes this happened every few hours, sometimes it can happen multiple times within a few minutes.
```

### Logs:

```plain text
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.798388367Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.810342474Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.810609023Z Unbanning 85.185.66.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.815155481Z Unbanning 111.70.18.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.816334090Z Unbanning 1.234.47.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.817276635Z Unbanning 124.195.191.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.818385944Z Unbanning 136.169.211.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.819767913Z Unbanning 80.227.147.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.821082646Z Unbanning 2.55.107.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.822321247Z Unbanning 190.33.254.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.823312043Z Unbanning 61.91.180.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.824332235Z Unbanning 205.210.31.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.825405545Z Unbanning 186.201.5.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.826443170Z Unbanning 46.48.133.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.827614995Z Unbanning 94.203.183.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.828635437Z Unbanning 186.239.155.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.829782687Z Unbanning 14.39.248.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.830870926Z Unbanning 218.151.8.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.832093286Z Unbanning 122.187.147.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.833296941Z Unbanning 125.19.244.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.834331599Z Unbanning 103.249.77.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.835489348Z Unbanning 98.178.152.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.836554986Z Unbanning 36.154.231.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.843702757Z Unbanning 66.96.201.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.843748984Z Unbanning 202.153.37.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.843753322Z Unbanning 37.192.126.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.843756709Z Unbanning 103.143.114.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.843759905Z Unbanning 41.79.189.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.843763040Z Unbanning 2.180.5.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.844970954Z Unbanning 125.138.98.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:51:59.846127009Z Unbanning 183.62.20.0/24
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:52:02.066509867Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:52:02.067484964Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:52:02.073110183Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:52:02.075387520Z Blacklist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:52:02.076728232Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T11:52:02.080216407Z Whitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:32.965515507Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:33.217734179Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:34.188649062Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:34.189606395Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:34.195447338Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:34.197463555Z Whitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:34.197487850Z Blacklist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:34.198345157Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:34.428244614Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:34.698344715Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:35.632112587Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:35.632918016Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:35.639979545Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:35.646108787Z Blacklist was changed, it has 1 entriesWhitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:35.646223622Z 
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:35.647433088Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:35.876112782Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:36.144984311Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:37.229706455Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:37.230524788Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:37.234616544Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:37.239947621Z Blacklist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:37.239998166Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:37.240875679Z Whitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:37.399085674Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:37.737504647Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:39.275869685Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:39.276718135Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:39.281058656Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:39.284258001Z Blacklist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:39.284495635Z Whitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:39.285470472Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:39.647309488Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:39.784816237Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:42.123707363Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:42.123752437Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:42.125247719Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:42.129159407Z Blacklist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:42.130737413Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:42.136390304Z Whitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:42.995738416Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:43.131009436Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:47.197640753Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:47.198487419Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:47.203061459Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:47.206069273Z Blacklist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:47.206098508Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:47.207908279Z Whitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:47.404854433Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:47.705467108Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:54.865213566Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:54.880631211Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:54.880677087Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:54.887981560Z Blacklist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:54.891846842Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:54.892838670Z Whitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:55.975538739Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:06:56.393944712Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:07:09.857014573Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:07:09.857402570Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:07:09.860573381Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:07:09.863910312Z Whitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:07:09.864507420Z Blacklist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T12:07:09.866648752Z Add host/network 46.148.40.0/24 to blacklist
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T13:13:10.046010401Z Error reading log line from pubsub
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T13:13:10.257566307Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T13:13:11.980763571Z Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T13:13:11.982030775Z Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T13:13:11.994016582Z Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T13:13:11.995039528Z Blacklist was changed, it has 1 entriesWhitelist was changed, it has 1 entries
mailcowdockerized-netfilter-mailcow-1  | 2023-03-14T13:13:11.995295367Z
```

### Steps to reproduce:

```plain text
Unsure how to reproduce, seems to happen fairly randomly.
```

### Which branch are you using?

master

### Operating System:

Debian GNU/Linux 11 (bullseye)

### Server/VM specifications:

8GB RAM, 4 CPU Cores

### Is Apparmor, SELinux or similar active?

apparmor_status shows module loaded

### Virtualization technology:

KVM

### Docker version:

23.0.1

### docker-compose version or docker compose version:

v2.16.0

### mailcow version:

2023-03

### Reverse proxy:

Traefik

### Logs of git diff:

```plain text
diff --git a/data/conf/nginx/templates/sites.template.sh b/data/conf/nginx/templates/sites.template.sh
index 782c8141..81b2688d 100644
--- a/data/conf/nginx/templates/sites.template.sh
+++ b/data/conf/nginx/templates/sites.template.sh
@@ -32,7 +32,7 @@ server {
   echo -n '
   server_name '${domains}';
 
-  include /etc/nginx/conf.d/includes/site-defaults.conf;
+  include /etc/nginx/conf.d/includes/auto.site-defaults.conf;
 }
 ';
 done
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index a445b60c..ed785454 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -198,3 +198,6 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks
 
 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
+
+myhostname = [REDACTED]
+
diff --git a/data/web/inc/vars.inc.php b/data/web/inc/vars.inc.php
index 5e6d72e7..200e769d 100644
--- a/data/web/inc/vars.inc.php
+++ b/data/web/inc/vars.inc.php
@@ -119,6 +119,10 @@ $SHOW_DKIM_PRIV_KEYS = false;
 $MAILCOW_APPS = array(
   array(
     'name' => 'Webmail',
+    'link' => '[REDACTED]',
+  ),
+  array(
+    'name' => 'Backup Webmail',
     'link' => '/SOGo/',
   )
 );
diff --git a/docker-compose.yml b/docker-compose.yml
index 40d22ce0..bcb072c5 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -377,9 +377,9 @@ services:
         - ./data/conf/nginx/:/etc/nginx/conf.d/:z
         - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro,z
         - sogo-web-vol-1:/usr/lib/GNUstep/SOGo/
-      ports:
-        - "${HTTPS_BIND:-}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
-        - "${HTTP_BIND:-}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
+#      ports:
+#        - "${HTTPS_BIND:-}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
+#        - "${HTTP_BIND:-}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
       restart: always
       networks:
         mailcow-network:
@@ -582,36 +582,6 @@ services:
           aliases:
             - ofelia
 
-    ipv6nat-mailcow:
-      depends_on:
-        - unbound-mailcow
-        - mysql-mailcow
-        - redis-mailcow
-        - clamd-mailcow
-        - rspamd-mailcow
-        - php-fpm-mailcow
-        - sogo-mailcow
-        - dovecot-mailcow
-        - postfix-mailcow
-        - memcached-mailcow
-        - nginx-mailcow
-        - acme-mailcow
-        - netfilter-mailcow
-        - watchdog-mailcow
-        - dockerapi-mailcow
-        - solr-mailcow
-      environment:
-        - TZ=${TZ}
-      image: robbertkl/ipv6nat
-      security_opt:
-        - label=disable
-      restart: always
-      privileged: true
-      network_mode: "host"
-      volumes:
-        - /var/run/docker.sock:/var/run/docker.sock:ro
-        - /lib/modules:/lib/modules:ro
-
 networks:
   mailcow-network:
     driver: bridge
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

### PR DESCRIPTION
**Pull request by th-joerger**
- do not refresh regex for each parsed line
- indicated maintenance steps to remedy regex error
- hint on ignored private IPs for proxy debug

Image can be tested with docker image thorjoerger/netfilter:152

This also closes #5125

### CODE REVIEW

**Comment by FreddleSpl0it** [comment]
Could you explain why you moved the refreshF2bregex call? 
This way, the function would only be called at the beginning of the while loop, and if pubsub.listen() raises an exception.
Or am i missing something?

**Comment by th-joerger** [comment]
I figured it made no sense to refresh the regex for each logline, but triggered by your request, I found what I believe to be the more fundamental problem with the program flow. As it is now, refresh regex is called only once, because `` for item in pubsub.listen():`` blocks indefinitely, so ``while not quit_now:`` is never checked again, right?

So I think, the watch thread should at least check ``quit_now`` once for each iteration of ``pubsub.listen()``. I can try to implement it this way if you concur.

Most likely related to [this issue](https://github.com/redis/redis-py/issues/386).

**Comment by FreddleSpl0it** [comment]
> So I think, the watch thread should at least check `quit_now` once for each iteration of `pubsub.listen()`. I can try to implement it this way if you concur.

yes, that sounds good. However, I have concerns about moving the refreshF2bregex call. Wouldn't it make sense to ensure that f2bregex is up-to-date before applying it?

**Comment by th-joerger** [comment]
Yes, I agree. It is not that costly of a function and in production it is only called every few seconds. I will make the change.

The API for ``pubsub.listen()`` does not support a timeout. I found a workaround which at least leaves the for loop after the last message has been parsed (and checks for ``quit_now``) but still not after a certain time, so the problem with the thread being stuck indefinitely still persists.

**Comment by FreddleSpl0it** [comment]
maybe we can call `pubsub.get_message()` in a while loop instead of `pubsub.listen()`
https://redis-py.readthedocs.io/en/stable/advanced_features.html#publish-subscribe

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
