### PR TITLE
backup_and_restore.sh: use pigz for faster compression

### PR DESCRIPTION
**Pull request by maltejk**
- use pigz for faster compression in backups, niced
- obviously need pigz. https://github.com/maltejk/buster-slim-pigz/

Can provide PR for data/Dockerfiles if this change would be considered

### CODE REVIEW

**Comment by xopez** [comment]
A compare would be nice.

**Comment by maltejk** [comment]
> On 16. Jul 2020, at 18:24, Sascha Moser <notifications@github.com> wrote:
> 
> A compare would be nice.

pigz runs four times faster here as I have four cpu cores.

**Comment by andryyy** [comment]
I appreciate this, but I don't think we should switch from the official packages for pigz. :/

**Comment by maltejk** [comment]
> On 19. Jul 2020, at 08:10, André Peters <notifications@github.com> wrote:
> 
> I appreciate this, but I don't think we should switch from the official packages for pigz. :/

Understood, thanks for the quick feedback. 

I can certainly build an image via compose if that's helpful. 

Another option certainly would be to stop compressing the mail folder tar archive, as it is compressed on a file base already I guess. 

Will open another PR then.

**Pull request closed without merging**
