### PR TITLE
Filter to limit ofelia scope

### PR DESCRIPTION
**Pull request by Kitof**
See https://github.com/mailcow/mailcow-dockerized/issues/5775

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by Kitof** [comment]
Is it possible to have a feedback on this ?

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by timwhite** [comment]
@milkmaker why close something that has been manually assigned to someone?

**Comment by DerLinkman** [comment]
Sorry @milkmaker is a bot account...

We'll take a look at this.

**Review by DerLinkman — APPROVED** [review]

**Pull request merged**
