### PR TITLE
Avoid exposing MySQL Root password through the cmdline during a backup

### PR DESCRIPTION
**Pull request by curdbecker**
The current version of the backup script accidentally exposes the MySQL Root password through the process cmdline during a backup. 

This is a potential security risk to the MySQL database, since the cmdline of a process can even be accessed by non-root users regardless of whether the process is in a docker container or not. For instance, a simple execution of a small shell snippet like `while true; do ps aux | grep -E [m]ysqldump; sleep 1; done` could (most likely) directly expose the root password during a backup. 

The fix deals with the two possible possibilities of exposure as follows:
- The password is directly supplied in the cmdline of the `docker run` command and then also in the cmdline of the `sh` process executed inside the container.
 -> This can be dealt with by exporting the `DBROOT` variable itself to the container. 
- The password is then supplied to `mysqldump` for performing the actual backup again using the cmdline.
->`mysqldump` supports the use of defaults files to set various environment options. Such a file containing the password can be created dynamically before executing `mysqldump` and can be used instead afterwards. The creation of the file using `echo` itself is uncritical, since echo is a shell builtin and therefore won't show up as an own process.

### CODE REVIEW

**Comment by andryyy** [comment]
Hm, it would still expose the password for a short time when it echos it to that file.

Oh, I am blind, you wrote:

    The creation of the file using echo itself is uncritical, since echo is a shell builtin and therefore won't show up as an own process.

Is this correct? Have never checked it. No way to still read it? It'd think it still shows as the commands parameter.

**Comment by curdbecker** [comment]
No, it doesn’t. echo is a builtin for bash, so it won’t be shown as an independant process if I am not mistaken :)

**Comment by andryyy** [comment]
It is shown as parameter, just checked it.

**Comment by curdbecker** [comment]
Where did you test it exactly? I can't reproduce it.  Does just the `echo` part of the command show up? Or what does show up at all?

I changed the patch now that it uses `bash` instead of `sh`, because I am using also `bash` in my patched version of the backup script (support for borgbackup). I figured that `sh` could be using `/bin/echo` instead of the shell builtin command, but that's also apparently not the case. Neither for `bash`. Just check the output below for reference.

```
# docker run --rm -it mariadb:10.2 /bin/sh -c "type echo"
echo is a shell builtin
```
```
# docker run --rm -it mariadb:10.2 /bin/bash -c "type echo"
echo is a shell builtin
```

**Comment by curdbecker** [comment]
Oh, and I just realised that I forgot the `-e` option for `echo` when switching the shell from `sh` to `bash`. I fixed it now. Sorry about that :)

**Pull request closed without merging**
