### PR TITLE
Pushover improvements

### PR DESCRIPTION
**Pull request by bluewalk**
Implementation of my suggested Pushover improvements, mentioned in #4862

This adds
* Two new variables SENDER_ADDRESS and SENDER_NAME
* The ability to choose the sound for the notification

### CODE REVIEW

**Comment by DerLinkman** [comment]
There we go :)

Sorry for messing with your branch. Now it only has your changes and not ours in it :)

**Review by DerLinkman — CHANGES_REQUESTED** [review]
In the init_db_inc.php file please increase the date at the beginning of the file as well. Otherwise no Database update is performed.

**Comment by bluewalk** [comment]
No worries, happy to know it’s getting merged so others can enjoy it 

> In the init_db_inc.php file please increase the date at the beginning of the file as well. Otherwise no Database update is performed.

Not sure if the database change is required, seems to be more like a migration step of existing data. If it’s required for a new attribute I will change it otherwise I will remove it.

**Comment by bluewalk** [comment]
Don't merge yet, found an issue in the parsing of the email address when it comes to subdomains. Will fix later today.

**Comment by bluewalk** [comment]
There we go, removed the regex which was not needed as we already have the senders address from the rspamd headers.

**Comment by bluewalk** [comment]
Just noticed the rspam from address sometimes differs from the actual address used in the header `Name <address>`. Eg Twitter has “notify@twitter.com” in its mail header while rspam comes back with something@bounce.twitter.com. Will do some improvements on that later 👍🏻

**Comment by FreddleSpl0it** [comment]
SENDER_ADDRESS might be a duplicate with the aleady existing SENDER variable or am i wrong?

**Comment by bluewalk** [comment]
> SENDER_ADDRESS might be a duplicate with the aleady existing SENDER variable or am i wrong?

Unfortunately not always the case. See earlier comment about Twitter. We can however remove the original SENDER as this could be a bounce email address. The from header of the email (part of the JSON body) is always correct and is what the email client shows.

**Comment by FreddleSpl0it** [comment]
Yes, i read your last comment not properly. I have tested your changes and everything works great :) thanks for your contribution.

**Review by FreddleSpl0it — APPROVED** [review]

**Pull request merged**
