### PR TITLE
[Web] Mailbox create/edit check if unlimited quota available

### PR DESCRIPTION
**Pull request by feldsam**
Signed-off-by: Kristian Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by andryyy** [comment]
Thank you

**Comment by andryyy** [comment]
The repository is not for untested changes, it happened before, so it is even more annoying. Thanks.

**Comment by feldsam** [comment]
Hello, sorry, what's wrong was with it? I tested it, but I not on the latest master revision.

**Comment by Hexaris** [comment]
this probably doesn't have to be there ...
`unlimited_quota'] != "1") > 0) ?`
last parenthesis

**Pull request merged**
