### PR TITLE
Use different exit code on updates check

### PR DESCRIPTION
**Pull request by max-baz**
Enables some scripting, e.g. putting this in a cron job:

    ./update.sh --check && <notify-me-about-available-updates>

By the way, what is the recommended way to follow updates? I'm preparing to switch from Mail-in-a-box, and there users receive an email when a new release is available. I found this `./update.sh --check` which with this PR merged will be able to help me follow updates, but is there maybe an alternative that everyone is currently using?

### CODE REVIEW

**Comment by mkuron** [comment]
You can subscribe to the RSS feed, https://github.com/mailcow/mailcow-dockerized/commits.atom . It's for the master branch, which contains the releases.

**Review by mkuron — APPROVED** [review]

**Comment by andryyy** [comment]
Can you change -1 to something from 3 to 255? 👍 I am not sure about which exit codes can/should be used right now. But I think we should avoid a negative int.

**Comment by max-baz** [comment]
Huh, a negative was not intended to be there, thanks for catching this! :)

I see all around that script `exit 1` is used, do you want me to use `exit 3` only in this particular case?

**Comment by andryyy** [comment]
Oh, okay. :) Hm, 3 would be good!

**Comment by max-baz** [comment]
Then 3 it is :+1:

**Pull request merged**
