### PR TITLE
Fix for git < 2.7

### PR DESCRIPTION
**Pull request by SecT0uch**
This change should be compatible with all git version. (get-url available from git 2.7)

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by DerLinkman** [comment]
Does it work on other systems which are not using an old Git Version?

This needs to be 100% bulletproof otherwise it won't merged!

**Comment by SecT0uch** [comment]
@DerLinkman yes it is:

```
$ git --version
git version 2.42.0
$ git config --get remote.origin.url
git@gitlab.com:fdroid/fdroidserver.git
$
```

**Comment by SecT0uch** [comment]
@DerLinkman Any chance we can get that merged ?

Centos 7 users are having issues when running the update script. 
The version I committed is way more bulletproof than `get-url` which has been added later on

**Comment by DerLinkman** [comment]
Ah yes. Sorry I missed the merge. Yes that works! Thanks

**Pull request merged**
