### PR TITLE
[Nginx] Reduce config duplication

### PR DESCRIPTION
**Pull request by klausenbusk**
It does not make sense having a seperate server block for both http
and https.
According to the nginx doc [1], using the same server block for both
should work.

[1] http://nginx.org/en/docs/http/configuring_https_servers.html#single_http_https_server

---

I'm using this configuration right now, and it seems to work fine.

### CODE REVIEW

**Comment by andryyy** [comment]
It makes sense and will break some setups without two server blocks, we tested this a while ago and run into some problems. Can't find the issue rn. I think it broke behind some reverse proxies?

**Comment by klausenbusk** [comment]
> we tested this a while ago and run into some problems. Can't find the issue rn. I think it broke behind some reverse proxies?

Interesting, I found the commit a3e966696f6bcc8b871a76ed7811cc465171627d, but as the commit message lacks the "why" that doesn't really help.

Looking through the commits, the commit messages could be improved. Feel free to read: https://chris.beams.io/posts/git-commit/

**Comment by klausenbusk** [comment]
> we tested this a while ago and run into some problems

I assume you are referring to this commit: c5054ae7eddec34ceb42863c2653504dd1ee6359, which was incorrectly implemented (you forgot to remove `ssl: on` and add `ssl` to https `listen`), so it effectively broke plain http.

**Comment by andryyy** [comment]
I tested it with a working config later... working as in "I removed the crap". It still had some downsides I don't want to dig out right now.....

Please read the open issues about how we plan to change git handling sometime soon....

**Comment by andryyy** [comment]
Hmm, let's give it a try.

**Pull request merged**
