### PR TITLE
Fix: Escape a `'` character in `update.sh`

### PR DESCRIPTION
**Pull request by h3ssan**
## Contribution Guidelines

* [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree them

## What does this PR include?

Fix for issue in https://github.com/mailcow/mailcow-dockerized/pull/6029

###  Affected Containers

None

### CODE REVIEW

**Comment by skyschub** [comment]
Why was this not released in a follow-up release?! The current stable release, `2024-08a`, is broken because of this, as the `update.sh` script has a syntax error and thus requires manual intervention...

**Comment by MAGICCC** [comment]
I guess the release was retagged, can you try a `git fetch && git checkout origin/master update.sh`?

**Comment by skyschub** [comment]
It wasn't. :( The `2024-08a` tag points to 439a936fd84aea6361c7611877f7dc920457adc5, and in that commit, the char is still unescaped:

https://github.com/mailcow/mailcow-dockerized/blob/439a936fd84aea6361c7611877f7dc920457adc5/update.sh#L407

**Comment by h3ssan** [comment]
Every one still facing this issue, please execute:
```bash
git fetch
git checkout origin/master
```

then run `./update.sh`

**Comment by DerLinkman** [comment]
I've retagged 2024-08a with the current master branch.

So it should be included within 2024-08a tag now

**Pull request merged**
