### PR TITLE
[Dovecot] Fix to allow the use of auth_default_realm without breaking…

### PR DESCRIPTION
**Pull request by sriccio**
… the master password used by imapsync and others

### CODE REVIEW

**Comment by sriccio** [comment]
Fix for https://github.com/mailcow/mailcow-dockerized/issues/1325

**Comment by andryyy** [comment]
Thanks. :-) Have you tested it with and without a default realm? Sync jobs, SOGo crons etc.?

**Comment by sriccio** [comment]
Hi @andryyy,

Yes I've tested sync jobs with and without default realm.

Also tested the sogo autoreply update cronjob with both setups successfully with:
`/usr/sbin/sogo-tool -v update-autoreply -p /etc/sogo/sieve.creds`

Cheers

**Comment by andryyy** [comment]
Nice, thanks for your work!

**Comment by sriccio** [comment]
thanks to you!

**Comment by sriccio** [comment]
Hi @andryyy,

This commit never made it to the master, is there something else I must do for it ?

I was asked to PR it to dev, but it never moved from there and dev branch seems way behind the master :)

Cheers,
Sébastien

**Pull request merged**
