### PR TITLE
Quarantine notifications - don't send if sender is blacklisted

### PR DESCRIPTION
**Pull request by feldsam**
Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by andryyy** [comment]
Hi,

Hm, how will that work with `*@bla.com` or `asd*@bla.com`?
How about a sender `bla@bla.com` while only `asdasd@bla.com` is blacklisted?

**Comment by feldsam** [comment]
Hi, thanks for pointing that. I fixed `*@domain.tld` senders, but `asd*@bla.com` is more complicated. In case of `asd*@bla.com` quarantine notification will be send.

**Comment by feldsam** [comment]
Ok, I replaced sender part by REGEX and looks like all cases are working

**Comment by andryyy** [comment]
Oh, cool. Let me check that tomorrow. :) Thanks!

**Comment by andryyy** [comment]
@mkuron What do you think?

**Comment by mkuron** [comment]
The query looks like it might work, but I'm not familiar with the quarantine mechanism as I don't use it.

**Pull request merged**
