### PR TITLE
Fix "The operation is insecure." when trying to register fido2 device.

### PR DESCRIPTION
**Pull request by El-Virus**
navigator.credentials.create(); Doesn't accept a port in the "id" parameter (generated by https://domain.tld:port/api/v1/get/fido2-registration/user). So, when trying to register a fido2 device via WebAuthn throws: "The operation is insecure." on firefox and "The relying party ID is not a registrable domain suffix of, nor equal to the current domain." on Chrome or Edge.
This commit replaces `$_SERVER['HTTP_HOST']` with `$_SERVER['SERVER_NAME']` when initializing `$WebAuthn` which excludes the port to formulate correct requests.
Now Mailcow allows the registration of fido2 devices when running in a non-standard port(eg. 443).

### CODE REVIEW

**Comment by DerLinkman** [comment]
Was not intentional (with the staging branch delete)

**Comment by DerLinkman** [comment]
@FreddleSpl0it opinion on that? Still needed after the WebAuthn Update?

**Comment by FreddleSpl0it** [comment]
Still needed.  $_SERVER['HTTP_HOST'] should be changed to $_SERVER['SERVER_NAME'] when initializing lbuchs\WebAuthn library

**Comment by El-Virus** [comment]
@DerLinkman, was it closed accidentally again?

**Comment by DerLinkman** [comment]
Yes... thanks to GitHub´s auto delete branch option. Deactivated it...

Sorry

**Pull request merged**
