### PR TITLE
Fix pip3 issue that broke netfilter Dockerfile build

### PR DESCRIPTION
**Pull request by ghost**
When building the netfilter docker image, using: docker:latest; running docker:dind service there is an error:
```
Attempting uninstall: packaging
    Found existing installation: packaging 20.9
ERROR: Cannot uninstall 'packaging'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
The command '/bin/sh -c apk add --virtual .build-deps   gcc   python3-dev   libffi-dev   openssl-dev && apk add -U python3   iptables   ip6tables   tzdata   py3-pip   musl-dev && pip3 install --upgrade pip   python-iptables   redis   ipaddress   dnspython && apk del .build-deps' returned a non-zero code: 1
```
Full logs:
```
$ docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
Step 1/8 : FROM alpine:3.14
3.14: Pulling from library/alpine
97518928ae5f: Pulling fs layer
97518928ae5f: Verifying Checksum
97518928ae5f: Download complete
97518928ae5f: Pull complete
Digest: sha256:635f0aa53d99017b38d1a0aa5b2082f7812b03e3cdb299103fe77b5c8a07f1d2
Status: Downloaded newer image for alpine:3.14
 ---> 0a97eee8041e
Step 2/8 : LABEL maintainer "Andre Peters <andre.peters@servercow.de>"
 ---> Running in a125a6232d4a
Removing intermediate container a125a6232d4a
 ---> f26caf93a018
Step 3/8 : ENV XTABLES_LIBDIR /usr/lib/xtables
 ---> Running in 248eac122cd3
Removing intermediate container 248eac122cd3
 ---> 2f90ff520447
Step 4/8 : ENV PYTHON_IPTABLES_XTABLES_VERSION 12
 ---> Running in 544c40fffd96
Removing intermediate container 544c40fffd96
 ---> b30765658632
Step 5/8 : ENV IPTABLES_LIBDIR /usr/lib
 ---> Running in b4771a0a6a95
Removing intermediate container b4771a0a6a95
 ---> d0df926f6678
Step 6/8 : RUN apk add --virtual .build-deps   gcc   python3-dev   libffi-dev   openssl-dev && apk add -U python3   iptables   ip6tables   tzdata   py3-pip   musl-dev && pip3 install --upgrade pip   python-iptables   redis   ipaddress   dnspython && apk del .build-deps
 ---> Running in 4468e23c3028
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/28) Installing libgcc (10.3.1_git20210424-r2)
(2/28) Installing libstdc++ (10.3.1_git20210424-r2)
(3/28) Installing binutils (2.35.2-r2)
(4/28) Installing libgomp (10.3.1_git20210424-r2)
(5/28) Installing libatomic (10.3.1_git20210424-r2)
(6/28) Installing libgphobos (10.3.1_git20210424-r2)
(7/28) Installing gmp (6.2.1-r0)
(8/28) Installing isl22 (0.22-r0)
(9/28) Installing mpfr4 (4.1.0-r0)
(10/28) Installing mpc1 (1.2.1-r0)
(11/28) Installing gcc (10.3.1_git20210424-r2)
(12/28) Installing pkgconf (1.7.4-r0)
(13/28) Installing libbz2 (1.0.8-r1)
(14/28) Installing expat (2.4.1-r0)
(15/28) Installing libffi (3.3-r2)
(16/28) Installing gdbm (1.19-r0)
(17/28) Installing xz-libs (5.2.5-r0)
(18/28) Installing mpdecimal (2.5.1-r1)
(19/28) Installing ncurses-terminfo-base (6.2_p20210612-r0)
(20/28) Installing ncurses-libs (6.2_p20210612-r0)
(21/28) Installing readline (8.1.0-r0)
(22/28) Installing sqlite-libs (3.35.5-r0)
(23/28) Installing python3 (3.9.5-r2)
(24/28) Installing python3-dev (3.9.5-r2)
(25/28) Installing linux-headers (5.10.41-r0)
(26/28) Installing libffi-dev (3.3-r2)
(27/28) Installing openssl-dev (1.1.1l-r0)
(28/28) Installing .build-deps (20220102.003225)
Executing busybox-1.33.1-r6.trigger
OK: 218 MiB in 42 packages
(1/31) Installing libmnl (1.0.4-r1)
(2/31) Installing libnftnl-libs (1.2.0-r0)
(3/31) Installing iptables (1.8.7-r1)
(4/31) Installing ip6tables (1.8.7-r1)
(5/31) Installing musl-dev (1.2.2-r3)
(6/31) Installing py3-appdirs (1.4.4-r2)
(7/31) Installing py3-chardet (4.0.0-r2)
(8/31) Installing py3-idna (3.2-r0)
(9/31) Installing py3-urllib3 (1.26.5-r0)
(10/31) Installing py3-certifi (2020.12.5-r1)
(11/31) Installing py3-requests (2.25.1-r4)
(12/31) Installing py3-msgpack (1.0.2-r1)
(13/31) Installing py3-lockfile (0.12.2-r4)
(14/31) Installing py3-cachecontrol (0.12.6-r1)
(15/31) Installing py3-colorama (0.4.4-r1)
(16/31) Installing py3-contextlib2 (0.6.0-r1)
(17/31) Installing py3-distlib (0.3.1-r3)
(18/31) Installing py3-distro (1.5.0-r3)
(19/31) Installing py3-six (1.15.0-r1)
(20/31) Installing py3-webencodings (0.5.1-r4)
(21/31) Installing py3-html5lib (1.1-r1)
(22/31) Installing py3-parsing (2.4.7-r2)
(23/31) Installing py3-packaging (20.9-r1)
(24/31) Installing py3-toml (0.10.2-r2)
(25/31) Installing py3-pep517 (0.10.0-r2)
(26/31) Installing py3-progress (1.5-r2)
(27/31) Installing py3-retrying (1.3.3-r1)
(28/31) Installing py3-ordered-set (4.0.2-r1)
(29/31) Installing py3-setuptools (52.0.0-r3)
(30/31) Installing py3-pip (20.3.4-r1)
(31/31) Installing tzdata (2021e-r0)
Executing busybox-1.33.1-r6.trigger
OK: 255 MiB in 73 packages
Requirement already satisfied: pip in /usr/lib/python3.9/site-packages (20.3.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Collecting python-iptables
  Downloading python-iptables-1.0.0.tar.gz (52 kB)
Collecting redis
  Downloading redis-4.1.0-py3-none-any.whl (171 kB)
Collecting ipaddress
  Downloading ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Collecting dnspython
  Downloading dnspython-2.1.0-py3-none-any.whl (241 kB)
Collecting deprecated>=1.2.3
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting packaging>=21.3
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.13.3.tar.gz (48 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.9/site-packages (from packaging>=21.3->redis) (2.4.7)
Using legacy 'setup.py install' for python-iptables, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Installing collected packages: wrapt, packaging, deprecated, redis, python-iptables, pip, ipaddress, dnspython
    Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
  Attempting uninstall: packaging
    Found existing installation: packaging 20.9
ERROR: Cannot uninstall 'packaging'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
The command '/bin/sh -c apk add --virtual .build-deps   gcc   python3-dev   libffi-dev   openssl-dev && apk add -U python3   iptables   ip6tables   tzdata   py3-pip   musl-dev && pip3 install --upgrade pip   python-iptables   redis   ipaddress   dnspython && apk del .build-deps' returned a non-zero code: 1
```
This error is likely due to pip3 not having correct metadata to the package that contains a list of files that belong to it.

The solution that I found was to ignore the installed packages.

The build log with the new Dockerfile (end):
```
tep 6/8 : RUN apk add --virtual .build-deps   gcc   python3-dev   libffi-dev   openssl-dev && apk add -U python3   iptables   ip6tables   tzdata   py3-pip   musl-dev && pip3 install --ignore-installed --upgrade pip   python-iptables   redis   ipaddress   dnspython && apk del .build-deps
 ---> Running in 42fa5a75509f
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/28) Installing libgcc (10.3.1_git20210424-r2)
(2/28) Installing libstdc++ (10.3.1_git20210424-r2)
(3/28) Installing binutils (2.35.2-r2)
(4/28) Installing libgomp (10.3.1_git20210424-r2)
(5/28) Installing libatomic (10.3.1_git20210424-r2)
(6/28) Installing libgphobos (10.3.1_git20210424-r2)
(7/28) Installing gmp (6.2.1-r0)
(8/28) Installing isl22 (0.22-r0)
(9/28) Installing mpfr4 (4.1.0-r0)
(10/28) Installing mpc1 (1.2.1-r0)
(11/28) Installing gcc (10.3.1_git20210424-r2)
(12/28) Installing pkgconf (1.7.4-r0)
(13/28) Installing libbz2 (1.0.8-r1)
(14/28) Installing expat (2.4.1-r0)
(15/28) Installing libffi (3.3-r2)
(16/28) Installing gdbm (1.19-r0)
(17/28) Installing xz-libs (5.2.5-r0)
(18/28) Installing mpdecimal (2.5.1-r1)
(19/28) Installing ncurses-terminfo-base (6.2_p20210612-r0)
(20/28) Installing ncurses-libs (6.2_p20210612-r0)
(21/28) Installing readline (8.1.0-r0)
(22/28) Installing sqlite-libs (3.35.5-r0)
(23/28) Installing python3 (3.9.5-r2)
(24/28) Installing python3-dev (3.9.5-r2)
(25/28) Installing linux-headers (5.10.41-r0)
(26/28) Installing libffi-dev (3.3-r2)
(27/28) Installing openssl-dev (1.1.1l-r0)
(28/28) Installing .build-deps (20220102.004614)
Executing busybox-1.33.1-r6.trigger
OK: 218 MiB in 42 packages
(1/31) Installing libmnl (1.0.4-r1)
(2/31) Installing libnftnl-libs (1.2.0-r0)
(3/31) Installing iptables (1.8.7-r1)
(4/31) Installing ip6tables (1.8.7-r1)
(5/31) Installing musl-dev (1.2.2-r3)
(6/31) Installing py3-appdirs (1.4.4-r2)
(7/31) Installing py3-chardet (4.0.0-r2)
(8/31) Installing py3-idna (3.2-r0)
(9/31) Installing py3-urllib3 (1.26.5-r0)
(10/31) Installing py3-certifi (2020.12.5-r1)
(11/31) Installing py3-requests (2.25.1-r4)
(12/31) Installing py3-msgpack (1.0.2-r1)
(13/31) Installing py3-lockfile (0.12.2-r4)
(14/31) Installing py3-cachecontrol (0.12.6-r1)
(15/31) Installing py3-colorama (0.4.4-r1)
(16/31) Installing py3-contextlib2 (0.6.0-r1)
(17/31) Installing py3-distlib (0.3.1-r3)
(18/31) Installing py3-distro (1.5.0-r3)
(19/31) Installing py3-six (1.15.0-r1)
(20/31) Installing py3-webencodings (0.5.1-r4)
(21/31) Installing py3-html5lib (1.1-r1)
(22/31) Installing py3-parsing (2.4.7-r2)
(23/31) Installing py3-packaging (20.9-r1)
(24/31) Installing py3-toml (0.10.2-r2)
(25/31) Installing py3-pep517 (0.10.0-r2)
(26/31) Installing py3-progress (1.5-r2)
(27/31) Installing py3-retrying (1.3.3-r1)
(28/31) Installing py3-ordered-set (4.0.2-r1)
(29/31) Installing py3-setuptools (52.0.0-r3)
(30/31) Installing py3-pip (20.3.4-r1)
(31/31) Installing tzdata (2021e-r0)
Executing busybox-1.33.1-r6.trigger
OK: 255 MiB in 73 packages
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Collecting python-iptables
  Downloading python-iptables-1.0.0.tar.gz (52 kB)
Collecting redis
  Downloading redis-4.1.0-py3-none-any.whl (171 kB)
Collecting ipaddress
  Downloading ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Collecting dnspython
  Downloading dnspython-2.1.0-py3-none-any.whl (241 kB)
Collecting deprecated>=1.2.3
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting packaging>=21.3
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.13.3.tar.gz (48 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)
Using legacy 'setup.py install' for python-iptables, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Installing collected packages: wrapt, pyparsing, packaging, deprecated, redis, python-iptables, pip, ipaddress, dnspython
    Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
    Running setup.py install for python-iptables: started
    Running setup.py install for python-iptables: finished with status 'done'
Successfully installed deprecated-1.2.13 dnspython-2.1.0 ipaddress-1.0.23 packaging-21.3 pip-21.3.1 pyparsing-3.0.6 python-iptables-1.0.0 redis-4.1.0 wrapt-1.13.3
(1/15) Purging .build-deps (20220102.004614)
(2/15) Purging gcc (10.3.1_git20210424-r2)
(3/15) Purging binutils (2.35.2-r2)
(4/15) Purging libatomic (10.3.1_git20210424-r2)
(5/15) Purging libgomp (10.3.1_git20210424-r2)
(6/15) Purging libgphobos (10.3.1_git20210424-r2)
(7/15) Purging python3-dev (3.9.5-r2)
(8/15) Purging libffi-dev (3.3-r2)
(9/15) Purging linux-headers (5.10.41-r0)
(10/15) Purging openssl-dev (1.1.1l-r0)
(11/15) Purging mpc1 (1.2.1-r0)
(12/15) Purging mpfr4 (4.1.0-r0)
(13/15) Purging isl22 (0.22-r0)
(14/15) Purging gmp (6.2.1-r0)
(15/15) Purging pkgconf (1.7.4-r0)
Executing busybox-1.33.1-r6.trigger
OK: 94 MiB in 58 packages
Removing intermediate container 42fa5a75509f
 ---> b2cf80f112b6
Step 7/8 : COPY server.py /
 ---> d484e099420b
Step 8/8 : CMD ["python3", "-u", "/server.py"]
 ---> Running in 0abe93dc640b
Removing intermediate container 0abe93dc640b
 ---> e0de6347c5ee
Successfully built e0de6347c5ee
```

### CODE REVIEW

**Comment by ghost** [comment]
If you use the --force-reinstall option instead, the build also fails.

**Comment by MAGICCC** [comment]
Hm strange why it fails now when you build the container..
Can you also change the base branch to staging and then you need to prob rebase

**Comment by andryyy** [comment]
It is fine for ne as long as we rebase on staging. :)

**Comment by andryyy** [comment]
I can hardly have a look at it right now as I'm still in hospital and will probably be for about a month. @mkuron can you help me out, please?

**Comment by mkuron** [comment]
Looks fine to me and makes the Dockerfile build correctly on my machine. I've switched the base branch to staging (which made an earlier bugfix show up in the diff that we merged to master instead of staging) and will merge in a minute.

The reason why this problem came up seems to be that _packaging_ was updated on pypi recently and the way Alpine installs it when _py3-pip_ is installed is incompatible with pip. I'm generally not a fan of mixing pip-installed and package manager-installed Python modules -- I usually only install modules via pip that are not available in the package manager to avoid issues precisely like this one...

**Review by mkuron — APPROVED** [review]

**Comment by andryyy** [comment]
Thank you!

**Comment by whalehub** [comment]
> I can hardly have a look at it right now as I'm still in hospital and will probably be for about a month.

Hope you get well soon! Wishing you all the best for your recovery.

**Comment by ghost** [comment]
> I can hardly have a look at it right now as I'm still in hospital and will probably be for about a month.

@andryyy Hope you get well soon! Wishing you all the best for your recovery.

**Comment by andryyy** [comment]
Merci! 🙂

**Pull request merged**
