### PR TITLE
[Update.sh] Added docker-compose Update prompt + Version check

### LINKED ISSUE #4648: The Compose file './docker-compose.yml' is invalid
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.nginx-mailcow.ports is invalid: Invalid port ":443:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx-mailcow.ports is invalid: Invalid port ":8080:8080", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

### Logs

```bash
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.nginx-mailcow.ports is invalid: Invalid port ":443:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx-mailcow.ports is invalid: Invalid port ":8080:8080", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

### Steps to reproduce

1. git pull
2../update.sh

### System information

| Question | Answer |
| --- | --- |
| My operating system | I_DO_REPLY_HERE |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker version (`docker version`) | I_DO_REPLY_HERE |
| docker-compose version (`docker-compose version`) | I_DO_REPLY_HERE |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
YOUR OUTPUT GOES HERE
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:

```
Chain INPUT (policy ACCEPT 35066 packets, 39M bytes)
 pkts bytes target     prot opt in     out     source               destination
  51M   59G MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0
   63  2545 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25
  51M 6015M ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:18388

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  79M   34G MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0
  79M   34G DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  79M   34G DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  36M 9857M ACCEPT     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
3614K  228M DOCKER     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0
2385K  362M ACCEPT     all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0
3552K  225M ACCEPT     all  --  br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0
  36M   33G ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
2894K  141M DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
  51M   35G ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    3   180 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      br-fa1cd97ce71b  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      br-fa1cd97ce71b  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  br-fa1cd97ce71b !br-fa1cd97ce71b  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  br-fa1cd97ce71b br-fa1cd97ce71b  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      br-98bf5e426461  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      br-98bf5e426461  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  br-98bf5e426461 !br-98bf5e426461  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  br-98bf5e426461 br-98bf5e426461  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 68466 packets, 70M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (4 references)
 pkts bytes target     prot opt in     out     source               destination
  476 27630 ACCEPT     udp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           udp dpt:1194
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.249         tcp dpt:6379
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.2           tcp dpt:8983
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.8           tcp dpt:3306
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:12345
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:4190
 8035  419K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:587
  902 51300 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:995
 1509 87148 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:465
  981 56028 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:993
34917 1782K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:25
  625 34636 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:143
 2440  143K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:110
 3223  166K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.10          tcp dpt:8080
 8720  484K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.10          tcp dpt:443
1857K   90M ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.4           tcp dpt:80

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
2397K  363M DOCKER-ISOLATION-STAGE-2  all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0
  51M   35G DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
 168M   84G RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0
11788  707K DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
  56M   35G RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
 203M  109G RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination
```

ip6tables -L -vn:
```
YOUR OUTPUT GOES HERE
```

iptables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
YOUR OUTPUT GOES HERE
```

### PR DESCRIPTION
**Pull request by DerLinkman**
This PR includes a update.sh Tweak which includes a Compose Update Prompt.

This is referencing: https://github.com/mailcow/mailcow-dockerized/issues/4648#issuecomment-1174702599

@andryyy i´ve moved the functions to the top since i would like to reuse one function in a early state of the script and don´t want to rewrite the same section of code again. Please let me know if you have a different approach of the function position or calling.

### CODE REVIEW

**Comment by ntimo** [comment]
I think we should we some way to configure all flags via env vars. Other wise it’s going to be hard to update mailcow using ansible or other automation toolings in the future :)

**Comment by DerLinkman** [comment]
> I think we should we some way to configure all flags via env vars. Other wise it’s going to be hard to update mailcow using ansible or other automation toolings in the future :)

It reacts to --no-update-compose and --force (the changes)

**Comment by DerLinkman** [comment]
@andryyy From my site it is ok. I´ve tested it on multiple maschines.

The --force option is respected and --no-update-compose will not ask for that prompt (still shows the diff between the installed and available version though).

**Comment by andryyy** [comment]
I'd prefer to test on machines with different OSes, pretend to have multiple docker compose installations with different versions and different networking. Or even both in different pathes etc. That's the way this should be tested in the future. That will help to not create a mess like it happened with the transition to v2.

As for the PR: looks good to me, but I have not tested it.

**Comment by DerLinkman** [comment]
Tested on multiple (all supported) OS (Centos, Ubuntu, Debian). Working!

**Pull request merged**
