### PR TITLE
Improve send-as behaviour

### PR DESCRIPTION
**Pull request by macwinnie**
Receiving mails for wildcard alias addresses is really easy – but sending mails from those any-aliases was not possible at all unless every sender address was added as an explicit alias to the database.

By this change in the database query for allowed sender addresses, the first finding `not NULL` (see [`SELECT COALESCE`](https://www.w3schools.com/sql/func_sqlserver_coalesce.asp) for how it works) – either an exact alias `mailbox@domain.tld` or the wildcard alias `@domain.tld` will be allowed to send mails as the given address ... without the need of explicit definition within the database.

I hope, you find this change useful and consider adding this feature to the official project =)

### CODE REVIEW

**Review by andryyy — COMMENTED** [review]
Looks good. :)

**Review by andryyy — APPROVED** [review]
Looks good!

**Comment by andryyy** [comment]
Forgot to approve. 

@DerLinkman We should not forget to increase the image version.

**Comment by DerLinkman** [comment]
@macwinnie can you increase the Image Tag inside of the docker-compose.yml for Postfix +1?

**Comment by macwinnie** [comment]
@DerLinkman done the `docker-compose.yml` update.

**Review by DerLinkman — APPROVED** [review]

**Pull request merged**
