### PR TITLE
remove version from docker-compose.yml

### PR DESCRIPTION
**Pull request by iamspido**
With docker version 25.05 the version 2.1 in docker-compose.yml will be obsolete.
docker-compose.yml: `version` is obsolete

Fix for https://github.com/mailcow/mailcow-dockerized/issues/5797

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by JiiPee74** [comment]
This is only warning and removing it from config file may break older docker installations, so I would leave it for now.

**Comment by tomudding** [comment]
> This is only warning and removing it from config file may break older docker installations, so I would leave it for now.

The `version` attribute has been optional since the new Compose specs released at the end of 2020, see https://github.com/docker/compose/releases/tag/1.27.0-rc1 and https://github.com/compose-spec/compose-spec/commit/649d3b0d8627a50f81e268678dca93811c3934b6.

Any recent version of Mailcow requires Compose v2 to be able to work, which has the above change since its inception. So if someone is still using a version of Compose that uses/only supports the v1 spec there are likely more serious issues with that system that require attention.

**Comment by DerLinkman** [comment]
I'll check what @tomudding said today. And if so (what i think because i trust him :D) it will be merged. But yeah if this is optional since Compose v2 we can safely merge this as you need compose v2 anyways to run mailcow nowadays...

**Comment by DerLinkman** [comment]
Jup works without version: even in the first 2.0.0 version of compose. Alright, then it will be merged :)

**Review by DerLinkman — APPROVED** [review]

**Pull request merged**
