### PR TITLE
Re-add default value for LOG_LINES

### PR DESCRIPTION
**Pull request by mkuron**
These were already added in #966, but seem to have gotten lost in the latest merge (b175125d024dc4b88fef98def9b65fabd7727af8).

### CODE REVIEW

**Comment by andryyy** [comment]
Thanks!

Let's change the update process. I trust your decision, any idea is welcome.

**Comment by mkuron** [comment]
I still think developing new features on dev and fixing bugs on master is fine. The problem only comes up when the same bugfix is re-implemented on dev before master is merged into dev. We just need to merge master into dev more often (ideally, every time master is changed).

**Comment by extremeshok** [comment]
+1

**Comment by MAGICCC** [comment]
Normally you do something like this:
- Every commit goes into dev, even PRs (change destination branch to dev if neccessary)
- New features, e.g. Nextcloud goes into a new branch (feature/xyz)
- If you commit, use good commit messages to build a [changelog](http://keepachangelog.com/en/1.0.0)  later
- If you think dev is stable, get persons to test simple things - we have IRC for this. Wait 1-2 days before everyone says it's fine
- Tag the latest commit with e.g. 0.x - use [semantic versioning](https://semver.org/)
- Merge dev into master
- Have fun with a stable project

Notes:
master branch shouldnt be touched unless you merge into it - protect it in the settings!

**Comment by mkuron** [comment]
@magiccc, that‘s of course the ideal case. We have discussed this multiple times before and found it too complex for a small project like Mailcow. It doesn‘t solve the problem of bugfixes though that need to go to master quickly. And sometimes there are multiple features in development that can’t easily be separated, so we don’t usually use feature branches. Nobody except @andryyy really runs the dev branch, so we simply can‘t get much testing on it before merging to master.

**Comment by MAGICCC** [comment]
@mkuron No project is too small! And if we find big bugs - like yesterday again - we find them on dev while testing and not when it got merged into master already. Then you have the problems, when users are updating and breaking their system with faulty things.
Nobody is perfect and I doubt we can find all mistakes, but I am sure we may find big mistakes and then we can fix them before merging.
Just count the issues after merging to master - there are a lot in the last weeks

**Comment by andryyy** [comment]
I will stop accepting PRs for the next days or weeks.

@mkuron Feel free to push and merge anyway.

**Comment by mritzmann** [comment]
Or you can accept only PRs with some amount of reviews. https://help.github.com/articles/about-pull-request-reviews/

**Pull request merged**
