### PR TITLE
✏️ Fixed invalid regexs for banning.

### PR DESCRIPTION
**Pull request by vermium**

### CODE REVIEW

**Comment by DerLinkman** [comment]
Test for PR action

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by vermium** [comment]
Anything I need to do? Since @DerLinkman changed it :)

**Comment by DerLinkman** [comment]
No 😀 it was just a test.

**Comment by vermium** [comment]
Oh cool!

**Comment by vermium** [comment]
Could you maybe review this?

**Review by DerLinkman — APPROVED** [review]
Looks good to me

**Comment by dragoangel** [comment]
I think PR itself okay, but I'm curious what was wrong? Regex not capture some cases?  Can PR have at least some short description which will describe samples of logs that wasn't covered by previous regex to validate.

**Comment by dragoangel** [comment]
@DerLinkman also you know that changes here will be only applied to new setups and to people who will go to fail2ban settings, and will reset rules to default? Need write about it in changelog as recommend action.

**Comment by DerLinkman** [comment]
> @DerLinkman also you know that changes here will be only applied to new setups and to people who will go to fail2ban settings, and will reset rules to default? Need write about it in changelog as recommend action.

Yeah I remembered that. Will do that. @VermiumSifell can you write  a quick before and after for this pr? As @dragoangel said?

**Comment by vermium** [comment]
Well I dont really know, it did just mot capture something so I put .+ To wildcard that part

**Comment by dragoangel** [comment]
> Well I dont really know, it did just mot capture something so I put .+ To wildcard that part

Can you share logs samples that wasn't been captured please?

**Comment by vermium** [comment]
> 

I currently don't have a mailcow setuped, but basicly when someone used failed password on smtp or pop3 login from thunderbird for example.

**Comment by dragoangel** [comment]
@DerLinkman can you check this regex, please? As I now do not have access to a running system for test.

**Comment by vermium** [comment]
Well as a proof, but from another logging message (JUST A RANDOM EXAMPLE INCLUDING Disconnected: AND NOT THE ACTUAL AUTH FAILED MESSAGE)
```
mailcowdockerized-dovecot-mailcow-1    | Nov  2 21:48:22 840ec6ccd2a5 dovecot: imap-login: Disconnected: Aborted login by logging out (no auth attempts in 0 secs): user=<>, rip=172.22.1.3, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
```

as you can see, it says `Disconnected:` and not `Disconnect` the old regex wasnt working due to the : another solution to this problem I think was to-do `Disconnect:` instead of `Disconnect.+` but I wanted to be sure that this will work with other logs too, not 100% sure if `Disconnect:` was working but something like that worked.

**Comment by FreddleSpl0it** [comment]
I can definitely say, that the current regex is not working for me

When i try to imap login with false credentials i get:
`imap-login: Disconnected: Connection closed (auth failed, 3 attempts in 14 secs): user=<test@domain.org>, method=PLAIN, rip=RIP, lip=LIP, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)`
in this scenario the suggested RegEx works fine
`-login: Disconnected.+ \(auth failed, .+\): user=.*, method=.+, rip=([0-9a-f\.:]+),`

this regex will also catch a failed pop3 login:
`pop3-login: Disconnected: Aborted login by logging out (auth failed, 3 attempts in 14 secs): user=<test@domain.org>, method=LOGIN, rip=RIP, lip=LIP, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)>`

i cannot reproduce and confirm the following:
```
 '-login: Aborted login.+ \(auth failed .+\): user=.+, rip=([0-9a-f\.:]+), lip.+'
 '-login: Aborted login.+ \(tried to use disallowed .+\): user=.+, rip=([0-9a-f\.:]+), lip.+'
```

**Review by mkuron — APPROVED** [review]

**Comment by vermium** [comment]
What's happening? Should this be merged or not?

**Comment by omexlu** [comment]
A RESET OF NETFILTER ENTRIES IN THE UI IS NEEDED TO APPLY THIS

Where and how to do that?

**Comment by skyschub** [comment]
System > Configuration > Options > Fail2ban parameters > expand the "Regex filters" section > Reset to default

**Pull request merged**
