### PR TITLE
Removing unused UCEPROTECT symbols from rspamd configs

### PR DESCRIPTION
**Pull request by Koopzington**
The symbols were no longer used since https://github.com/mailcow/mailcow-dockerized/commit/38e5dc37d2a3b56b5bb2cdd246442cbe2bbe24f7#diff-2ddcc31f5c527a3fcadb72a6d446d28c6f7cfc5362a6c38c6229c7cd07c40f3d

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Review by dragoangel — APPROVED** [review]
LGTM

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by Koopzington** [comment]
🤷

**Pull request closed without merging**
