### PR TITLE
php-fpm dockerfile simplification

### PR DESCRIPTION
**Pull request by TBK**
Locked to specific Alpine release.
Fewer layers.
Size reduction of 403.3 MB.
image

I also checked the docker-entrypoint.sh script againtst http://www.shellcheck.net/ and corected most of the warnings. There are still a few left.

The last part of the dockerfile, from "# Configuring php-fpm" and below is a modified version of the last section of the official php image dockerfile - https://github.com/docker-library/php/blob/76a1c5ca161f1ed6aafb2c2d26f83ec17360bc68/7.1/fpm/alpine/Dockerfile

### CODE REVIEW

**Comment by andryyy** [comment]
Thanks, but you shouldn't change the script based on a web check. Things like `rm /data/dkim/{keys,txt}/"${file}"` happen then. I agree that using quotation marks is mostly a good idea, but not always necessary. Just like `-r` for read when we read domain names.
Sometimes you lose functionality of a script with these slight changes. :)

I should nevertheless start using more quotation marks...

It's a very nice approach to save a lot of disk space, thanks!

**Comment by andryyy** [comment]
And a +1 for  `Time to milk the cows`. 🐄

**Comment by andryyy** [comment]
I see this is missing mysqladmin and redis-cli. I assume you just don't use the migration script. But then don't push untested, please.

Edit: It is also missing the PEAR path in include_path, ctype_alnum is not defined etc.
Sorry, this cannot be tested...

**Comment by TBK** [comment]
I am sorry. Apprently I was too tired when doing tesing and tested against the old Dockerfile..... fail :(

I will create a new PR without the changed to the bash script and with all of the dependencies.

**Pull request merged**
