### PR TITLE
[web] Responsive Design

### PR DESCRIPTION
**Pull request by feldsam**
Complete styling for mobile devices. Tested on iPhone 11

Signed-off-by: Kristian Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by feldsam** [comment]
maildev feldhost cz_mailbox_lang=en

**Review by ghost — APPROVED** [review]
🎉

**Comment by andryyy** [comment]
bootstrap-tabcollapse was last updated 6 years ago. My plan is to migrate to BS5.

**Comment by feldsam** [comment]
Hi, but it is working good. When you update to BS5, then we can replace it with something new.

**Comment by feldsam** [comment]
@andryyy what about this? update to BS5 is a big step and takes time. There are many changes and new functions, like flex grid. I think we should implement a templating system like Twig during the update to BS5. I am ready to help, but in meantime, we can have at least this responsive design on old code.

btw, I added two more lines to `tabcollapse` script to make it work better with Mailcow, it is a simple script, which I can maintain.

**Pull request merged**
