### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by flobeier**
Duplicate entries removed and remaining sorted alphabetically, indentation through tabs changed to spaces. Duplicate of #1294 which was accidently closed by me while trying to fix it.

### CODE REVIEW

**Comment by andryyy** [comment]
But this still has duplicates and is not sorted. 😱 :-)

**Comment by andryyy** [comment]
Some pecl extensions should also be installed in a given order. I remember having trouble with this - not in mailcow though.

Still, it has duplicates and is not really sorted. 🤷‍♂️ 

Give me a few minutes to pipe it through sort and uniq.

**Comment by flobeier** [comment]
@andryyy okay, I didn't know that there could be trouble with the pecl extensions if you change the order.

I'm sorry that you had to go through the file and fix it, which was my original intention to do. On top of being relatively inexperienced with git I was a little tired last night and must have commited the wrong file. One duplicate still slipped through (`libjpeg-turbo-dev`).
Thanks for the learning opportunity.

**Comment by andryyy** [comment]
The image doesn't even build like this. Please never, ever push to this repository when you didn't test exactly what you push.

**Comment by flobeier** [comment]
@andryyy yes, again, I'm sorry. I honestly don't know why I pushed the wrong content. I shouldn't have tried to quickly fix my earlier mistake before going to bed.

**Pull request merged**
