### PR TITLE
support pre-hashed passwords

### PR DESCRIPTION
**Pull request by drpuur**
PR was closed instead of merged. See https://github.com/mailcow/mailcow-dockerized/pull/3283

### CODE REVIEW

**Comment by andryyy** [comment]
Merci. Perhaps we should add this here: https://mailcow.github.io/mailcow-dockerized-docs/model-passwd/ - can you do that, too? :)

**Comment by drpuur** [comment]
> Merci. Perhaps we should add this here: https://mailcow.github.io/mailcow-dockerized-docs/model-passwd/ - can you do that, too? :)

I am a new user and missed the possibility to import mailbox-passwords from my current setup. I only have them in hashed form, of course. So I'd rather put a note in the API doc.

**Comment by andryyy** [comment]
That's fine.

**Comment by andryyy** [comment]
@ntimo Do you think you can add that hint there? :)

**Pull request merged**
