### PR TITLE
Add switch to skip fetching certificates auto{config,discover} subdomains

### PR DESCRIPTION
**Pull request by schichtnudelauflauf**
Add switch to skip fetching certs for auto{config,discover} subdomains.

Might be useful in certain reverse proxy situations.

This is a cleaned up version of https://github.com/mailcow/mailcow-dockerized/pull/5474

The things discussed there are changed and I made a better name.
I had to open a new PR due to Github Web UI limitations.

The old PR that is linked can bre closed.

@jennypaxian, pinging you too because you'll not be auto notified.

### CODE REVIEW

**Comment by schichtnudelauflauf** [comment]
(Offtopic: How much I hate that the webinterface does sign my commits with a key I don't control. I'd rather they were unsigned. Sheesh.)

**Comment by dragoangel** [comment]
You feel that variable definitely is too long?

`AUTODISCOVER_SAN=y/n` and should be `y` by default in compose when unset. Don't want autodiscover, put it to `n`

**Comment by schichtnudelauflauf** [comment]
that sounds kinda ambiguous but I'll put it if it gets it merged 😁

**Comment by jennypaxian** [comment]
> You feel that variable definitely is too long?
> 
> `AUTODISCOVER_SAN=y/n` and should be `y` by default in compose when unset. Don't want autodiscover, put it to `n`

Sounds good to me, also thanks y'all for following up on it.

**Comment by schichtnudelauflauf** [comment]
Ok now after snail fast editing of things on my phone the name is changed, default flipped.

**Comment by dragoangel** [comment]
Well now it looks cleaner for me, thanks.

**Comment by schichtnudelauflauf** [comment]
Just in case, I couldn't squash the commits together with the webinterface from the phone. I have no laptop nearby. But you'll merge squashed anyways ig?

**Comment by schichtnudelauflauf** [comment]
Can I get a yes or no here?

**Review by DerLinkman — APPROVED** [review]
Now it looks good! Thank you very much <3

**Pull request merged**
