### PR TITLE
Update quarantine.js

### PR DESCRIPTION
**Pull request by prey87**
changed created formatter like in site/user.js, site/mailbox.js & site/admin.js to get month and day in 2-ditgit format

### CODE REVIEW

**Comment by andryyy** [comment]
I think the seconds are fine in this overview. :/

**Comment by prey87** [comment]
The time format don't change.
before:
2.6.2020, 19:41:52
after:
02.06.2020, 19:41:52

**Comment by andryyy** [comment]
Ah, sorry. Got it wrong. Yes, that's fine. But there are other places, too. We should change all of them.

**Comment by prey87** [comment]
found some more in the debug.js and changed them too

**Comment by andryyy** [comment]
Thank you very much!!

**Pull request merged**
