### PR TITLE
Adds only existing domains in table to the filter and removes additional ajax request.

### LINKED ISSUE #2601: Alias domain filtering
The "All domains" Dropdown is not working in "Mail Setup"

### PR DESCRIPTION
**Pull request by Kraeutergarten**
This fixes #2601

### CODE REVIEW

**Comment by evilstiefel** [comment]
LGTM, the only issue I guess is that it will fail "ungracefully" if anybody ever decides to rename the row for domains in the table, but that's hardly limited to this PR.

Thanks!

**Comment by Kraeutergarten** [comment]
@evilstiefel 
New commit should fix your concern.

**Comment by andryyy** [comment]
image

I have three domains, no mailboxes. In the mailbox table it returns one domain.

**Comment by andryyy** [comment]
Nah, something else is broken now. I will check it. :) Probably not related.
Edit: Yes, it was indeed not related. :)

**Comment by evilstiefel** [comment]
Well, technically it now uses the data that populates the rows of the table. That means if there are no entries, there should be no options for the filter.

**Pull request merged**
