### PR TITLE
Added org labels to docker compose

### PR DESCRIPTION
**Pull request by ntimo**
The org labels can be used in combination with node exporter and Grafana to visualise the performance of the Mailcow Stack.

### CODE REVIEW

**Comment by andryyy** [comment]
That’s not useful for everyone. 

Please add it to the docs to be used in a docker-compose. override.yml.

**Comment by ntimo** [comment]
Sure but it also won't hurt to have to label added to the containers :)

**Comment by ntimo** [comment]
Hier mal ein Beispiel Grafana board:
Screenshot 2019-04-07 at 13 28 24

**Comment by andryyy** [comment]
But you don’t want to set fixed labels for everyone for something individual

**Pull request closed without merging**
