### PR TITLE
Respect COMPOSE_PROJECT_NAME when querying for container name

### PR DESCRIPTION
**Pull request by max-baz**
I noticed this when experimenting with mailcow by running a second instance of it on a single server, these scripts do not respect COMPOSE_PROJECT_NAME and therefore collide with already existing containers.

### CODE REVIEW

**Comment by mkuron** [comment]
Partial duplicate of #2796.

**Comment by max-baz** [comment]
Oh I didn't see that one! It seems my PR has a few extra bits that are missing in #2796, but I'm totally okay for this PR to be closed if the work is continued there.

**Comment by andryyy** [comment]
This didn't work the last time we merged something similar.

Also not sure if all docker-compose versions use the same json key. Do they?

I'd be fine merging, if we are sure this is tested. :)

**Comment by max-baz** [comment]
I don't know for sure, but some of the code in `master` already uses this exact logic 😉 

https://github.com/mailcow/mailcow-dockerized/blob/a908b2da6e9a6da98b1d0271dca725e8012b62fd/data/web/inc/functions.docker.inc.php#L28

**Comment by andryyy** [comment]
:) Should be fine then or at least break everywhere evenly. 😄 

I will build it and test.

**Comment by andryyy** [comment]
jq -rc 'select(.project == "${COMPOSE_PROJECT_NAME}")'

This would not work for example. 

I will consider a rework.

**Pull request closed without merging**
