### PR TITLE
Make is_valid_domain_name more strict

### LINKED ISSUE #1118: Admin-Interface allows creation of "invalid" domains
Currently, you can create a domain like "mynamespace" without a TLD like .com, .de etc. This is fine, but then you cannot create any mailboxes for those domains (in the creation dialog, you will receive an error: "Mailbox name is invalid").

I believe you should either:

- not be able to create these domains in the interface
- or be able to add a mailbox to them

### PR DESCRIPTION
**Pull request by patschi**
Fixes #1118

### CODE REVIEW

**Comment by andryyy** [comment]
What was not covered by the previous check? Do you have examples?

**Comment by patschi** [comment]
See issue #1118. Using `asd` was a valid domain, but what in reality isn't. This slight modification forces the existence of a dot in the domain, so only `asd.com` is valid.

**Comment by andryyy** [comment]
I always thought that was fine, if you want to route some crazy internal stuff with your mailcow. Not sure. For me personally it is fine to change it. @mkuron ?

**Comment by mkuron** [comment]
If you want to do crazy stuff, you can just comment out the validation. For most users, more strict validation makes things easier.

**Comment by andryyy** [comment]
Merciiiii

**Pull request merged**
