### PR TITLE
Update imapsync whitelist

### PR DESCRIPTION
**Pull request by mlfreeman2**
Added `inet4` option and `ssl1` option to whitelist.
1. `inet4` takes no args so it should be safe?
2. `ssl2` was already there so `ssl1` should be there as its counterpart.
3. Sorted whitelist alphabetically, removed redundant entries for `folderfirst`, `folderlast`, and `folderrec`

### CODE REVIEW

**Comment by andryyy** [comment]
Things that mailcow UI (as checkbox or whatever) should not be included here.

**Comment by andryyy** [comment]
Furthermore this is a list I don't want modified externally and esp not with a push to master without issue. :/

**Comment by mlfreeman2** [comment]
> Things that mailcow UI (as checkbox or whatever) should not be included here.

These two options are not checkboxes in the UI.

**Comment by mlfreeman2** [comment]
I'll open an issue in a little while.
Basically, this new whitelist broke editing existing jobs if they used an "unapproved" option.

**Comment by mlfreeman2** [comment]
Closed this and opened issue #4667 instead

**Pull request closed without merging**
