### PR TITLE
a little bit of security

### PR DESCRIPTION
**Pull request by JOduMonT**
Hide the version of NGINX, block XSS and more...
inspired by : https://gist.github.com/plentz/6737338

tested with : https://securityheaders.io
it pass the project from Grade : E fo B

### CODE REVIEW

**Review by mkuron — APPROVED** [review]

**Comment by andryyy** [comment]
This breaks Roundcube for those who have it installed. Should be in the docs.

**Comment by K2rool** [comment]
If your talking about the broken Roundcube issue that the non docker version had months ago that was due to the use of X-Frame-Options "DENY"; which break Roundcube due to the frame holding <pre>/skins/larry/watermark.html</pre> getting blocked which makes Roundcube near unusable.

I think config changes on this pull will work fine with users on Roundcube, not too sure about SoGo as I don't rely use it that much to be told.

.

**Comment by andryyy** [comment]
I see. :)

**Comment by andryyy** [comment]
Breaks SPDY: ERR_SPDY_PROTOCOL_ERROR

That's why you never just add some options blindly that sound like they make anything more secure. :-/

**Comment by mkuron** [comment]
Hmm, probably one of the SSL lines. The headers are unlikely have such an effect. They are the more important part anyway as they prevent XSS.

**Comment by andryyy** [comment]
Yes :( have had no time to check it yet, commented those lines for now.

**Pull request merged**
