### PR TITLE
Update lang.it.json

### PR DESCRIPTION
**Pull request by towerman86**
Translated more voices

### CODE REVIEW

**Comment by MAGICCC** [comment]
Cool thanks. Do you plan to create more commits? If yes then we dont need to merge the PR now

**Comment by towerman86** [comment]
I'm still translating as much as I can, but I prefer to save them here for not losing something 👍 
Do I have to tell you when I'm done?

**Comment by towerman86** [comment]
> Cool thanks. Do you plan to create more commits? If yes then we dont need to merge the PR now

I'm still translating as much as I can, but I prefer to save them here for not losing something 👍 
Do I have to tell you when I'm done?

**Comment by MAGICCC** [comment]
Sure no problem, just tell us here when we can merge :)

**Pull request closed without merging**
