### PR TITLE
Enable portainer (container monitoring)

### PR DESCRIPTION
**Pull request by v60fan**
Updated the docker-compose and added 2 section blocks to the nginx site.conf to enable portainer to be integrated

can then be accessed at: https://{MAILCOW_HOSTNAME}/portainer/

### CODE REVIEW

**Comment by ghost** [comment]
it's good idea.

**Comment by broedli** [comment]
Hey @v60fan,
I am not a huge fan of the idea on integrating this project into mailcow. What about a wiki entry explaining how to integrate portainer with mailcow, so users can choose if they want this graphical ui for docker (it's not overly complicated to modify the mailcow project to include this.)
That said, I've just tested your pull request and it seems to work fine.

**Comment by v60fan** [comment]
@broedli It's up to André really. Personally I like having something to more easily monitor, but I do view it as very tangential to the project. As someone had asked for it, and I knew how to do it, I thought it was worth creating the pull request so that everyone could see what needs changing and decide for themselves.

**Comment by andryyy** [comment]
Brad, can you move that to the docs? I really like the idea.

**Comment by v60fan** [comment]
I have added this to the docs as requested, so closing the pull request to merge into base code.

**Pull request closed without merging**
