### PR TITLE
[Netfilter] Exclude banning IPs when dovecot server not reacheble

### PR DESCRIPTION
**Pull request by dragoangel**

### CODE REVIEW

**Comment by DerLinkman** [comment]
It needs a rebuild of the netfilter container right?

**Comment by dragoangel** [comment]
Yes I think

**Comment by dragoangel** [comment]
Oh, and one note - this will impact only new setups or people who will click on reset button* in fail2ban settings

**Comment by DerLinkman** [comment]
Ok, that is maybe an idea for the docs? Clear the fail2ban Settings (if it is not there)

**Comment by dragoangel** [comment]
I think better for update notes, yes. Sort of:
`If you not have custom rules - reset them once after update. If you have custom rules please copy them to notes, reset rules and reaply your custom rules back`

**Comment by andryyy** [comment]
Did you verify this 100% works as intended?

**Comment by dragoangel** [comment]
Yes, and I not asking for a merge without checking. If you stop dovecot and try auth over smtp you will reproduce same log line. I validate it over regex101.

**Comment by DerLinkman** [comment]
So again: Safe to merge? You already said it but I want to be sure it is 😝

**Comment by dragoangel** [comment]
Yep :). I use this regex for a month.

**Comment by DerLinkman** [comment]
Alright then.

**Pull request merged**
