### PR TITLE
New interface for manage filters more userfriendly way

### PR DESCRIPTION
**Pull request by feldsam**
Hello, I programed new "user filters" for easier filters managing, without writing own scripts. User/Admin can define rules and sieve scripts are automatically generating as active sieve postfilter

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by andryyy** [comment]
Hi, that's very nice!

The reason I have not implemented it is the existence of SOGos own filter managment. It writes JSON to a user pref table and creates these filters when you save them. It does not detect changes to those filters in sieve, you'd need to change the JSON code and have SOGo itself update them. So any change to the "sogo" sieve script is destroyed as long as it is not changed within SOGo itself.

**Comment by feldsam** [comment]
oh, I did not observed it in SOGo, so probably waste of work. On the other hand, it is not bad have it in mailcow UI, just not connected with SOGo filters...

In future I have to ask first :) have mailcow some irc or slack?

**Comment by hachre** [comment]
Yes! `irc.freenode.net`, channel `#mailcow`

**Comment by andryyy** [comment]
We thought about making SOGo optional, so it would be a good feature then!

**Comment by Arkaniod** [comment]
Making SOGo optional would be a great idea, explicit for an Backup-MX running with Mailcow, where SOGo isn't needed

**Comment by feldsam** [comment]
What about this? Should I solve conflicts? or it is not planned to merge this?

**Comment by discofris** [comment]
Having SOGo as an optional module, would be a fantastic feature!
After each restart I manually stop the SOGo docker container.

**Comment by lavdnone** [comment]
Very useful. Maybe put it in to sieve_before ...
https://wiki1.dovecot.org/LDA/Sieve/Dovecot "Executing Multiple Scripts Sequentially"

**Comment by feldsam** [comment]
@andryyy what about this? should I solve conflicts and you merge it?

**Comment by andryyy** [comment]
As long as SOGo exists and is default, no. This will be confusing and breaking filters for SOGo users.

**Pull request closed without merging**
