### PR TITLE
add basic ldap support

### PR DESCRIPTION
**Pull request by etique57**
Not exactly sure of what I'm doing...

### CODE REVIEW

**Comment by mkuron** [comment]
Discussion was started in https://github.com/mailcow/mailcow-dockerized/pull/743#issuecomment-388651331 a month ago. Maybe @bkleiner / @str8labs, the original author, can explain what they did in this code, what works and what doesn't. Then we can try to finish up their LDAP work.

**Comment by neox8** [comment]
has anyone tried this build yet?

**Comment by it-toppp** [comment]
LDAP worked?

**Comment by pde-rent** [comment]
Why was this PR closed ? Anything wrong with the implementation ?

**Comment by mkuron** [comment]
The original developers never followed up and while it looks like a good start, it was definitely incomplete. Mailcow has changed quite a bit over time so that this solution will likely not work anymore.

**Pull request closed without merging**
