### PR TITLE
enable http3 in nginx

### PR DESCRIPTION
**Pull request by Zoey2936**

### CODE REVIEW

**Comment by DerLinkman** [comment]
How does it behave when someone uses a Reverse Proxy?

Did you've tested this with reverse proxies before?

**Comment by patschi** [comment]
I'd advise against merging this as of now. As per [nginx changelog](https://nginx.org/en/CHANGES) this setting is experimental, and just shortly after the initial release there was a bugfix. To me, this implies this not being stable as of now.

Having tested this previously, I had noticeable issues in getting http/3 to work with nginx on a reliable basis. As mailcow UI is a crucial part to daily operation and any automation using its API, I'd recommend not enabling it as of today. It's not mature enough to be enabled by default on all installations.

Beside this, http/3 requires UDP/443 to be allowed in the firewall and might require documentation changes as well.

**Comment by Zoey2936** [comment]
> I'd advise against merging this as of now. As per [nginx changelog](https://nginx.org/en/CHANGES) this setting is experimental, and just shortly after the initial release there was a bugfix. To me, this implies this not being stable as of now.
> 

I used the nginx-quic repo (before it was merged into nginx and released with v1.25.0) for a very long time now, and I had no issues so far. 

> Having tested this previously, I had noticeable issues in getting http/3 to work with nginx on a reliable basis. As mailcow UI is a crucial part to daily operation and any automation using its API, I'd recommend not enabling it as of today. It's not mature enough to be enabled by default on all installations.
> 

quic will only be used if the client supports it, there is no reason why http 1 / 1.1 / 2 should break and clients which don't support can't break, since they can't connect to the udp port. 

You need to have one listener with the reuseport AND quic option, all others are only allowed to have the quic option, otherwise it won't work. You also need to set the alt-svc header.

> Beside this, http/3 requires UDP/443 to be allowed in the firewall and might require documentation changes as well.

Thats true

> How does it behave when someone uses a Reverse Proxy?

there is no reverse proxies yeet which connect over quic to the backend, they will continue to use http1/1.1/2, so no change, if the proxy point to the http port nothing changes, since quic only works with tls

> Did you've tested this with reverse proxies before?

yes
```console
zoey@mx:~$ curl -I --http3 http://127.0.0.1:880
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 27 Jun 2023 14:11:07 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: PHPSESSID=<no-idea-if-this-needs-to-be-hidden>; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Alt-Svc: h3=":3443"; ma=86400
Strict-Transport-Security: max-age=15768000;
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin

zoey@mx:~$ curl -kI --http3 https://127.0.0.1:3443
HTTP/3 200 
server: nginx
date: Tue, 27 Jun 2023 14:09:08 GMT
content-type: text/html; charset=utf-8
vary: accept-encoding
set-cookie: PHPSESSID=<no-idea-if-this-needs-to-be-hidden>; path=/; secure; HttpOnly
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
alt-svc: h3=":3443"; ma=86400
strict-transport-security: max-age=15768000;
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-robots-tag: none
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin

zoey@mx:~$ curl -I --http3 https://mx.zvcdn.de # my outgoing reverse proxy also supports quic, nginx
HTTP/3 200 
date: Tue, 27 Jun 2023 14:10:20 GMT
content-type: text/html; charset=utf-8
vary: accept-encoding
vary: Accept-Encoding
set-cookie: PHPSESSID=<no-idea-if-this-needs-to-be-hidden>; path=/; secure; HttpOnly
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
alt-svc: h3=":3443"; ma=86400
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-robots-tag: none
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
alt-svc: h3=":443"; ma=86400

zoey@mx:~$ curl -I https://mx.zvcdn.de
HTTP/1.1 200 OK
Date: Tue, 27 Jun 2023 14:13:16 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
Vary: Accept-Encoding
Set-Cookie: PHPSESSID=<no-idea-if-this-needs-to-be-hidden>; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Alt-Svc: h3=":3443"; ma=86400
Strict-Transport-Security: max-age=15768000;
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Alt-Svc: h3=":443"; ma=86400
```

**Comment by patschi** [comment]
> I used the nginx-quic repo (before it was merged into nginx and released with v1.25.0) for a very long time now, and I had no issues so far.

Even if it works for you, it doesn't mean it works for everybody in every scenario at a larger scale. There might be edge-cases still need to be discovered.

> quic will only be used if the client supports it, there is no reason why http 1 / 1.1 / 2 should break and clients which don't support can't break, since they can't connect to the udp port.

As it's a experimental protocol, there might be still issues in its implementation in the client- or server-side rendering the site inaccessible. (Also taking into account that Chrome, Firefox, curl, .NET Framework, Safari, etc all have their own implementation)

> You need to have one listener with the reuseport AND quic option, all others are only allowed to have the quic option, otherwise it won't work. You also need to set the alt-svc header.

I'm aware of that and I've configured it exactly according to nginx's documentation. I've been chatting with @Thomas2500 and we were working independently on setting HTTP/3 up - it did not work on a reliable basis. Different HTTP calls were switching between HTTP/2 and HTTP/3, at times it was working and sometimes it just didn't - without any changes.

While I appreciate new protocols and like to give them a try for a few sites as well, I don't think enabling a experimental protocol implementation across thousands of production instances is the best way for now. Everyone can still decide on their own discretion to enable it on their setup.

I think the added benefit to the rather simple mailcow UI will be too marginal and barely noticeable - compared to "real" and more heavy-loaded websites. IMHO it's not worth the possible side effects and issues.

Again - I have absolutely nothing against new protocols, new exciting software-stuff or whatsoever; nor is this a personal thing. Working in the Enterprise IT field I'm leaning more towards "staying on the safe side" while HTTP/3 has had more time to evolve, being more battle-tested and considered stable.

**Comment by Zoey2936** [comment]
Do you talk about quic/http3 in general or about the implementation of it in nginx?

> I'm aware of that and I've configured it exactly according to nginx's documentation. I've been chatting with @Thomas2500 and we were working independently on setting HTTP/3 up - it did not work on a reliable basis. Different HTTP calls were switching between HTTP/2 and HTTP/3, at times it was working and sometimes it just didn't - without any changes.

What client did you used? Since if I do `while true; do curl -kIs --http3 https://127.0.0.1:3443 | head -n1; done` for a minute, it only responds with http3, also spamming f5 in edge only responds with h3. Nearly every browser supports it since over two years: https://caniuse.com/http3.

I understand that you don't like to implement this a month after nginx released it, but most clients support it already for years. The caddy web server uses it by default and from my view caddy is getting more popular. Nearly every Cloudflare protected site uses quic. There are already implementations like DoQ or DoH3.

But maybe you should at least remove the deprecated http2 option and move it to the main config.

**Comment by patschi** [comment]
> Do you talk about quic/http3 in general or about the implementation of it in nginx?

Only nginx's experimental implementation.

> What client did you used?

Chrome + Firefox.

> [...] but most clients support it already for years. The caddy web server uses it by default [...]

It's not just about the client-sided support. Caddy's HTTP/3 implementation might be stable at this point, but for nginx it isn't - those are entirely different implementations for the same protocol. Being stable in Caddy, doesn't mean it's with nginx.

> But maybe you should at least remove the deprecated http2 option and move it to the main config.

We could indeed. But I'm not sure if we should apply them now - just to have the option to rollback to earlier nginx versions, should it - for the very unlikely case - be needed at any point; e.g. if any critical bug is discovered. This allows us to rollback without reverting back all configuration changes.

I'm not sure if that would cause any side effects if users do have additional vhosts configured using the old parameters?

But I'd leave that up to @DerLinkman to decide.

**Comment by Habetdin** [comment]
There is also PR #5365 that doesn't enable HTTP3 yet but fixes the deprecated way of enabling HTTP2.

**Comment by Zoey2936** [comment]
> There is also PR #5365 that doesn't enable HTTP3 yet but fixes the deprecated way of enabling HTTP2.

thanks for the information!

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by Zoey2936** [comment]
How to reopen this?

**Comment by benedict1337** [comment]
If you are using a Nginx docker image built with **[BoringSSL](https://github.com/nginx-modules/docker-nginx-boringssl)** or LibreSSL, HTTP/3 QUIC works fine. Currently the Nginx mainline image with OpenSSL does not fully support HTTP/3.

**But I don't think mailcow needs HTTP/3 support since HTTP/2 is efficient enough.**

**Comment by patschi** [comment]
> How to reopen this?

As this PR is mainly about HTTP/3 implementation and has its own discussion, I'd suggest to raise a new PR to adjust the (deprecated) HTTP/2 settings. 
cc @DerLinkman

**Comment by Zoey2936** [comment]
> If you are using a Nginx docker image built with **[BoringSSL](https://github.com/nginx-modules/docker-nginx-boringssl)** or LibreSSL, HTTP/3 QUIC works fine. Currently the Nginx mainline image with OpenSSL does not fully support HTTP/3.

That could be true... I only used nginx built with the quictls fork

> **But I don't think mailcow needs HTTP/3 support since HTTP/2 is efficient enough.**

That is not an argument from my view. Using improved protocols is always good (if they work).

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
