### PR TITLE
Update SOGo to 5.7.1

### PR DESCRIPTION
**Pull request by MAGICCC**
This PR updates SOGo to 5.7.1
Since SOGo is managed by Alinto now the repo URL and public key changed.

Releasenotes: https://github.com/Alinto/sogo/releases/tag/SOGo-5.7.1

New image **mailcow/sogo:1.110** on Dockerhub available

### CODE REVIEW

**Comment by DerLinkman** [comment]
Don´t work as expected:

image

@andryyy maybe a coinsident with your change regarding sieve (https://github.com/mailcow/mailcow-dockerized/commit/ad8b7f08944c05854d8d6bf87ae13cd7ecd92f5a)?

**Comment by DerLinkman** [comment]
> Don´t work as expected:
> 
> image
> 
> @andryyy maybe a coinsident with your change regarding sieve ([ad8b7f0](https://github.com/mailcow/mailcow-dockerized/commit/ad8b7f08944c05854d8d6bf87ae13cd7ecd92f5a))?

Nope it´s a issue with SOGo. Cannot reproduce that with SOGo 5.7.0 and your changes @andryyy.

**Comment by DerLinkman** [comment]
@MAGICCC can you test this please as well?

I´ve published a newer Version of Dovecot with that fix included to Docker Hub

**Comment by MAGICCC** [comment]
Yes looks fine @DerLinkman 
thanks for fixing :) Can you also edit the compose-file for the new dovecot version?

**Comment by DerLinkman** [comment]
No need for this. I´ll reuse the Version @andryyy already pushed which is in staging.

**Pull request merged**
