### PR TITLE
Add rspamd score and symbols to quarantine detail view

### PR DESCRIPTION
**Pull request by friedPotat0**
Adds the rspamd score and all symbols with their single scores and their options to the quarantine detail view. The options can be inspected by hovering over the symbols.

### CODE REVIEW

**Comment by andryyy** [comment]
Nice. :) Can you post a screenshot?

**Comment by friedPotat0** [comment]
image

**Comment by andryyy** [comment]
Woat. That's nice. Thanks!

**Comment by andryyy** [comment]
Can you mail me to andre.peters@debinux.de ?

**Pull request merged**
