### PR TITLE
Allow setting ACL_ANYONE in the configuration

### PR DESCRIPTION
**Pull request by tisoft**
This makes sharing to "Any authenticated User" (#1954) configurable. Default is disabled as it is currently the case.

### CODE REVIEW

**Comment by andryyy** [comment]
You even revert the patch, nice. :)

Let me run some tests, okay?

**Comment by tisoft** [comment]
Yeah reverting the patch has the benefit of allowing an admin to enable and disable this at will. :)

Maybe the location of the "acl_anyone" configuration file is not the best, since that is outside the container and someone might think he can fiddle around with it. It will be overwritten at container restart anyway... So maybe something inside the container like /tmp is more appropriate.

Using ```acl_anyone = </usr/local/etc/dovecot/acl_anyone``` to read the value from a file was the only solution i found to dynamically change the dovecot config based on an environment variable without doing a sed replacement. Unfortunately %{env:ACL_ANYONE} replacement does not work here, since the string is not evaluated by the acl plugin. It is directly string compared. Also no newlines may be contained in the file. All learned the hard way. So if you think of simplifying this, I already tried some simpler methods and failed. :)

**Comment by K2rool** [comment]
Should this line https://github.com/mailcow/mailcow-dockerized/blob/e10db26825fe0d6915d826511207dcdfac2ae4cd/docker-compose.yml#L150 not be like this <pre> - ACL_ANYONE=${ACL_ANYONE:-disallow} </pre> that way the default value is also set in docker-compose.yml not ever user will use update.sh some user with heavily modified install will be doing manual updates so unless the user adds it to mailconf.conf it will be undefined.

**Comment by tisoft** [comment]
I have added the default to the compose file. Thanks for catching that!

**Comment by andryyy** [comment]
Can you check the PR? Something seems wrong.

And sorry, totally forgot about it. Will merge it asap, but please check it first. :)

**Comment by tisoft** [comment]
Updated to latest master

**Comment by andryyy** [comment]
Niiiice, thank you!

**Pull request merged**
