### PR TITLE
dovecot: replace solr fts with flatcurve (xapian)

### PR DESCRIPTION
**Pull request by DerLinkman**
Basically PR: https://github.com/mailcow/mailcow-dockerized/pull/4456

More details soon...

### CODE REVIEW

**Comment by gelbphoenix** [comment]
Are there any updates for this PR?

**Comment by DerLinkman** [comment]
Which issue? Flatcurve is already integrated and can be toggled already.

This PR is only fully implementing Flatcurve into mailcow and therefore removing Solr.

**Comment by gelbphoenix** [comment]
> Which issue? Flatcurve is already integrated and can be toggled already.
> 
> This PR is only fully implementing Flatcurve into mailcow and therefore removing Solr.

I meant PR, sry for that error on my side.

I also meant as a question how far the switch from solr to flatcurve is also if the switch will be happening in December. Only to have a sort of technical update for Mailcow admins.

(If this isn't the space for that I excuse myself for this mistake.)

**Comment by DerLinkman** [comment]
Yeah from my side the switch in this pr is done. So: Yes it will take part in December.

**Pull request merged**
