### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by flobeier**
Duplicate entries removed and remaining sorted alphabetically, indentation through tabs changed to spaces

### CODE REVIEW

**Comment by hachre** [comment]
FYI: This will most likely get declined because it's against `master`. It should be against `dev`!

**Comment by flobeier** [comment]
@hachre thanks for the heads-up, I'll do a rebase.

**Comment by andryyy** [comment]
That will not work. This does merge master to dev, which is right now problematic. Can you please clone dev and push from there?

**Comment by andryyy** [comment]
And thanks for the cleanup. :-)

**Pull request closed without merging**
