### PR TITLE
Update lang.nl.json

### PR DESCRIPTION
**Pull request by Geitenijs**

### CODE REVIEW

**Comment by ntimo** [comment]
Hey, thanks for the new translations. Could you maybe check if the following translations are. missing? This are the dict keys that are missing when comparing the lang.nl.json with lang.en.json.

- success.sogo_profile_reset
- admin.yes
- admin.no
- admin.quarantine_bcc
- mailbox.yes
- mailbox.no

**Comment by andryyy** [comment]
Thanks. :)

The yes/no flags are probably not worth a translation. :)

**Comment by Geitenijs** [comment]
@ntimo Done! Thanks for letting me know :)

**Comment by andryyy** [comment]
Thank you :)

**Pull request merged**
