### PR TITLE
[CI] Added Mailcow tests & image builds

### PR DESCRIPTION
**Pull request by ntimo**
This MR adds the mailcow integration tests to run via GitHub CI/CD. It also adds a build for the Docker images on overy push using a matrix build which is quite performant (it takes 5 minutes for all images). The images are not yet pushed anywhere just build.

P.S. I also renamed the twitter job name because it triggered me that it uses dashes instead of spaces like the other ones.

### CODE REVIEW

**Review by DerLinkman — APPROVED** [review]
Looks good to me! The general Docker Build Idea is not bad but I'm afraid of a automatic build which can cause images to break. But yeah if something happens like this we can correct it manually of course.

**Comment by MAGICCC** [comment]
> Looks good to me! The general Docker Build Idea is not bad but I'm afraid of a automatic build which can cause images to break. But yeah if something happens like this we can correct it manually of course.

At the moment its only build - no push. Afterwards we could decide to tag, build, push but indeed need to be tested before a release is happening :)

Also its just me but maybe we can change following to multiline and sort by name?
```
images: ["unbound-mailcow", "clamd-mailcow", "rspamd-mailcow", "php-fpm-mailcow",
                "sogo-mailcow", "dovecot-mailcow", "postfix-mailcow", "acme-mailcow",
                "netfilter-mailcow", "watchdog-mailcow", "dockerapi-mailcow", "solr-mailcow",
                "olefy-mailcow"]

**Comment by MAGICCC** [comment]
Btw did you encounter ratelimits from GH IPs during pull? I dont know if GH IPs are maybe whitelisted or if they spawn in different  (IPv6) subnets? I am sure we wont run into any ratelimits but we can consider to use a dockerhub account (later)

**Comment by ntimo** [comment]
> Btw did you encounter ratelimits from GH IPs during pull? I dont know if GH IPs are maybe whitelisted or if they spawn in different (IPv6) subnets? I am sure we wont run into any ratelimits but we can consider to use a dockerhub account (later)



> Btw did you encounter ratelimits from GH IPs during pull? I dont know if GH IPs are maybe whitelisted or if they spawn in different (IPv6) subnets? I am sure we wont run into any ratelimits but we can consider to use a dockerhub account (later)

In my testing I did not had any ratelimit issues no. 

"For publicly accessible containers we are working with docker hub to make sure you will not be impacted by the new rate limits. If you need private containers we still do not have a solution for that problem for forks of public repos."
From https://github.com/actions/virtual-environments/issues/1445#issuecomment-713861495

**Comment by ntimo** [comment]
> Also its just me but maybe we can change following to multiline and sort by name?
> 
> ```
> images: ["unbound-mailcow", "clamd-mailcow", "rspamd-mailcow", "php-fpm-mailcow",
>                 "sogo-mailcow", "dovecot-mailcow", "postfix-mailcow", "acme-mailcow",
>                 "netfilter-mailcow", "watchdog-mailcow", "dockerapi-mailcow", "solr-mailcow",
>                 "olefy-mailcow"]
> ```

The order has actually been taken from the compose override :D But yeah I will order them.

**Comment by DerLinkman** [comment]
Since it won´t push anything to Docker Hub right know it is ok for me :)

**Comment by larena1** [comment]
Please change images to yaml list style. It looks a bit ugly right now

```
images:
  - acme-mailcow
  - ... 
  - ... 
```

**Comment by MAGICCC** [comment]
> Please change images to yaml list style. It looks a bit ugly right now
> 
> ```
> images:
>   - acme-mailcow
>   - ... 
>   - ... 
> ```

Something like https://github.com/mailcow/mailcow-dockerized/pull/4688?

**Pull request merged**
