### PR TITLE
Replace weird character to the correct `'`

### PR DESCRIPTION
**Pull request by h3ssan**
## Contribution Guidelines

* [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree them

## What does this PR include?

In `generate_config.sh` and `update.sh`, replacing a weird character to the correct one, from  `´` to `'`.
Show as `�`

### Short Description

No need

###  Affected Containers

None

## Did you run tests?

No need

### What did you tested?

No need

### What were the final results? (Awaited, got)

No need

### CODE REVIEW

**Comment by DerLinkman** [comment]
Thank you!

**Comment by fingo2409** [comment]
@h3ssan @DerLinkman 

./update.sh: line 407: syntax error near unexpected token `)'
./update.sh: line 407: `  --skip-ping-check    -   Skip ICMP Check to public DNS resolvers (Use it only if you've blocked any ICMP Connections to your mailcow machine)'
Seems this broke the update.sh script

**Comment by h3ssan** [comment]
> @h3ssan @DerLinkman
> 
> ./update.sh: line 407: syntax error near unexpected token `)' ./update.sh: line 407: ` --skip-ping-check - Skip ICMP Check to public DNS resolvers (Use it only if you've blocked any ICMP Connections to your mailcow machine)' Seems this broke the update.sh script

I’ll check, just a minute

**Comment by ptroc** [comment]
I can confirm that `'`  brakes quotes of help msg on my end also

**Comment by h3ssan** [comment]
Issue confirmed, will fix it now

**Comment by DerLinkman** [comment]
Yes...

**Comment by DerLinkman** [comment]
I thought you tested it?

**Comment by h3ssan** [comment]
Fixed in `https://github.com/mailcow/mailcow-dockerized/pull/6034`, sorry for the issue

**Comment by h3ssan** [comment]
> I thought you tested it?

@DerLinkman sorry, since I working in 2 instances, on my VPS and local one, looks like I tested the VPS one but the modified one was on my local machine. So sorry.

**Comment by h3ssan** [comment]
@Fingo2409 and @ptroc issue is solved, please do `git pull` and enjoy.

**Comment by DerLinkman** [comment]
Would do git fetch & git checkout origin/master update.sh to let the update.sh script recover only :)

**Pull request merged**
