### PR TITLE
dockerapi with python3

### PR DESCRIPTION
**Pull request by christianbur**
Uses dockerapi with python3, because python2 is End of Life on January 1, 2020.
This is the second PR, the first one can be found here https://github.com/mailcow/mailcow-dockerized/pull/2342

### CODE REVIEW

**Comment by Kraeutergarten** [comment]
Do we need the pyOpenSSL?
 I think you don't use it anymore.

**Comment by andryyy** [comment]
I wonder when we actually needed it. Edit: I'm blind.

Yes, we can probably remove it.

**Comment by christianbur** [comment]
pyOpenSSL is not really needed anymore, because I create the certificate file directly on the cli with openssl. 
In the old script it was needed to create the certifiact with python-openssl. 

I've updated the Dockerfile.

**Comment by andryyy** [comment]
Thanks. Sorry guys, need a little bit more time. :-(

**Comment by andryyy** [comment]
I will rebuild the image :)

**Pull request merged**
