### PR TITLE
Modified branch switch in generate_config.sh

### PR DESCRIPTION
**Pull request by maljes**
#4725 prevents [mailcow-ansiblerole](https://github.com/mailcow/mailcow-ansiblerole) from installing mailcow automatically by adding a `read` statement (https://github.com/mailcow/mailcow-dockerized/commit/4f380debb5a1b4e0079dde717ed3c6a455629b43#diff-be47f8b7221a40f99901465896a1702267321312166e16282e83fb0a313854ceR144) without giving the option to answer the question with environment variables.

My changes will add the possibility to define the mailcow branch by an environment variable to be able to bypass input.

### CODE REVIEW

**Comment by DerLinkman** [comment]
Very nice! It still works with the input?

Did you tested it in general?

**Comment by maljes** [comment]
> Very nice! It still works with the input?
> 
> 
> 
> Did you tested it in general?

Yes i tested it. Without the environment variable, everything works as before and you would not notice the change.

**Comment by MAGICCC** [comment]
I guess this will also fix the [mailcow Integration Tests](https://github.com/mailcow/mailcow-dockerized/runs/8154597594?check_suite_focus=true#step:5:219) because it fails to generate mailcow.conf file.
And we may need to add the new environment variable [here](https://github.com/mailcow/mailcow-integration-tests/blob/master/roles/mailcow/tasks/main.yml#L40) too if I am not wrong @ntimo

**Comment by maljes** [comment]
> I guess this will also fix the [mailcow Integration Tests](https://github.com/mailcow/mailcow-dockerized/runs/8154597594?check_suite_focus=true#step:5:219) because it fails to generate mailcow.conf file.
> 
> And we may need to add the new environment variable [here](https://github.com/mailcow/mailcow-integration-tests/blob/master/roles/mailcow/tasks/main.yml#L40) too if I am not wrong @ntimo 

I think for the integration test it would be the same fix as for the ansible-role. I also pushed a fix for this here https://github.com/mailcow/mailcow-ansiblerole/pull/28

**Comment by MAGICCC** [comment]
I just tested the changes, but the while loop won't finish because MAILCOW_BRANCH is not set in the loop. 
Using following it works
```diff
echo "Which branch of mailcow do you want to use?"
echo ""
echo "Available Branches:"
echo "- master branch (stable updates) | default, recommended [1]"
echo "- nightly branch (unstable updates, testing) | not-production ready [2]"
sleep 1

while [ -z "${MAILCOW_BRANCH}" ]; do
  read -r -p  "Choose the Branch with it´s number [1/2] " branch
  case $branch in
    [2])
- git_branch="nightly"
+ MAILCOW_BRANCH="nightly"
      ;;
    *)
- git_branch="master"
+ MAILCOW_BRANCH="master"
    ;;
  esac
done
```

The if below should set the right env variable then anyway
```
if [ ! -z "${MAILCOW_BRANCH}" ]; then
  git_branch=${MAILCOW_BRANCH}
fi
```

**Comment by maljes** [comment]
@MAGICCC you're right. I replaced the variables and pushed my changes.

**Review by DerLinkman — CHANGES_REQUESTED** [review]
Looks good but please change the git branch variable in Line 452 as well.

**Comment by maljes** [comment]
> Looks good but please change the git branch variable in Line 452 as well.

I don't really know why i should change the variable at this line @DerLinkman.  At line 158 (https://github.com/mailcow/mailcow-dockerized/pull/4741/files#diff-be47f8b7221a40f99901465896a1702267321312166e16282e83fb0a313854ceR158) the variable `git_branch` will be set to the value of `MAILCOW_BRANCH`. `MAILCOW_BRANCH` won't be used after that.

**Comment by DerLinkman** [comment]
Yeah my bad. Looks fine. @MAGICCC can you confirm it works with that changes now?

**Comment by MAGICCC** [comment]
Yes looks good @DerLinkman 

env variable with 'master'
```
root@mailcow-dev:~# export MAILCOW_BRANCH="master"


root@mailcow-dev:~# echo ${MAILCOW_BRANCH}
master


root@mailcow-dev:~# ./generate_config.sh
Found Docker Compose Plugin (native).
Setting the DOCKER_COMPOSE_VERSION Variable to native
Notice: You´ll have to update this Compose Version via your Package Manager manually!
Press enter to confirm the detected value '[value]' where applicable or enter a custom value.
Mail server hostname (FQDN) - this is not your mail domain, but your mail servers hostname: moo.test.cow
Timezone [Etc/UTC]:
Which branch of mailcow do you want to use?

Available Branches:
- master branch (stable updates) | default, recommended [1]
- nightly branch (unstable updates, testing) | not-production ready [2]
[...]


root@mailcow-dev:~# cat data/web/inc/app_info.inc.php | grep "MAILCOW_BRANCH"
  $MAILCOW_BRANCH="master";

```



env variable with 'nightly'

```
root@mailcow-dev:~# export MAILCOW_BRANCH="nightly"


root@mailcow-dev:~# echo ${MAILCOW_BRANCH}
nightly


root@mailcow-dev:~# ./generate_config.sh
Found Docker Compose Plugin (native).
Setting the DOCKER_COMPOSE_VERSION Variable to native
Notice: You´ll have to update this Compose Version via your Package Manager manually!
Press enter to confirm the detected value '[value]' where applicable or enter a custom value.
Mail server hostname (FQDN) - this is not your mail domain, but your mail servers hostname: moo.test.cow
Timezone [Etc/UTC]:
Which branch of mailcow do you want to use?

Available Branches:
- master branch (stable updates) | default, recommended [1]
- nightly branch (unstable updates, testing) | not-production ready [2]
[...]



root@mailcow-dev:~# cat data/web/inc/app_info.inc.php | grep "MAILCOW_BRANCH
  $MAILCOW_BRANCH="nightly";
```


normal
```
root@mailcow-dev:~# export MAILCOW_BRANCH=""
root@mailcow-dev:~# echo ${MAILCOW_BRANCH}

root@mailcow-dev:~# ./generate_config.sh
Found Docker Compose Plugin (native).
Setting the DOCKER_COMPOSE_VERSION Variable to native
Notice: You´ll have to update this Compose Version via your Package Manager manually!
Press enter to confirm the detected value '[value]' where applicable or enter a custom value.
Mail server hostname (FQDN) - this is not your mail domain, but your mail servers hostname: moo.test.cow
Timezone [Etc/UTC]:
Which branch of mailcow do you want to use?

Available Branches:
- master branch (stable updates) | default, recommended [1]
- nightly branch (unstable updates, testing) | not-production ready [2]
Choose the Branch with it´s number [1/2] 1
[...]

root@mailcow-dev:~# cat data/web/inc/app_info.inc.php | grep "MAILCOW_BRANCH"
  $MAILCOW_BRANCH="master";
```

```
root@mailcow-dev:~# export MAILCOW_BRANCH=""
root@mailcow-dev:~# echo ${MAILCOW_BRANCH}

root@mailcow-dev:~# ./generate_config.sh
Found Docker Compose Plugin (native).
Setting the DOCKER_COMPOSE_VERSION Variable to native
Notice: You´ll have to update this Compose Version via your Package Manager manually!
Press enter to confirm the detected value '[value]' where applicable or enter a custom value.
Mail server hostname (FQDN) - this is not your mail domain, but your mail servers hostname: moo.test.cow
Timezone [Etc/UTC]:
Which branch of mailcow do you want to use?

Available Branches:
- master branch (stable updates) | default, recommended [1]
- nightly branch (unstable updates, testing) | not-production ready [2]
Choose the Branch with it´s number [1/2] 2
[...]

root@mailcow-dev:~# cat data/web/inc/app_info.inc.php | grep "MAILCOW_BRANCH"
  $MAILCOW_BRANCH="nightly";
```

**Review by DerLinkman — APPROVED** [review]

**Pull request merged**
