### PR TITLE
Allow to easily add custom plugins to rspamd

### PR DESCRIPTION
**Pull request by sriccio**
Since rspamd **1.9.2** we'll be able to load custom modules from plugins.d
directory.

This allow to add and configure plugins easily from the
data/conf/rspamd/plugins.d

Also loading config for custom plugins need rspamd.conf.local or
optionally rspamd.conf.override.

I added support for this in the docker-compose.yml

Idea came while i was writing a custom plugin for Cyren antispam
gateway, which can be found here: https://github.com/sriccio/rspamd-plugins

### CODE REVIEW

**Comment by andryyy** [comment]
I will check this asap. :) Thanks.

**Comment by apintocr** [comment]
After this update RSpam watchdog keeps failing with "Rspamd settings check failed"

However it seems that rspamd is working correctly...

I'm using the default configs.

Any way I can debug this @andryyy @sriccio ?

**Comment by andryyy** [comment]
Whats the output of `ls -la data/conf/rspamd`?

**Comment by apintocr** [comment]
```
apinto@artemis:/srv/mailcow$ ls -la data/conf/rspamd
total 44
drwxr-xr-x  9 apinto          vanguardly      4096 May  6 09:01 .
drwxr-xr-x 11 apinto          vanguardly      4096 Mar 15 19:11 ..
drwxr-xr-x  2 systemd-network systemd-journal 4096 May  6 09:53 custom
drwxr-xr-x  2 apinto          vanguardly      4096 Mar 12 20:37 dynmaps
drwxr-xr-x  2 systemd-network systemd-journal 4096 May  6 09:53 local.d
drwxr-xr-x  2 apinto          vanguardly      4096 Sep 15  2018 lua
drwxr-xr-x  2 apinto          vanguardly      4096 May  6 09:01 meta_exporter
drwxr-xr-x  2 systemd-network systemd-journal 4096 May  6 09:53 override.d
drwxr-xr-x  2 root            root            4096 May  6 09:01 plugins.d
-rw-r--r--  1 root            root              20 May  6 09:01 rspamd.conf.local
-rw-r--r--  1 root            root              24 May  6 09:01 rspamd.conf.override
```

**Comment by andryyy** [comment]
Shouldn't be a problem, I don't see anything wrong. Please run update and check rspamd-mailcow logs if the problem persists. Set `level = "info"` in `data/conf/rspamd/override.d/logging.inc` before debugging (if it persists).

**Comment by apintocr** [comment]
Thank you @andryyy for your help.

But the problem persists.

I've enabled `level = info` and restarted containers.

How shall I proceed? :)
What should I look for on the logs?

**Comment by apintocr** [comment]
Not sure if it is related, but IPV6 Nat is also failing:

`IPv6 NAT warning: ipv6nat mailcow container was not started at least 30s after siblings (not an error)`

**Comment by apintocr** [comment]
I've found this in the logs:

` lua; rspamd.local.lua:139: dynamic ratelimit request for domain mydomain.com returned invalid or empty data ("") or error ("nil")`

Can it be related?

**Comment by andryyy** [comment]
IPv6: **not an error** :) That's ok and wanted.

No, the empty return for rl is not an error.

**Comment by apintocr** [comment]
Thank you.

> IPv6: **not an error** :) That's ok and wanted.
> 
> No, the empty return for rl is not an error.

Thank you.

Any tips on how to debug this?

**Comment by andryyy** [comment]
Full rspamd-mailcow logs would be useful. :) At least from starting Rspamd until it fails and is restarted by watchdog.

You could also enable debug_modules in logging.inc (add settings).

Also run `docker-compose exec php-fpm-mailcow curl http://nginx:8081/settings.php` to test for valid settings output.

And `docker-compose exec rspamd-mailcow rspamadm configtest` (some warnings are okay, syntax OK is important).

You could also try to remove the new files and restart rspamd-mailcow.

**Comment by apintocr** [comment]
Thank you very much @andryyy .

Output of `docker-compose exec rspamd-mailcow rspamadm configtest`
```
old syntax for ratelimits: 360 / 1m
old style rate bucket config detected for to_ip: 360 / 1m
old syntax for ratelimits: 45 / 1m
old style rate bucket config detected for to: 45 / 1m
old syntax for ratelimits: 100 / 1s
old style rate bucket config detected for bounce_to: 100 / 1s
old syntax for ratelimits: 180 / 1m
old style rate bucket config detected for to_ip_from: 180 / 1m
old syntax for ratelimits: 100 / 1s
old style rate bucket config detected for bounce_to_ip: 100 / 1s
cannot find dependency on symbol MAILCOW_WHITE
symbol 'NEURAL_SPAM' has its score defined but there is no corresponding rule registered
symbol 'NEURAL_HAM' has its score defined but there is no corresponding rule registered
syntax OK
```

Output for: `docker-compose exec php-fpm-mailcow curl http://nginx:8081/settings.php`
```
settings {
  watchdog {
    priority = 10;
    rcpt_mime = "/null@localhost/i";
    from_mime = "/watchdog@localhost/i";
    apply "default" {
      actions {
        reject = 9999.0;
        greylist = 9998.0;
        "add header" = 9997.0;
      }
    }
  }
  whitelist_onedomainpt {
    from = "/^.*@seg\-social\.pt$/i";
    priority = 5;
    rcpt = "/.*@onedomain.pt/i";
    rcpt = "/.*@onedomain.com/i";
    apply "default" {
      MAILCOW_WHITE = -999.0;
    }
    symbols [
      "MAILCOW_WHITE"
    ]
  }
  whitelist_mime_onedomainpt {
    from_mime = "/^.*@seg\-social\.pt$/i";
    priority = 5;
    rcpt = "/.*@onedomain.pt/i";
    rcpt = "/.*@onedomain.com/i";
    apply "default" {
      MAILCOW_WHITE = -999.0;
    }
    symbols [
      "MAILCOW_WHITE"
    ]
  }
  whitelist_anotherdomainpt {
    from = "/^.*@cofidis\.pt$/i";
    from = "/^.*@.*\.pt$/i";
    from = "/^.*@.*\.com$/i";
    priority = 5;
    rcpt = "/.*@anotherdomain.pt/i";
    rcpt = "/.*@mkt.anotherdomain.pt/i";
    apply "default" {
      MAILCOW_WHITE = -999.0;
    }
    symbols [
      "MAILCOW_WHITE"
    ]
  }
  whitelist_mime_anotherdomainpt {
    from_mime = "/^.*@cofidis\.pt$/i";
    from_mime = "/^.*@.*\.pt$/i";
    from_mime = "/^.*@.*\.com$/i";
    priority = 5;
    rcpt = "/.*@anotherdomain.pt/i";
    rcpt = "/.*@mkt.anotherdomain.pt/i";
    apply "default" {
      MAILCOW_WHITE = -999.0;
    }
    symbols [
      "MAILCOW_WHITE"
    ]
  }
  traps {
    priority = 9;
    want_spam = yes;
  }
}
```

**Comment by apintocr** [comment]
I've also edited `data/conf/rspamd/override.d/logging.inc` to have the following contents:
```
type = "console";
systemd = false;
level = "info";

.include "$CONFDIR/logging.inc"
.include(try=true; priority=20) "$CONFDIR/override.d/logging.custom.inc"

debug_modules = ["settings"]
```

I'll post logs soon.

**Comment by apintocr** [comment]
@andryyy could this be related?
```
rspamd-mailcow_1     | 2019-05-06 12:49:59 #15(controller) <rznbhc>; map; rspamd_map_cache_cb: cached data is now expired (gen mismatch 3 != 4) for http://nginx:8081/forwardinghosts.php
rspamd-mailcow_1     | 2019-05-06 12:50:00 #15(controller) <oxhd99>; map; rspamd_map_cache_cb: cached data is now expired (gen mismatch 3 != 4) for http://nginx:8081/settings.php
```

**Comment by apintocr** [comment]
I think I found the issue!

For some reason these where the settings:
image

After I changed them to:
image

It seems to be fixed.

----
I just do not understand why the value was changed.
I'm 100% sure I have not changed it, and I just ran the update script this morning.

In any case, Thank you very much for your support @andryyy

**Comment by andryyy** [comment]
Hm, you should set them in `data/conf/rspamd/local.d/metrics.conf`. :) That's more reliable, I think. Don't know why it kicked the dynamic settings. :/

**Pull request merged**
