### PR TITLE
Admin login to SOGo

### PR DESCRIPTION
**Pull request by mkuron**
From #2373. i still need to review whether this introduces any security concerns before we merge it.

### CODE REVIEW

**Comment by andryyy** [comment]
Thanks. :)

**Comment by extremeshok** [comment]
Any progress on this ?

**Comment by andryyy** [comment]
I think this will be a merger. But let's give @mkuron time to check!

**Comment by mkuron** [comment]
Sorry, I‘ve been too busy lately. Hopefully this weekend.

**Comment by extremeshok** [comment]
I was not sure if we were waiting for something to be coded or bug to be fixed, was going to see if I could do anything to help.

**Comment by sriccio** [comment]
Just a little note for @mhofer117, I've tested the multiple concurrent admin logins (commit https://github.com/mailcow/mailcow-dockerized/pull/2388/commits/6a7b4387ebd54180decc3e3ea6b2c0c9bf44fc09) and it works perfectly :)

**Comment by andryyy** [comment]
It works. The only concern is security at the moment.

**Comment by mkuron** [comment]
I don't understand how this works. The master password is stored in `$_SESSION`. Then nginx makes an internal request to the script to retrieve it. That would only work if nginx somehow copied the session cookie into that internal request?

Also, what does `SOGoEncryptionKey` do? What does SOGo encrypt with it and where is the encrypted text stored?

**Comment by mhofer117** [comment]
Hi @mkuron, thanks for taking the time to review

Yes, the master password is stored in the $_SESSION so we don't need to read the file on every auth_request call.
Yes, nginx auth_request actually has the same context as the normal request, even though it's executed internally. This includes the php session cookie and means php will automatically find the users session on session_start() with this cookie.

[SOGoEncryptionKey](https://sogo.nu/files/docs/SOGoInstallationGuide.html) is used to encrypt remote calendar passwords in case of proxy auth. I'm not sure why this would be important but it's mentioned in the SOGo docs so I figured it might be a sensible option.

and thanks @sriccio for testing

**Comment by extremeshok** [comment]
Could this be merged with the default being disabled.

A notice could be added that this could introduce a security risk, this would allow far more user testing and battle hardening.

**Comment by mhofer117** [comment]
Actually this is already the case.
On update the configuration option will be added with value "n" which disables the feature completely

**Comment by mkuron** [comment]
I think this is ok. Please resolve the merge conflict, update the image versions and merge. We should definitely keep it disabled by default, but it's a nice feature for those who need it. I have triple-checked that it does not have any side effects if is disabled and am reasonably certain it is secure when enabled.

Also, this infrastructure could be used to make the SOGo link in the top bar when a user logs in take them directly to SOGo without having to log in again.

**Comment by extremeshok** [comment]
> Also, this infrastructure could be used to make the SOGo link in the top bar when a user logs in take them directly to SOGo without having to log in again.


Now that would be useful for users ;P

**Comment by extremeshok** [comment]
Can this be merged ?

**Comment by andryyy** [comment]
Let's just create some docs first. :)

**Comment by mhofer117** [comment]
Let me know what type of documentation you'd like to have and if I can help.

**Comment by andryyy** [comment]
Just anything would be fine. :) Perhaps inside Debugging & Troubleshooting, not sure. Just a small doc about what it is and what it does.

I will merge it afterwards.

**Comment by mhofer117** [comment]
Hey @andryyy I finally had enough time to add some documentation. Hope it's what you expected.

**Comment by andryyy** [comment]
@mhofer117 Absolutely, thank you!!

**Comment by extremeshok** [comment]
Thanks to everyone who made this possible

**Comment by mhofer117** [comment]
Thanks for merging :)

**Comment by andryyy** [comment]
Thank YOU! :)

**Comment by andryyy** [comment]
Can you check the open issues about this?

**Comment by mhofer117** [comment]
Yes you can ping me if there are issues. As far as I can see there was only one with the proxy and you aolved it, right?

**Comment by andryyy** [comment]
Indeed, thank you. :)

**Pull request merged**
