### PR TITLE
Update sogo-auth.php

### PR DESCRIPTION
**Pull request by cero1988**
#initialize db before validating credentials #5397

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by cero1988** [comment]
> Thanks for contributing!
> 
> I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`. See the attached picture on how to change the base branch to `staging`:
> 
> 

excuse me, I noticed that in the staged branch this issue is already been resolved, I will close the bug and the pull request

**Comment by cero1988** [comment]
I noticed that this issue reguard only the nightly branch

**Comment by cero1988** [comment]
I noticed that this issue reguard only the nightly branch

**Comment by cero1988** [comment]
I noticed that this issue regard only the nightly branch
is correct to mantain the pull request on the nightly branch ?

**Comment by MAGICCC** [comment]
No in staging

**Comment by cero1988** [comment]
This issue Is new of the nightly branch, how can I contribute to resolve this issue ?
In my home installation I have resolved by adding this line to sogo-auth.php for make working the eas authentications

**Comment by MAGICCC** [comment]
@DerLinkman is updating the nightly branch from the staging branch every x days, so it would be better to push it in staging first

**Comment by rbreunung** [comment]
I think I experienced the same issue. For me it is blocking CalDAV/CardDAV and EAS.

**Comment by FreddleSpl0it** [comment]
@MAGICCC merging into nightly should be fine since this feature is only available there.
Thanks @cero1988, seems that i missed that. When you go ahead and require_once the prerequisites you should be able to remove the other 2 require_once since they are already in the prerequisites.

**Pull request merged**
