### PR TITLE
Update dockerapi to python3

### PR DESCRIPTION
**Pull request by christianbur**
so i ported dockerapi to python3, someone who knows the api a bit better should test it now. 

Sorry I did the diff with the master and not with dev, do I have to set the pull reqest again for dev?

https://github.com/mailcow/mailcow-dockerized/issues/2291

### CODE REVIEW

**Comment by andryyy** [comment]
Nice, I will check it! :-)

**Comment by christianbur** [comment]
but it's not finished yet, I need to get used to it.

**Comment by andryyy** [comment]
No problem, it's a start.

**Comment by christianbur** [comment]
I found a bug in changing the password of Rspamd UI, so please wait. 

```
sql_shell = container.exec_run(["/bin/bash"], stdin=True, socket=True, user='mysql')
sql_socket = sql_shell.output;  #  # don't "decode("utf-8")" it, it's a socket (it's wrong in PR)

worker_shell = container.exec_run(["/bin/bash"], stdin=True, socket=True, user='_rspamd')
worker_socket = worker_shell.output;   # don't "decode("utf-8")" it, it's a socket (it's wrong in PR)
```
I don't understand these two calls at the moment, a socket comes back (e.g. worker_socket), ok. The variable worker_socket is of type socket.SocketIO, and sendall is for objects of type [socket](https://docs.python.org/3/library/socket.html), but how do I convert it?

if you want to change the Rspan UI password you will always get the following error message in the gui
 "'SocketIO' object has no attribute 'sendall'"

**Comment by christianbur** [comment]
@andryyy 
Hi, in the next days I will submit a new PR. I have completely rebuilt the function container_post, it now works without "100x if, elif, else", which makes the code much easier to read and maintain. The generation of ssl certs has also been simplified to one line. I still have to test the whole thing, but so far it looks pretty good, until the problem described above is still not solved.

**Comment by andryyy** [comment]
It is very, very important to keep the pipe for changing the password to not expose the password, please don't drop this.

A more simplified and cleaner version would be nice. This script actually sucks, yes.

**Comment by christianbur** [comment]
i will take over all functions of the api 1:1, i just want to make the code more readable. 

exaple

```
 class container_post(Resource):
  def post(self, container_id, post_action):
    if container_id and container_id.isalnum() and post_action:
      try:
        """Dispatch container_post api call"""
        if post_action == 'exec':
          if not request.json or not 'cmd' in request.json:
            return jsonify(type='danger', msg='cmd is missing')
          if not request.json or not 'task' in request.json:
            return jsonify(type='danger', msg='task is missing')

          api_call_method_name = '__'.join(['container_post', str(post_action), str(request.json['cmd']), str(request.json['task']) ])
        else:
          api_call_method_name = '__'.join(['container_post', str(post_action) ])

        api_call_method = getattr(self, api_call_method_name, lambda container_id: jsonify(type='danger', msg='container_post - api call  unknown'))


        output_debug = True
        if output_debug:
          print("api call: %s, container_id: %s" % (api_call_method_name, container_id))
          if post_action == 'exec':
            print("request.json: %s" % request.json)
          output = api_call_method(container_id)
          print("output: %s" % output)
          return output
        else:
          return api_call_method(container_id)
      except Exception as e:
        print("error - container_post: %s" % str(e))  
        return jsonify(type='danger', msg=str(e))

    else:
      return jsonify(type='danger', msg='invalid container id or missing action')        


  # api call: container_post - post_action: stop
  def container_post__stop(self, container_id):
    for container in docker_client.containers.list(all=True, filters={"id": container_id}):
      container.stop()
    return jsonify(type='success', msg='command completed successfully')


  # api call: container_post - post_action: start
  def container_post__start(self, container_id):
    for container in docker_client.containers.list(all=True, filters={"id": container_id}):
      container.start()
    return jsonify(type='success', msg='command completed successfully')


  # api call: container_post - post_action: restart
  def container_post__restart(self, container_id):
    for container in docker_client.containers.list(all=True, filters={"id": container_id}):
      container.restart()
    return jsonify(type='success', msg='command completed successfully')


  # api call: container_post - post_action: top
  def container_post__top(self, container_id):
    for container in docker_client.containers.list(all=True, filters={"id": container_id}):
      return jsonify(type='success', msg=container.top())


  # api call: container_post - post_action: stats
  def container_post__stats(self, container_id):
    for container in docker_client.containers.list(all=True, filters={"id": container_id}):
      return jsonify(type='success', msg=container.stats(decode=True, stream=False))


  # api call: container_post - post_action: exec - cmd: mailq - task: delete
  def container_post__exec__mailq__delete(self, container_id):
    r = re.compile("^[0-9a-fA-F]+$")
    filtered_qids = filter(r.match, request.json['items'])
    if filtered_qids:
      flagged_qids = ['-d %s' % i for i in filtered_qids]
      sanitized_string = str(' '.join(flagged_qids));

      for container in docker_client.containers.list(filters={"id": container_id}):
        postsuper_r = container.exec_run(["/bin/bash", "-c", "/usr/sbin/postsuper " + sanitized_string])
        return exec_run_handler('generic', postsuper_r)


```

**Comment by andryyy** [comment]
Thanks. :) You keep the output formats, too?

**Comment by christianbur** [comment]
input and output of the api remain unchanged.

**Comment by christianbur** [comment]
The PR can be closed, I have submitted my current changes in https://github.com/mailcow/mailcow-dockerized/pull/2342. As soon as I solved the problem with exec_run I will submit a new RP with Python3.

**Pull request closed without merging**
