### PR TITLE
[Web] change tfa flow

### PR DESCRIPTION
**Pull request by FreddleSpl0it**
### Changes
Here I have made a few more changes related to the tfa flow. I did this because a user on the Telegram channel showed that you can only use one authenticator for tfa. This problem is probably related to an older issue. ([#4308](https://github.com/mailcow/mailcow-dockerized/issues/4308))

After the changes, admins or domain admins, with an active tfa, are greeted with a modal where they can select a registered authenticator to log in.

### Update 07.03.2022
I have enabled 2 factor authentication for user as requested [(#4494)](https://github.com/mailcow/mailcow-dockerized/issues/4494)

Screenshot 2022-02-22 093709

**I have tested this so far, but would still be happy if others would also test it, because there are a lot of changes :).**

### Fixes
- probably fixes [#4308](https://github.com/mailcow/mailcow-dockerized/issues/4308)
- Domainadmins are currently unable to register webauthn due to a bug
- The password confirmation when registering or deactivating tfa is always true no matter what you enter.

### CODE REVIEW

**Comment by MAGICCC** [comment]
Neat, I cant test it because I dont have a $yubikey

**Comment by FreddleSpl0it** [comment]
if you want to test webauthn then you can emulate multiple authenticator in chrome 
[https://developer.chrome.com/docs/devtools/webauthn/](https://developer.chrome.com/docs/devtools/webauthn/)

The only thing I could not test is Yubico OTP

**Comment by MAGICCC** [comment]
I received my Yubikey today and added it to my cow and applied your changes.
~~Seems I don't see the TFA confirmation dialog anymore. Tried to clear and using different browsers...~~
Selector is fine but after login I have only an empty page when using my Yubikey, TOTP is fine
Maybe also needs a rebase on master branch

Need to check why Webauth doesnt work, maybe because my reverseproxy?!

**Comment by MAGICCC** [comment]
Works now as expected. @andryyy or @DerLinkman, would be great if anyone could also check.

**Comment by DerLinkman** [comment]
Will test this tomorrow.

**Pull request merged**
