### PR TITLE
Add pre and post update hook

### PR DESCRIPTION
**Pull request by alxhlz**
This pr adds a pre and post update hook to mailcow which can be helpful if you run some kind of reverse proxy in front of your mailcow installation that has to be restarted due to several reasons.

It simply checks if the required files exists and runs them.

`pre_update_hook.sh`
`post_update_hook.sh`

### CODE REVIEW

**Comment by andryyy** [comment]
Hi,
Can you please add it to the docs?

**Comment by alxhlz** [comment]
Done in https://github.com/mailcow/mailcow-dockerized-docs/pull/284

**Comment by alxhlz** [comment]
image

**Comment by MAGICCC** [comment]
What about to put them in `helper-scripts` folder?

**Comment by alxhlz** [comment]
Hmm, I am open to that change but isn't the helper-scripts folder for already working and existing scripts that ships with mailcow instead of custom scripts by the user?

**Comment by MAGICCC** [comment]
Yes indeed. Maybe it's just me and my head that I like having a clean root folder and putting scripts in subfolder(s) :)

**Pull request merged**
