### PR TITLE
[PHP-FPM] Updated pm config, increase values

### PR DESCRIPTION
**Pull request by feldsam**
Related to #931

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by andryyy** [comment]
Hi, first of all: thanks!
How about providing these options as env vars we could set in mailcow.conf? We should keep a default value (as is) and override them when set in mailcow.conf. Or we even move the file to data/conf...

**Comment by feldsam** [comment]
What about mysql config, that also contains options like max-connections and max allowed packed and is not configurable via mailcow.conf

Look on related issue #931 please, there can be possible optimizations on debug page probably.

**Comment by andryyy** [comment]
That's available from data/conf/mysql/my.cnf 👍 

I check the debug page.

**Comment by feldsam** [comment]
ok, so I can do it similarly or what you suggest?

**Comment by feldsam** [comment]
Closing this PR as I see it is already done better way in dev branch.

**Pull request closed without merging**
