### PR TITLE
[Web] apple config app passwords enhancements + translations

### PR DESCRIPTION
**Pull request by feldsam**
Signed-off-by: Kristian Feldsam <feldsam@gmail.com>

Hi @mkuron, I changed a few things in your work, please check.

- user.php - keep template and data definition in each other
- *.twig - use of `format` instead of `replace` and show `<br>` only on `lg` screens

Desktop:  
Screenshot 2023-09-04 at 8 42 49

Mobile:  
Screenshot 2023-09-04 at 8 43 06

### CODE REVIEW

**Review by mkuron — APPROVED** [review]

**Comment by waja** [comment]
ping

**Comment by DerLinkman** [comment]
Yeah sorry for the closing, wasn't my intention.

**Comment by feldsam** [comment]
@andryyy what about this?

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by DerLinkman** [comment]
Would like to merge this inside the BS5 Branch. @FreddleSpl0it there is a change (a very small one :D) for the general BS with that patch.

That is the main reason why i would like to implement this directly to BS5 instead of BS3. So we skip a port so to say.

**Comment by feldsam** [comment]
Hi @DerLinkman, I just updated this PR to match latest staging branch.

**Comment by feldsam** [comment]
Hi @DerLinkman, what about this PR?

**Comment by feldsam** [comment]
PR is approved, so I am closing this and pushing directly to staging

**Comment by feldsam** [comment]
ah, looks like my permission to commit to this project was removed :(

**Pull request merged**
