### PR TITLE
Add simplified Chinese language translations

### PR DESCRIPTION
**Pull request by EHfive**
Generally, we use language code 'zh-cn' to represent simplified Chinese, 'zh-tw' in the case of traditional Chinese.
Due to the limitation of https://github.com/usrz/bootstrap-languages used by mailcow UI, there is only code 'zh' avaliable for Chinese. That's why I use 'zh' instead.

Maybe we should switch from bootstrap-languages in future so that we can add support for traditional Chinese.

### CODE REVIEW

**Comment by MAGICCC** [comment]
Wew nice!
You can also add some strings here:
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/dovecot.conf#L90

**Comment by EHfive** [comment]
Oh, I missed that.

**Comment by EHfive** [comment]
> Wew nice!
> You can also add some strings here:
> https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/dovecot.conf#L90

Added.

**Comment by EHfive** [comment]
I think it's ready to be reviewed.

**Comment by MAGICCC** [comment]
LGTM @andryyy

**Comment by andryyy** [comment]
Very cool. Thank you!
Did you check Dovecot is ok with the chinese chars in the config file?

**Comment by MAGICCC** [comment]
It's starting and does not crash for me

**Comment by EHfive** [comment]
> Very cool. Thank you!
> Did you check Dovecot is ok with the chinese chars in the config file?

I don't think it would be a problem because `dovecot.conf` stored as 'UTF-8'.
And, yes, I did't observed any errors.

**Comment by andryyy** [comment]
Let me check that too and then merge it. :)

**Comment by andryyy** [comment]
Thank you!!!

**Pull request merged**
