### PR TITLE
[Netfilter] Implemented exponentially incrementing bantime

### PR DESCRIPTION
**Pull request by th-joerger**
Implemented exponentially incrementing bantime, removed active_window code that did nothing, cleanly initialized dictionary

This PR implements #5086 in the most basic form.

Container can be checked out and tested by replacing:

```
    netfilter-mailcow:
      image: mailcow/netfilter:1.51
```

with

```
    netfilter-mailcow:
      image: thorjoerger/netfilter:1.51
```

in docker-compose.yml

### CODE REVIEW

**Comment by mkuron** [comment]
We should probably cap the exponential growth at some point (maybe at 24 hours). IP addresses do occasionally get reassigned, so we don't want to punish the new owner of an IP address with a two-year ban time even if the old owner deserved it for getting banned 20 times.

**Comment by th-joerger** [comment]
> We should probably cap the exponential growth at some point (maybe at 24 hours). IP addresses do occasionally get reassigned, so we don't want to punish the new owner of an IP address with a two-year ban time even if the old owner deserved it for getting banned 20 times.

I agree and also mentioned this as optional in my original issue. But this option (as well as incremental ban times itself) should be exposed as options in the UI. This requires work in other containers. I can do this, but only if @DerLinkman agrees that this has any chance to be merged back.

**Comment by DerLinkman** [comment]
Yeah sounds good to me!

No reason not to implement it in the ui as well.

**Comment by th-joerger** [comment]
I implemented the UI elements and api, tested it on my instance and seems to work fine. I added all the translations I felt confident enough.

grafik

**Comment by DerLinkman** [comment]
Thanks for your work, really appreciate it! Will test it next week and stage it if everything goes well :)

**Comment by th-joerger** [comment]
Thanks a lot!

**Comment by th-joerger** [comment]
> Thanks for your work, really appreciate it! Will test it next week and stage it if everything goes well :)

Did you get the chance to test it? Does everything work? @DerLinkman

**Comment by FreddleSpl0it** [comment]
i have tested it and it works on a freshly installed mailcow.
However if i have the latest mailcow installed and upgrade the netfilter container i get the following error

```
Clearing all bans
Initializing mailcow netfilter chain
Watching Redis channel F2B_CHANNEL
Exception in thread Thread-2 (autopurge):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/server.py", line 430, in autopurge
    MAX_BAN_TIME = int(f2boptions['max_ban_time'])
KeyError: 'max_ban_time'
```

**Comment by th-joerger** [comment]
I updated my PR and reworked the option handling. Can you test if this fixes the problem for you? I updated the docker container from my first post here so you can use this for testing @FreddleSpl0it

**Comment by FreddleSpl0it** [comment]
Looks good! it's working now as expected.
The only thing is, that there are no default values in the mailcow UI but netfilter uses it's default values `max_ban_time = 10000` and `ban_time_increment = True`. 
I think that the netfilter container needs to push the default values to redis if nothing is found.

**Comment by th-joerger** [comment]
Do you have any idea where this is done initially? Because the only place where the defaults are mentioned (which I am aware of) are in the netfilter/server.py, so that should be the place where they are initially set.

**Comment by th-joerger** [comment]
Ok, I think I found and fixed the problem. This should work now. Can you verify again?

**Comment by FreddleSpl0it** [comment]
Found the issue. it's happening in the refreshF2boptions method

Edit: looks good i will test it

**Comment by th-joerger** [comment]
I thought this whole option code felt a little off, so I looked a bit deeper into it and it seems, those redis suboptions where the result of a migration to netfilter from fail2ban itself in 38a819771bfdb49500f59048419c7ff170aa9737. They will never be set in a deployment, except you upgrade mailcow in a single step from a 2018 deployment to a 2023 deployment.

**Review by FreddleSpl0it — APPROVED** [review]

**Pull request merged**
