### PR TITLE
Enable autodiscover to work with app passwords

### LINKED ISSUE #4513: Autodiscover dont work with "App passwords"
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

when using "App passwords" to add a account on android via "Exchange" android is unable to pull the autodiscover.xml so did some digging using priasoft tool (https://www.priasoft.com/autodiscover-testing-tool/) i found out that if i disable f2a and using my standard password everything works like it should but if i enable f2s and use a  "App passwords" it gives a 401 error

### Logs

```bash
2022-03-19T23:07:04 :: Getting a list of AutoDiscover urls to use...
2022-03-19T23:07:04 :: Getting currently configured DNS servers from host...
2022-03-19T23:07:04 ::     DNS IP: 8.8.8.8
2022-03-19T23:07:04 ::     DNS IP: 1.1.1.1
2022-03-19T23:07:04 :: Attempting to determine the AutoDiscover endpoint to use.
2022-03-19T23:07:04 :: Checking to see of mailbox ID is Office 365
2022-03-19T23:07:04 :: Checking MX record for 'domain.com' to determine if it is Office 365.
2022-03-19T23:07:04 :: MX query returned 1 records
2022-03-19T23:07:04 ::     mail.domain.com.
2022-03-19T23:07:04 :: Mail domain does not appear to be Office 365.
2022-03-19T23:07:04 :: Checking local domain SCP records, if host is domain joined.
2022-03-19T23:07:04 :: No SCP information found.
2022-03-19T23:07:04 :: Search for locally cached AutoDiscover.xml files.
2022-03-19T23:07:04 ::     Found 0 files
2022-03-19T23:07:04 :: End of cached files analysis
2022-03-19T23:07:04 :: Adding http://domain.com/autodiscover/autodiscover.xml to list of redirection test hosts
2022-03-19T23:07:04 :: Adding https://domain.com/autodiscover/autodiscover.xml to list of redirection test hosts
2022-03-19T23:07:04 :: SRV query returned 1 records
2022-03-19T23:07:04 ::     mail.domain.com.
2022-03-19T23:07:04 :: Calculated the following 7 urls for AutoDiscover lookup, and will be queried in the order listed...
2022-03-19T23:07:04 ::      0. ROOT: https://domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:04 ::      1. AUTOD: https://autodiscover.domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:04 ::      2. REDIRECT: http://domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:04 ::      3. REDIRECT: http://autodiscover.domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:04 ::      4. REDIRECT: https://domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:04 ::      5. REDIRECT: https://autodiscover.domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:04 ::      6. SRV: https://mail.domain.com./autodiscover/autodiscover.xml
2022-03-19T23:07:04 :: 
2022-03-19T23:07:05 :: Request will be sent to: http://domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:05 :: HttpWebRequest object created
2022-03-19T23:07:05 :: HttpWebRequest set to disallow auto redirect
2022-03-19T23:07:05 :: HttpWebRequest set to GET method
2022-03-19T23:07:05 :: HttpWebRequest ContentType set to 'text/xml'
2022-03-19T23:07:05 :: Sending request to the server...please wait...
2022-03-19T23:07:05 :: The remote server returned an error: (401) Unauthorized.
2022-03-19T23:07:05 :: 
2022-03-19T23:07:05 :: Request will be sent to: http://autodiscover.domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:05 :: HttpWebRequest object created
2022-03-19T23:07:05 :: HttpWebRequest set to disallow auto redirect
2022-03-19T23:07:05 :: HttpWebRequest set to GET method
2022-03-19T23:07:05 :: HttpWebRequest ContentType set to 'text/xml'
2022-03-19T23:07:05 :: Sending request to the server...please wait...
2022-03-19T23:07:05 :: The remote server returned an error: (401) Unauthorized.
2022-03-19T23:07:05 :: 
2022-03-19T23:07:05 :: Request will be sent to: https://domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:05 :: HttpWebRequest object created
2022-03-19T23:07:05 :: HttpWebRequest set to disallow auto redirect
2022-03-19T23:07:05 :: HttpWebRequest set to GET method
2022-03-19T23:07:05 :: HttpWebRequest ContentType set to 'text/xml'
2022-03-19T23:07:05 :: Sending request to the server...please wait...
2022-03-19T23:07:05 :: The remote server returned an error: (401) Unauthorized.
2022-03-19T23:07:05 :: 
2022-03-19T23:07:05 :: Request will be sent to: https://autodiscover.domain.com/autodiscover/autodiscover.xml
2022-03-19T23:07:05 :: HttpWebRequest object created
2022-03-19T23:07:05 :: HttpWebRequest set to disallow auto redirect
2022-03-19T23:07:05 :: HttpWebRequest set to GET method
2022-03-19T23:07:06 :: HttpWebRequest ContentType set to 'text/xml'
2022-03-19T23:07:06 :: Sending request to the server...please wait...
2022-03-19T23:07:06 :: The remote server returned an error: (401) Unauthorized.
```

### Steps to reproduce

1. enable f2a
2. set a "App password"
3. run test

### System information

| Question | Answer |
| --- | --- |
| My operating system | Unraid |
| Is Apparmor, SELinux or similar active? | Yes |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 15GB, 6|
| Docker Version (`docker version`) | 20.10.13 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | Nginx Proxy Manager |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
YOUR OUTPUT GOES HERE
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 
2476K 1653M DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0 
2476K 1653M DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
2163K 1624M ACCEPT     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 193K   12M DOCKER     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0
 120K   18M ACCEPT     all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0
 191K   12M ACCEPT     all  --  br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0  
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0 

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.249         tcp dpt:6379
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.4           tcp dpt:8983
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.9           tcp dpt:3306
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:12345
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:4190
   21  1116 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:995
   49  2772 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:993
   23  1196 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:143
   42  2296 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:110
   20  1080 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:587
   31  1700 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:465
   35  1916 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:25
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.10          tcp dpt:8443
  907 54420 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.10          tcp dpt:8080

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination 
 120K   18M DOCKER-ISOLATION-STAGE-2  all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
2540K 1683M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0   

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 DROP       all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0  
 124K   20M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0   

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination 
2540K 1683M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0 
```

ip6tables -L -vn:
```
N/A Disabled
```

iptables -L -vn -t nat:
```

 pkts bytes target     prot opt in     out     source               destination 
    0     0 RETURN     all  --  br-mailcow *       0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0  
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:7654 to:172.22.1.249:6379
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:18983 to:172.22.1.4:8983
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:13306 to:172.22.1.9:3306
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.250:12345
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4190 to:172.22.1.250:4190
   21  1116 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:172.22.1.250:995
   49  2772 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:172.22.1.250:993
   23  1196 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:172.22.1.250:143
   42  2296 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:172.22.1.250:110
   20  1080 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:172.22.1.253:587
   31  1700 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:172.22.1.253:465
   35  1916 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:172.22.1.253:25
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8443 to:172.22.1.10:8443
  907 54420 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.22.1.10:8080

```

ip6tables -L -vn -t nat:
```
N/A Disabled
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
N/A
```

### PR DESCRIPTION
**Pull request by mkuron**
Fixes #4513 reported by @Alacard

### CODE REVIEW

**Comment by DerLinkman** [comment]
Tested?

**Comment by mkuron** [comment]
@Alacard says it works.

**Comment by DerLinkman** [comment]
Alrighty.

**Comment by jmber** [comment]
Yes it works. 
It was forgotten on this commit in the past. The check_login function was changed:
https://github.com/mailcow/mailcow-dockerized/commit/e13bc242a4130c1333f995c1bf02369c06e3a16d

**Pull request merged**
