### PR TITLE
Fix sorting dates and missing Rspamd attributes in datatables

### LINKED ISSUE #4911: Logging problem - sort order problem - Moocember Update 2022
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
- Some logs (autodiscover, acme, api, mailcow UI) can not be sorted on time. Looks like random sort. Sorting newest first doesn't work for these logs

Created [new issue](https://github.com/mailcow/mailcow-dockerized/issues/4912#issue-1510122622) for rspamd items: 
_- After upgrading to Moocember Update 2022 GUI logs show invalid values. rspamd set all event dates to 1-1-1970 01:00 
- Score and Scan Time show: [object Object]_ 
```

### Logs:

```plain text
No errors in logs. Docker container logs show valid data
```


### Steps to reproduce:

```plain text
Install new 2022-12 and look in logs. Restarting doesn't help.
```


### Which branch are you using?

master

### Operating System:

Debian 11

### Server/VM specifications:

2GB, 2CPU

### Is Apparmor, SELinux or similar active?

No

### Virtualization technology:

KVM

### Docker version:

20.10.22 

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-12

### Reverse proxy:

NA

### Logs of git diff:

```plain text
None
```


### Logs of iptables -L -vn:

```plain text
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                                pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                                                                                                                                                                                                                                                           Chain FORWARD (policy DROP 0 packets, 0 bytes)                                                                                                                                                                                                pkts bytes target     prot opt in     out     source               destination                                                                                                                                                              19090   15M DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0                                                                                                                                                              19090   15M DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0                                                                                                                                                 15492   14M ACCEPT     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED                                                                                                                      1518 94979 DOCKER     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0                                                                                                                                                             2080  857K ACCEPT     all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0                                                                                                                                                        1508 94403 ACCEPT     all  --  br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0                                                                                                                                                          12M 1096M ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED                                                                                                                           14  1132 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0                                                                                                                                                                 12M 1111M ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0                                                                                                                                                                 0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0                                                                                                                                                                                                                                                                                                                                                                                                           Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                               pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                                                                                                                                                                                                                                                           Chain DOCKER (2 references)                                                                                                                                                                                                                   pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                  8   780 ACCEPT     udp  --  !docker0 docker0  0.0.0.0/0            172.17.0.3           udp dpt:22124                                                                                                                                        5   292 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:9443                                                                                                                                         0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:8000                                                                                                                                         0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.249         tcp dpt:6379                                                                                                                                   0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.5           tcp dpt:8983                                                                                                                                   0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.9           tcp dpt:3306                                                                                                                                   5   300 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:587                                                                                                                                    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:12345                                                                                                                                  0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:4190                                                                                                                                   1    52 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:465                                                                                                                                    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:995                                                                                                                                    2   120 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:25                                                                                                                                     0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:993                                                                                                                                    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:143                                                                                                                                    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:110                                                                                                                                    2   104 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.10          tcp dpt:443                                                                                                                                    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.10          tcp dpt:80                                                                                                                                                                                                                                                                                                                                                                              Chain DOCKER-ISOLATION-STAGE-1 (1 references)                                                                                                                                                                                                 pkts bytes target     prot opt in     out     source               destination                                                                                                                                                               2080  857K DOCKER-ISOLATION-STAGE-2  all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0                                                                                                                                          12M 1111M DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0                                                                                                                                                27M 3217M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0                                                                                                                                                                                                                                                                                                                                                                                                             Chain DOCKER-ISOLATION-STAGE-2 (2 references)                                                                                                                                                                                                 pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                  0     0 DROP       all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0                                                                                                                                                                0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0                                                                                                                                                                 12M 1136M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0                                                                                                                                                                                                                                                                                                                                                                                                             Chain DOCKER-USER (1 references)                                                                                                                                                                                                              pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                27M 3217M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```


### Logs of ip6tables -L -vn:

```plain text
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                                pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                                                                                                                                                                                                                                                           Chain FORWARD (policy DROP 0 packets, 0 bytes)                                                                                                                                                                                                pkts bytes target     prot opt in     out     source               destination                                                                                                                                                               7498 6286K DOCKER-ISOLATION-STAGE-1  all      *      *       ::/0                 ::/0                                                                                                                                                       3413 5987K ACCEPT     all      *      br-mailcow  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED                                                                                                                      3520  240K DOCKER     all      *      br-mailcow  ::/0                 ::/0                                                                                                                                                                   561 59211 ACCEPT     all      br-mailcow !br-mailcow  ::/0                 ::/0                                                                                                                                                             3519  240K ACCEPT     all      br-mailcow br-mailcow  ::/0                 ::/0                                                                                                                                                                 0     0 ACCEPT     all      *      docker0  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED                                                                                                                          489 29384 DOCKER     all      *      docker0  ::/0                 ::/0                                                                                                                                                                        0     0 ACCEPT     all      docker0 !docker0  ::/0                 ::/0                                                                                                                                                                    489 29384 ACCEPT     all      docker0 docker0  ::/0                 ::/0                                                                                                                                                                                                                                                                                                                                                                                                                Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                               pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                                                                                                                                                                                                                                                           Chain DOCKER (2 references)                                                                                                                                                                                                                   pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                  0     0 ACCEPT     udp      !docker0 docker0  ::/0                 fd00:dead:beef:c0:0:242:ac11:3  udp dpt:22124                                                                                                                             0     0 ACCEPT     tcp      !docker0 docker0  ::/0                 fd00:dead:beef:c0:0:242:ac11:2  tcp dpt:9443                                                                                                                              0     0 ACCEPT     tcp      !docker0 docker0  ::/0                 fd00:dead:beef:c0:0:242:ac11:2  tcp dpt:8000                                                                                                                              0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::e  tcp dpt:587                                                                                                                                 0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:4190                                                                                                                                0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::e  tcp dpt:465                                                                                                                                 0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:995                                                                                                                                 1    80 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::e  tcp dpt:25                                                                                                                                  0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:993                                                                                                                                 0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:143                                                                                                                                 0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:110                                                                                                                                 0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::d  tcp dpt:443                                                                                                                                 0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::d  tcp dpt:80                                                                                                                                                                                                                                                                                                                                                                           Chain DOCKER-ISOLATION-STAGE-1 (1 references)                                                                                                                                                                                                 pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                561 59211 DOCKER-ISOLATION-STAGE-2  all      br-mailcow !br-mailcow  ::/0                 ::/0                                                                                                                                                 0     0 DOCKER-ISOLATION-STAGE-2  all      docker0 !docker0  ::/0                 ::/0                                                                                                                                                    638K 1011M RETURN     all      *      *       ::/0                 ::/0                                                                                                                                                                                                                                                                                                                                                                                                                  Chain DOCKER-ISOLATION-STAGE-2 (2 references)                                                                                                                                                                                                 pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                  0     0 DROP       all      *      br-mailcow  ::/0                 ::/0                                                                                                                                                                     0     0 DROP       all      *      docker0  ::/0                 ::/0                                                                                                                                                                    23702 2887K RETURN     all      *      *       ::/0                 ::/0
```


### Logs of iptables -L -vn -t nat:

```plain text
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                           pkts bytes target     prot opt in     out     source               destination                                                                                                                                                               3323  131K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL                                                                                                                                                                                                                                                                                                                                                                    Chain INPUT (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                                pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                                                                                                                                                                                                                                                           Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                               pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                  0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL                                                                                                                                                                                                                                                                                                                                                                    Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                          pkts bytes target     prot opt in     out     source               destination                                                                                                                                                               1235 92834 MASQUERADE  all  --  *      !br-mailcow  172.22.1.0/24        0.0.0.0/0                                                                                                                                                            294 18400 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0                                                                                                                                                                 0     0 MASQUERADE  udp  --  *      *       172.17.0.3           172.17.0.3           udp dpt:22124                                                                                                                                          0     0 MASQUERADE  tcp  --  *      *       172.17.0.2           172.17.0.2           tcp dpt:9443                                                                                                                                           0     0 MASQUERADE  tcp  --  *      *       172.17.0.2           172.17.0.2           tcp dpt:8000                                                                                                                                           0     0 MASQUERADE  tcp  --  *      *       172.22.1.249         172.22.1.249         tcp dpt:6379                                                                                                                                           0     0 MASQUERADE  tcp  --  *      *       172.22.1.5           172.22.1.5           tcp dpt:8983                                                                                                                                           0     0 MASQUERADE  tcp  --  *      *       172.22.1.9           172.22.1.9           tcp dpt:3306                                                                                                                                           0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:587                                                                                                                                            0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:12345                                                                                                                                          0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:4190                                                                                                                                           0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:465                                                                                                                                            0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:995                                                                                                                                            0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:25                                                                                                                                             0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:993                                                                                                                                            0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:143                                                                                                                                            0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:110                                                                                                                                            0     0 MASQUERADE  tcp  --  *      *       172.22.1.10          172.22.1.10          tcp dpt:443                                                                                                                                            0     0 MASQUERADE  tcp  --  *      *       172.22.1.10          172.22.1.10          tcp dpt:80                                                                                                                                                                                                                                                                                                                                                                                      Chain DOCKER (2 references)                                                                                                                                                                                                                   pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                  2   120 RETURN     all  --  br-mailcow *       0.0.0.0/0            0.0.0.0/0                                                                                                                                                                0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0                                                                                                                                                                   3   275 DNAT       udp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:22124 to:172.17.0.3:22124                                                                                                                     5   292 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:9443 to:172.17.0.2:9443                                                                                                                       0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8000 to:172.17.0.2:8000                                                                                                                       0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:7654 to:172.22.1.249:6379                                                                                                                  0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:18983 to:172.22.1.5:8983                                                                                                                   0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:13306 to:172.22.1.9:3306                                                                                                                   6   383 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:172.22.1.253:587                                                                                                                    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.250:12345                                                                                                                0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4190 to:172.22.1.250:4190                                                                                                                  1    52 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:172.22.1.253:465                                                                                                                    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:172.22.1.250:995                                                                                                                    2   120 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:172.22.1.253:25                                                                                                                      0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:172.22.1.250:993                                                                                                                    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:172.22.1.250:143                                                                                                                    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:172.22.1.250:110                                                                                                                    2   104 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.22.1.10:443                                                                                                                     0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.22.1.10:80
```


### Logs of ip6tables -L -vn -t nat:

```plain text
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                           pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                 92  7360 DOCKER     all      *      *       ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL                                                                                                                                                                                                                                                                                                                                                                    Chain INPUT (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                                pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                                                                                                                                                                                                                                                           Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                               pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                  0     0 DOCKER     all      *      *       ::/0                !::1                  ADDRTYPE match dst-type LOCAL                                                                                                                                                                                                                                                                                                                                                                    Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)                                                                                                                                                                                          pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                466 43566 MASQUERADE  all      *      !br-mailcow  fd4d:6169:6c63:6f77::/64  ::/0                                                                                                                                                              0     0 MASQUERADE  all      *      !docker0  fd00:dead:beef:c0::/80  ::/0                                                                                                                                                                   0     0 MASQUERADE  udp      *      *       fd00:dead:beef:c0:0:242:ac11:3  fd00:dead:beef:c0:0:242:ac11:3  udp dpt:22124                                                                                                                    0     0 MASQUERADE  tcp      *      *       fd00:dead:beef:c0:0:242:ac11:2  fd00:dead:beef:c0:0:242:ac11:2  tcp dpt:9443                                                                                                                     0     0 MASQUERADE  tcp      *      *       fd00:dead:beef:c0:0:242:ac11:2  fd00:dead:beef:c0:0:242:ac11:2  tcp dpt:8000                                                                                                                     0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::e  fd4d:6169:6c63:6f77::e  tcp dpt:587                                                                                                                                      0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:4190                                                                                                                                     0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::e  fd4d:6169:6c63:6f77::e  tcp dpt:465                                                                                                                                      0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:995                                                                                                                                      0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::e  fd4d:6169:6c63:6f77::e  tcp dpt:25                                                                                                                                       0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:993                                                                                                                                      0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:143                                                                                                                                      0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:110                                                                                                                                      0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::d  fd4d:6169:6c63:6f77::d  tcp dpt:443                                                                                                                                      0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::d  fd4d:6169:6c63:6f77::d  tcp dpt:80                                                                                                                                                                                                                                                                                                                                                                                Chain DOCKER (2 references)                                                                                                                                                                                                                   pkts bytes target     prot opt in     out     source               destination                                                                                                                                                                  0     0 RETURN     all      br-mailcow *       ::/0                 ::/0                                                                                                                                                                     0     0 RETURN     all      docker0 *       ::/0                 ::/0                                                                                                                                                                        0     0 DNAT       udp      !docker0 *       ::/0                 ::/0                 udp dpt:22124 to:[fd00:dead:beef:c0:0:242:ac11:3]:22124                                                                                               0     0 DNAT       tcp      !docker0 *       ::/0                 ::/0                 tcp dpt:9443 to:[fd00:dead:beef:c0:0:242:ac11:2]:9443                                                                                                 0     0 DNAT       tcp      !docker0 *       ::/0                 ::/0                 tcp dpt:8000 to:[fd00:dead:beef:c0:0:242:ac11:2]:8000                                                                                                 0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:587 to:[fd4d:6169:6c63:6f77::e]:587                                                                                                        0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:4190 to:[fd4d:6169:6c63:6f77::f]:4190                                                                                                      0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:465 to:[fd4d:6169:6c63:6f77::e]:465                                                                                                        0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:995 to:[fd4d:6169:6c63:6f77::f]:995                                                                                                        1    80 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:25 to:[fd4d:6169:6c63:6f77::e]:25                                                                                                          0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:993 to:[fd4d:6169:6c63:6f77::f]:993                                                                                                        0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:143 to:[fd4d:6169:6c63:6f77::f]:143                                                                                                        0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:110 to:[fd4d:6169:6c63:6f77::f]:110                                                                                                        0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:443 to:[fd4d:6169:6c63:6f77::d]:443                                                                                                        0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:80 to:[fd4d:6169:6c63:6f77::d]:80
```


### DNS check:

```plain text
151.101.65.69                                                                                                                                                                                                                                151.101.1.69                                                                                                                                                                                                                                 151.101.129.69                                                                                                                                                                                                                               151.101.193.69
```

### LINKED ISSUE #4912: rspamd log shows invalid values (date, score and scan time)
invalid dates and values
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
After upgrading to Moocember Update 2022 GUI rspamd logs show invalid values. 
- event dates to 1-1-1970 01:00 
- Score and Scan Time show: [object Object]

Originally reported in https://github.com/mailcow/mailcow-dockerized/issues/4911#issue-1510099907
```

### Logs:

```plain text
NA
```

### Steps to reproduce:

```plain text
Install 2022-12 and look at the logs
```

### Which branch are you using?

master

### Operating System:

Debian 11

### Server/VM specifications:

2GB, 2CPU

### Is Apparmor, SELinux or similar active?

No

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-12

### Reverse proxy:

nginx

### Logs of git diff:

```plain text
NA
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

### PR DESCRIPTION
**Pull request by tomudding**
Timestamps retrieved from the API were always converted to a browser local format. The format specified for moment.js added in 5160eff29446ba94329116a6ed3787400b03e461 did not work because of this.

Additionally, the format specified used `dd` which looks for two letter days, such as "Mo", "Tu", "We", etc. Furthermore, `mm` is used for minutes, not months.

Because the locale formatted datetime can vary a lot, it is not easy to get this into moment.js to enable the sorting of datetimes in the datatables. In other words, there is no conversion from an `Intl.DateTimeFormat` specifier string to moment.js. Adding many `$.fn.dataTable.moment(format);` with different `format`s is not useful.

I have fixed this rewriting how the timestamps from the API are added to the tables. It still uses the locale of the browser, because not everyone wants to use ISO 8601, but no longer requires moment.js (which has been removed).

Two data attributes are added to the `td`s of the timestamps:
- `data-order`
- `data-sort`

The values of these are the timestamps as returned by the server, which are very easily sorted (as they are just UNIX timestamps). Then, when creating the cell in the table, it will be converted to what the locale of the browser specified (this has not changed).

---

Specific to the Rspamd logs, not everything was properly converted when the datatables were introduced. This has been fixed similarly to the fixes for timestamps.

---

This fixes #4911 and fixes #4912.

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by tomudding** [comment]
I have also added fixes for #4912, as the cause of the issues was similar.

Before:
image

After:
image

**Comment by DerLinkman** [comment]
Thank you very much!

@FreddleSpl0it would be nice if you could review it in the near future.

**Comment by FreddleSpl0it** [comment]
Thank you for your fast patch! I have tested it and it's working as expected.

**Review by FreddleSpl0it — APPROVED** [review]

**Comment by tomudding** [comment]
Thank you for verifying it this quickly! Don't forget to link the second issue (#4912) to this PR otherwise someone has to close it manually, editing the description does not update it if you do not have access.

Warmest wishes for a happy holiday season!

**Pull request merged**
