### PR TITLE
data/web: Update syncjob password input to type password

### PR DESCRIPTION
**Pull request by lazyfrosch**
So the password is not readable in clear text.

### CODE REVIEW

**Comment by andryyy** [comment]
Could you please push this to dev? :)

**Comment by lazyfrosch** [comment]
Ooops, okay. Updated

Btw. you should merge master -> dev to avoid merge / rebase problems every time :)

**Comment by andryyy** [comment]
master to dev? the dev stage was master at one point.

**Comment by mkuron** [comment]
@lazyfrosch is right. The current problem is that bug fixes are directly put into master and then independently reimplemented on dev. This produces merge conflicts when changes are proposed against master and the base branch of the PR is then changed to dev.

The correct way to do bugfixes on master (and new features on dev) would be to merge master into dev every time a change is made on master.

**Comment by andryyy** [comment]
I should not commit pushes to master. Problem would be solved.

**Comment by lazyfrosch** [comment]
@andryyy well, there can be good reasons why. Just make sure to merge it to dev afterwards. Then dev is always prepared to be merged to master.

**Comment by andryyy** [comment]
Hm, I once did it. But sometimes I am lazy. I should start doing it and also use better comments for commits!

**Comment by lazyfrosch** [comment]
@andryyy no worries, I'm amazed by the stack so far :wink:

**Pull request merged**
