### PR TITLE
[Rspamd] add domain wide footer

### PR DESCRIPTION
**Pull request by FreddleSpl0it**
This PR adds a new rule to Rspamd. When an authenticated user sends an email, the rule will check if a domain-wide footer has been set for that specific domain. If such a footer exists, the rule will modify the MIME part of the email and add the footer to the very end of the email.

Resolves: https://github.com/mailcow/mailcow-dockerized/issues/1485

### CODE REVIEW

**Comment by MAGICCC** [comment]
I just tested it and it works with the HTML footer, but I couldn't use the PLAIN one somehow. When I enter some text it won't add it to the mail

**Comment by FreddleSpl0it** [comment]
@MAGICCC The email probably has both a text/plain and a text/html section. The mail client will then render the most suitable content type. Can you check the source code of the email? The footer should be there.

Maybe we should add some info. Admins need to provide both text/plain and a text/html footer to ensure that it will be displayed.

**Comment by MAGICCC** [comment]
Oh @FreddleSpl0it, yes it's in the source of the mail. 
Indeed maybe a different wording should be used. Admins needs to know that they should fill both, one with HTML tags and the other without

**Comment by MAGICCC** [comment]
@FreddleSpl0it is there some update on this btw?

**Comment by alwey** [comment]
I tested this recently. This patch does indeed append text and HTML-footers to the mail body, respectively. However, it seems to break the DKIM-signatures. Sadly, therefore I had to roll back the patch.

**Comment by FreddleSpl0it** [comment]
> I tested this recently. This patch does indeed append text and HTML-footers to the mail body, respectively. However, it seems to break the DKIM-signatures. Sadly, therefore I had to roll back the patch.

Can someone confirm this? In my tests DKIM was still working.

**Comment by tilwegener** [comment]
Can you add variables, which will then be added to the Domain Wide Footer? For example %name% for the full name or %email% for the email address?

**Comment by tilwegener** [comment]
@FreddleSpl0it Thanks for the great implementation of the domain wide footer. An improvement would be that you can exclude certain mailboxes from this, just no-reply emails or from one sends Laravel emails, it looks stupid if then also the footer is attached.

**Comment by DerLinkman** [comment]
> @FreddleSpl0it Thanks for the great implementation of the domain wide footer. An improvement would be that you can exclude certain mailboxes from this, just no-reply emails or from one sends Laravel emails, it looks stupid if then also the footer is attached.

Could you please open a enhancement issue for that?

**Comment by bnfone** [comment]
> > I tested this recently. This patch does indeed append text and HTML-footers to the mail body, respectively. However, it seems to break the DKIM-signatures. Sadly, therefore I had to roll back the patch.
> 
> Can someone confirm this? In my tests DKIM was still working.


Hi there,

I recently took the time to test the domain-wide footer feature in Mailcow version 2024-02 and encountered an issue regarding DKIM signatures. Despite various configurations and testing with different email clients such as Apple Mail on Mac, Thunderbird, and Spark, all emails sent to ping@tools.mxtoolbox.com for DKIM verification failed to maintain a valid DKIM signature. What's particularly intriguing is that this issue does not occur when emails are dispatched via SOGo, where the DKIM signature remains unaffected.


Has anyone else observed similar behavior, or could anyone provide further testing or insight into this issue? Any feedback or suggestions would be greatly appreciated .

Thanks in advance for your help.

**Pull request merged**
