### PR TITLE
Add DBhost parameter

### PR DESCRIPTION
**Pull request by titilambert**
Modifications for implementing #189

### CODE REVIEW

**Comment by LeoColman** [comment]
This PR was closed. Does it work, or is it a planned feature?

**Comment by andryyy** [comment]
SQL is not SQL. People will hook their SQL version 5.5 etc. and complain why stuff fails. 

You should be very sure your Sql is compatible. I have not tested various versions.

**Comment by LeoColman** [comment]
Interesting. The main objective is to lower the resources the server is using to the minimum possible, and running MYSQL with everything else is kinda costy. Do you think this would provide an alternative to this problem?

**Comment by andryyy** [comment]
You can change the sql configuration file to fit your resources. SOGo EAS cache is quiet aggressive.

**Pull request closed without merging**
