### PR TITLE
Added possibility to configure autodiscover names

### PR DESCRIPTION
**Pull request by develth**
Added feature to configure the autodiscover DisplayName & DisplayShortName via vars.local.inc.php

### CODE REVIEW

**Comment by develth** [comment]
@DevTek314 @andryyy 
Maybe this is something we could implement like #933 ?

**Review by lavdnone — APPROVED** [review]
useful

**Comment by mkuron** [comment]
I think this should just use the values from #933 and not have its own settings.

**Comment by nnx-support** [comment]
Hi !

I was looking to do the exact same thing. Is there a chance for this PR to get merged? Should I open a new one?

@mkuron I noticed you say it should use the settings set in the WebUI but i think there is value in setting something different than the WebUI title. And also there is `displayName` and `displayShortName` while there is only one in the WebUI.

**Pull request closed without merging**
