### PR TITLE
use random password for mailcow-reset-admin.sh

### LINKED ISSUE #3921: Reset admin script with random password
At the moment, the script to reset the admin password, sets it to default value ( admin:moohoo ).
For security reason should be set to a random value.
Even if it is highly unprobable that someone unauthorized ( or a bot ) could access the admin account before changing the default password, it's still possible.

Best regards

### PR DESCRIPTION
**Pull request by prey87**
Closes #3921

### CODE REVIEW

**Comment by andryyy** [comment]
Taking a quick glance I doubt it will work. Did you test it?

Please also use ${bla} just for integrity. :)

**Comment by prey87** [comment]
Curly braces added.
I have also tested the script ;D

**Comment by andryyy** [comment]
It’s strange it would expand the var in the single quotes.

**Comment by prey87** [comment]
what do you mean exactly?

**Comment by andryyy** [comment]
The `'$password'` stuff. But I'm wrong, it works indeed.

Thanks. :)

**Pull request merged**
