### PR TITLE
armcow64: dockerized 

### LINKED ISSUE #879: ARM64 Support
I have extensive experience with docker on arm, so before I get to work on this, has anyone got mailcow-dockerized ported or running on arm ?

Did a quick search through the repo and I do not see any references to arm. 

Does the repo owner have any issues against arm support being added ?

Thanks

### PR DESCRIPTION
**Pull request by DerLinkman**
## Description:
This PR adds the ARM64 compatibility for our lovely mailcow: dockerized.

ARM64 does not need a manual configuration change in the mailcow Configs, all changes to be ARM64 compatible (not much) are **included into this PR**.

## Phase Status:
1. Port mailcow to ARM64:  
2. Test all components of mailcow on a ARM64 Server: 
3. Publish Images for public tests: 
4. Update Documentation Pages for ARM64: 
5. Merges and final Tests: 

## Latest Events:
+ August 7st 2023: We stumbled across a big issue with decrypting migrated e-mails with the new Alpine based dovecot images. Older E-Mails are not decryptable, new once are. It's not 100% clear why this happens but right know it looks like a non completed implementation of OpenSSL within Dovecot which is causing this strange behaviour as the new OS Versions (Alpine 3.17+ and Debian 12+ are now shipped with OpenSSL 3.X instead of 1.1.1x)
+ August 2nd 2023: Within the latest Dev Build from Rspamd (3.6) the issue with Hyperscan/Vectorscan has finally been solved. Now we can concentrate on optimizing the rest.
+ May 5th 2023: We've published the first ARM64 images (for testing to Docker Hub) which means that you can now test the ARM64 Port of mailcow. Simply clone mailcow as you normally would on a ARM64 Device and switch the branch with `git checkout feat/arm64-cow`. To generate/update your mailcow please use the `--dev` Parameter alongside the desired script to keep the current branch checked out instead of the master/nightly branch.

## Estimated Release:
TBA

### CODE REVIEW

**Comment by BarsMonster** [comment]
Just tried to test it on Oracle cloud instance with fresh installation and got: " docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'" which is probably caused by incorrect urllib3 version inside "mailcowdockerized-dockerapi-mailcow-1". Not sure if it is caused by any ARM64 changes or it's an overall issue.

**Comment by DerLinkman** [comment]
DockerAPI is now running again it was indeed a urllib3 issue.

Can you try it again?

**Comment by BarsMonster** [comment]
> DockerAPI is now running again it was indeed a urllib3 issue.
> 
> Can you try it again?

Yep, can confirm that 'chunked' issue is fixed.
Update: It looks like everything works smoothly. Thanks for making it possible on ARM64!

**Comment by BarsMonster** [comment]
It seem almost all functionality is working, except rspamd HyperScan library.
I am getting "bad hs database in /var/lib/rspamd/"[....] on each restart, even if I delete *.hs cache files - they are recreated and still invalid. Probably caused by architecture mismatch.

**Comment by rflrkn** [comment]
Just making sure: Can I update Mailcow on ARM64 using the normal `update.sh`-Script (with the `--dev` Parameter, obviously)?

**Comment by BarsMonster** [comment]
> Just making sure: Can I update Mailcow on ARM64 using the normal `update.sh`-Script (with the `--dev` Parameter, obviously)?

worked for me

**Comment by DerLinkman** [comment]
> It seem almost all functionality is working, except rspamd HyperScan library.
> 
> I am getting "bad hs database in /var/lib/rspamd/"[....] on each restart, even if I delete *.hs cache files - they are recreated and still invalid. Probably caused by architecture mismatch. 

Jup also saw that during my testing phases. Don't know how to proceed with that. Yes we could deactivate the hyperscan functionality on ARM64 devices but that seems more like a workaround to me.

**Comment by BarsMonster** [comment]
> > It seem almost all functionality is working, except rspamd HyperScan library.
> > I am getting "bad hs database in /var/lib/rspamd/"[....] on each restart, even if I delete *.hs cache files - they are recreated and still invalid. Probably caused by architecture mismatch.
> 
> Jup also saw that during my testing phases. Don't know how to proceed with that. Yes we could deactivate the hyperscan functionality on ARM64 devices but that seems more like a workaround to me.

My understanding is that HyperScan is Intel's contribution, so supporting it on ARM64 is on us. I tried to contact rspamd developers with no luck. In my view disabling it is a valid short-term solution, as there is slower PCRE fallback. I was not able to disable it in a way that suppresses the error, "disable_hyperscan" option does not cut it.  

I.e. currently I see this error in logs, but fallback works. I.e. seems no functionality is lost (just performance impact + errors in log). 

**Update:** Apparently it must be disabled at compile time with  -DENABLE_HYPERSCAN=OFF

**Comment by BarsMonster** [comment]
> Yes we could deactivate the hyperscan functionality on ARM64 devices but that seems more like a workaround to me.

Apparently it is (theoretically) possible to use ARM64-aware fork of hyperscan: https://github.com/VectorCamp/vectorscan

Without replacing the library - HyperScan must be disabled with PCRE fallback to scare less people with unfixable error message. In HyperScan official repo Intel officially declined to support or merge in ARM64 support (which is not surprising).

**Comment by jfreax** [comment]
Tried it on Hetzner and it works great! Thanks for that.

There were only a small hiccup with the restore helper script. It tries to fetch mailcow/backup:latest which is only available for x86 at the moment. But tag 1.2 is indeed available as arm64. Changing the version on top of `./helper-scripts/backup_and_restore.sh` did the trick. Restoring went fine afterwards.

**Comment by DerLinkman** [comment]
> isable it in a way that suppresses the error, "disable_hyperscan" option does not cut it.
> 
> I.e. currently I see this error in logs, but fallback works. I.e. seems no functionality is lost (just performance impact + errors in log).
> 
> **Update:** Apparently it must be disabled at compile time with -DENABLE_HYPERSCAN=OFF

Or we keep this error and state it as won't fix. I don't want to disable this feature for x86 too (our bigger userbase).

Theoretically we could compile it for ourself but i don't see the necessarity here...

**Comment by BarsMonster** [comment]
@DerLinkman Unfortunately, it has more impact than just error message. These HyperScan files are continuously re-generated, which takes CPU time and disk space. 

The only solution is -DENABLE_HYPERSCAN=OFF added conditionally, only for ARM64 (or for all platforms which are not x86 / x86_64). This would also enable it later to work on RiskV servers, which will come few years down the line.

**Comment by DerLinkman** [comment]
Is Vectorscan compatible with x86 or is that only compatible for ARM(64)?

**Comment by BarsMonster** [comment]
@DerLinkman 
Vectorscan claim to fame is portability, so it is definitely not just ARM64. 

But x86_32 is not supported:  "32-bit x86 is not supported by Vectorscan, we do not test or include it in the CI builds, please use Hyperscan instead if you need 32-bit x86."

x86_64 Seems to be supported, few bugs were found and fixed.

**Comment by DerLinkman** [comment]
> It seem almost all functionality is working, except rspamd HyperScan library. I am getting "bad hs database in /var/lib/rspamd/"[....] on each restart, even if I delete *.hs cache files - they are recreated and still invalid. Probably caused by architecture mismatch.

Let's see what it brings:

https://github.com/rspamd/rspamd/issues/4493

**Comment by Vcele** [comment]
Should one currently use the arm64-Version? Are there expected security problems, or severe functionality problems?

**Comment by BarsMonster** [comment]
> Should one currently use the arm64-Version? Are there expected security problems, or severe functionality problems?

I am using it at the moment. No issues found that affect functionality. rspamd performance can be reduced, but for <1'000'000 emails per day it should be ok.

**Comment by kwojcik-blockether** [comment]
Getting an error for SSL certificate. Is it connected with ARM64 or the user error on my side?

```
blockether-mail-acme-mailcow-1  | Traceback (most recent call last):
blockether-mail-acme-mailcow-1  |   File "/usr/bin/acme-tiny", line 8, in <module>
blockether-mail-acme-mailcow-1  |     sys.exit(main())
blockether-mail-acme-mailcow-1  |   File "/usr/lib/python3.10/site-packages/acme_tiny.py", line 195, in main
blockether-mail-acme-mailcow-1  |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
blockether-mail-acme-mailcow-1  |   File "/usr/lib/python3.10/site-packages/acme_tiny.py", line 90, in get_crt
blockether-mail-acme-mailcow-1  |     out = _cmd(["openssl", "req", "-in", csr, "-noout", "-text"], err_msg="Error loading {0}".format(csr))
blockether-mail-acme-mailcow-1  |   File "/usr/lib/python3.10/site-packages/acme_tiny.py", line 28, in _cmd
blockether-mail-acme-mailcow-1  |     raise IOError("{0}\n{1}".format(err_msg, err))
blockether-mail-acme-mailcow-1  | OSError: Error loading /var/lib/acme/mail.blockether.io/acme.csr
blockether-mail-acme-mailcow-1  | b'Unable to load X509 request\n5810779DFFFF0000:error:0480006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:763:Expecting: CERTIFICATE REQUEST\n'
```

**Comment by deanpcmad** [comment]
Have just tried the branch on a clean Ubuntu 22.04 ARM server on Hetner Cloud and I'm having issues. It keeps getting stuck when trying to connect to the database, but the database is online:

```
mailcowdockerized-watchdog-mailcow-1   | Waiting for SQL...
mailcowdockerized-postfix-mailcow-1    | Waiting for database to come up...
mailcowdockerized-php-fpm-mailcow-1    | Waiting for SQL...
mailcowdockerized-sogo-mailcow-1       | Waiting for database to come up...
mailcowdockerized-dovecot-mailcow-1    | Waiting for database to come up...
mailcowdockerized-watchdog-mailcow-1   | Waiting for SQL...
mailcowdockerized-rspamd-mailcow-1     | Waiting for PHP on port 9001...
mailcowdockerized-postfix-mailcow-1    | Waiting for database to come up...
mailcowdockerized-php-fpm-mailcow-1    | Waiting for SQL...
mailcowdockerized-sogo-mailcow-1       | Waiting for database to come up...
mailcowdockerized-dovecot-mailcow-1    | Waiting for database to come up...
mailcowdockerized-watchdog-mailcow-1   | Waiting for SQL...
mailcowdockerized-postfix-mailcow-1    | Waiting for database to come up...
mailcowdockerized-php-fpm-mailcow-1    | Waiting for SQL...
mailcowdockerized-sogo-mailcow-1       | Waiting for database to come up...
mailcowdockerized-dovecot-mailcow-1    | Waiting for database to come up...
mailcowdockerized-rspamd-mailcow-1     | Waiting for PHP on port 9001...
mailcowdockerized-watchdog-mailcow-1   | Waiting for SQL...
```

Any ideas?

**Comment by BarsMonster** [comment]
> Any ideas?

I am pretty sure it is not related to ARM64. I would investigate using regular mailcow troubleshooting. i.e. inspect SQL logs in more details, and try to connect manually from SQL docker / from postfix docker.

**Comment by deanpcmad** [comment]
You're right, I ended up completely removing all volumes and re-starting. All seems well!
Will this be in the next version?

**Comment by BarsMonster** [comment]
@DerLinkman I see that there was a commit in rspamd on 25th of May to try to fix hyperscan, docker image mailcow/rspamd though is still from 12th. I assume the straightforward way to test it is to update docker image to current version and test? 

Also, hope to see this pushed to mainline for mailcow. Even if we have to disable hyperscan when building rspamd as a temporary measure. My server is working flawlessly in the last 2 months, with no updates though :-)

**Comment by DerLinkman** [comment]
> I see that there was a commit in rspamd on 25th of May to try to fix hyperscan, docker image mailcow/rspamd though is still from 12th. I assume the straightforward way to test it is to update docker image to current version and test?

Just tested the most current Rspamd Repo Package (from July 4th) and the issue still persists im afraid.

Sorry but this will delay the ARM64 thing as i don't want to disable Hyperscan for Rspamd as it unessecarily complicates the building process for now.

**Comment by Vcele** [comment]
For some reason when I try to run the update.sh (with --dev) it fails to pull phpfpm.

```
Error response from daemon: manifest for mailcow/phpfpm:1.85 not found: manifest unknown: manifest unknown

Error pulling mailcow/phpfpm:1.85, retrying...
Error response from daemon: manifest for mailcow/phpfpm:1.85 not found: manifest unknown: manifest unknown

Error pulling mailcow/phpfpm:1.85, retrying...
Error response from daemon: manifest for mailcow/phpfpm:1.85 not found: manifest unknown: manifest unknown

Error pulling mailcow/phpfpm:1.85, retrying...
Error response from daemon: manifest for mailcow/phpfpm:1.85 not found: manifest unknown: manifest unknown

Error pulling mailcow/phpfpm:1.85, retrying...

Too many failed retries, exiting
```

Is it possible that the version if this docker container (1.85) hasn't been released yet?

**Comment by maxkratz** [comment]
> Is it possible that the version if this docker container (1.85) hasn't been released yet?

Seems like you are correct: https://hub.docker.com/r/mailcow/phpfpm/tags

**Comment by DerLinkman** [comment]
You guys can now try it inside the nightly build.

How exactly and more informations can be found here:
https://mailcow.email/posts/2023/arm64-open-beta/

**Comment by Vcele** [comment]
> You guys can now try it inside the nightly build.
> 
> How exactly and more informations can be found here:
> https://mailcow.email/posts/2023/arm64-open-beta/

How can you switch over from the current branch?

**Comment by RogerSik** [comment]
@Vcele https://docs.mailcow.email/i_u_m/i_u_m_update/ 

```
# - Switch your mailcow updates to the unstable (nightly) branch.
FOR TESTING PURPOSES ONLY!!!! NOT READY FOR PRODUCTION!!!
./update.sh --nightly
```

**Comment by Vcele** [comment]
Thanks just found out myself 👍

**Comment by RogerSik** [comment]
was you able to update successfully? @Vcele 

Update is working but all my older emails are now not more readable. 



Dovecot logs says
```
failed: Decryption error: no private key available (read reason=prefetch) in=232 out=2380 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=0 body_count=0 body_bytes=0
```

Even an restore with the backup_and_restore.sh script didn't resolved this issue.

**Comment by Vcele** [comment]
> was you able to update successfully? @Vcele
> 
> Update is working but all my older emails are now not more readable.
> 
> 
> 
> Dovecot logs says
> 
> ```
> failed: Decryption error: no private key available (read reason=prefetch) in=232 out=2380 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=0 body_count=0 body_bytes=0
> ```
> 
> Even an restore with the backup_and_restore.sh script didn't resolved this issue.

It's the same for me, but I found a work around 😉

1. Log in via Thunderbird and make sure you can access your emails like that
2. Move all emails to a local folder or a different mailbox
3. Make sure they disappear in SOGo
4. Move all emails back to your Mailcow mailbox

**Comment by DerLinkman** [comment]
> was you able to update successfully? @Vcele 
> 
> 
> 
> Update is working but all my older emails are now not more readable. 
> 
> 
> 
> 
> 
> 
> 
> Dovecot logs says
> 
> ```
> 
> failed: Decryption error: no private key available (read reason=prefetch) in=232 out=2380 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=0 body_count=0 body_bytes=0
> 
> ```
> 
> 
> 
> Even an restore with the backup_and_restore.sh script didn't resolved this issue. 
> 
> 

That should not happen in general I'll take a look at it on Monday why this is happening. My guess is the switch from Debian to Alpine.

**Comment by DerLinkman** [comment]
Ok i spend the whole day on researching and debugging why dovecot cannot load the private/public keys and apparently it looks like the reason for this is openssl 3.X our previously installation on Debian 11 is openssl 1.1.1u. With Deb 12 and Alpine 3.17+ openssl 3.X is shipped with. However though it seems that dovecot cannot proceed with keys generated within < 3.X? I'm not nearly enough an expert to confirm this so if someone of you is please go ahead.

However this one is a huge even more bigger impact for not only ARM64 no mailcow itself as we have to think about an idea to migrate mails to newer keys generated with openssl 3.X instead of 1.X (if this is really the problem here). Right now it looks like it.

**Comment by DerLinkman** [comment]
Latest Events Updated:

+ August 7st 2023: We stumbled across a big issue with decrypting migrated e-mails with the new Alpine based dovecot images. Older E-Mails are not decryptable, new once are. It's not 100% clear why this happens but right know it looks like a non completed implementation of OpenSSL within Dovecot which is causing this strange behaviour as the new OS Versions (Alpine 3.17+ and Debian 12+ are now shipped with OpenSSL 3.X instead of 1.1.1x)

**Comment by maxkratz** [comment]
@DerLinkman If I understand you correctly, this also affects "normal" AMD64-based instances, correct?

Is the behavior of the non-decryptable emails based on the host OS (e.g., Debian 12) or is this only because of the used OSes inside the mailcow containers? In other words: should an existing mailcow stack on a Debian 11 host *not* be upgraded to Debian 12 at the moment?

**Comment by DerLinkman** [comment]
> @DerLinkman If I understand you correctly, this also affects "normal" AMD64-based instances, correct?
> 
> 
> 
> Is the behavior of the non-decryptable emails based on the host OS (e.g., Debian 12) or is this only because of the used OSes inside the mailcow containers? In other words: should an existing mailcow stack on a Debian 11 host *not* be upgraded to Debian 12 at the moment?

Yes it affects AMD64 but only image wise. mailcow is fully usable on Debian 12. The issue is only inside the nightly images.

**Comment by maxkratz** [comment]
> Yes it affects AMD64 but only image wise. mailcow is fully usable on Debian 12. The issue is only inside the nightly images.

Thank you for the clarification. I guess the images based on the new(er) OSes will not be released as stable until this bug is fixed, correct?

**Comment by DerLinkman** [comment]
> > Yes it affects AMD64 but only image wise. mailcow is fully usable on Debian 12. The issue is only inside the nightly images.
> 
> Thank you for the clarification. I guess the images based on the new(er) OSes will not be released as stable until this bug is fixed, correct?

Yes, definitely not! ARM64 however will also not be released until this issue has been solved unfortunately.

**Comment by danieldietzler** [comment]
Are there any updates on this? I am assuming most of the mailcow development is currently kinda on hold/aimed towards solving this, since this is a major issue and must be solved going forward?

**Comment by lincft** [comment]
I had the same issue with the non-decryptable emails.

I tried this successfully:

1. Decrypt the emails with the script from the documentation
2. Update
3. Encypt the emails with the script. But i had to remove "-regextype egrep"

**Comment by Volkor3-16** [comment]
> But i had to remove "-regextype egrep"

That worked for me, but now I'm getting another error from what I assume is dovecot not supporting lz4.
`Fatal: fs_init() failed: compress: Compression method 'lz4' not supported.` is spammed in console.

I am on ARM (Oracle Cloud), so it might be something with the image?

**Comment by DerLinkman** [comment]
> > But i had to remove "-regextype egrep"
> 
> That worked for me, but now I'm getting another error from what I assume is dovecot not supporting lz4. `Fatal: fs_init() failed: compress: Compression method 'lz4' not supported.` is spammed in console.
> 
> I am on ARM (Oracle Cloud), so it might be something with the image?

Hi, yep that lz4 error you're getting is indeed from dovecot. As Alpine currently does not support lz4 as a decryption method (and i don't know why, their reason was: "we do not recommend, bye" (??!!!)) this error happens. I already reopend the ticket regarding "not recommended" but didn't got a answer yet.

There is currently no fix for this.

**Comment by KeldorDE** [comment]
I found the following issue, the support for zstd compression in dovecot 2.3.20-r7 under Alpine 3.17 was added in April. It seems that you can enable/change the compression with the ENV variable `COMPRESSION=zstd`

https://github.com/Mailu/Mailu/issues/2139

Would this be an option to switch to zstd? I can't estimate the effort and the steps needed for an update.

**Comment by DerLinkman** [comment]
> I found the following issue, the support for zstd compression in dovecot 2.3.20-r7 under Alpine 3.17 was added in April. It seems that you can enable/change the compression with the ENV variable `COMPRESSION=zstd`
> 
> [Mailu/Mailu#2139](https://github.com/Mailu/Mailu/issues/2139)
> 
> Would this be an option to switch to zstd? I can't estimate the effort and the steps needed for an update.

Unfortunately no as it seems. I thought that too (actually was i the man who contacted alpine in the firstplace to ask for at least zstd support). That is what the current nightly/arm64 builds support but it can not decompress mails which has been compressed with lz4 that's what the issue saying. Because the setting zstd inside the dovecot conf is only for new mails. If it detects old mails it will use that decryption method to decrypt them. if that decryption method is not available then you're lost so to say.

**Comment by DerLinkman** [comment]
Yes lz4 will also be present in Alpine 3.18.4(?) i guess then:
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/50663

**Comment by lincft** [comment]
> > But i had to remove "-regextype egrep"
> 
> That worked for me, but now I'm getting another error from what I assume is dovecot not supporting lz4. `Fatal: fs_init() failed: compress: Compression method 'lz4' not supported.` is spammed in console.
> 
> I am on ARM (Oracle Cloud), so it might be something with the image?

With the arm64-dev image worked it fine. I testet it with an old backup again

This i used for decryption:

find /var/vmail/ -type f -regextype egrep -regex '.*S=.*W=.*' | while read -r file; do
if [[ $(head -c7 "$file") == "CRYPTED" ]]; then
doveadm fs get compress lz4:1:crypt:private_key_path=/mail_crypt/ecprivkey.pem:public_key_path=/mail_crypt/ecpubkey.pem:posix:prefix=/ \
  "$file" > "/tmp/$(basename "$file")"
  if [[ -s "/tmp/$(basename "$file")" ]]; then
    chmod 600 "/tmp/$(basename "$file")"
    chown 5000:5000 "/tmp/$(basename "$file")"
    mv "/tmp/$(basename "$file")" "$file"
  else
    rm "/tmp/$(basename "$file")"
  fi
fi
done


And this after updating to the latest version to encrypt the mails:

find /var/vmail/ -type f -regex '.*S=.*W=.*' | while read -r file; do
if [[ $(head -c7 "$file") != "CRYPTED" ]]; then
doveadm fs put crypt private_key_path=/mail_crypt/ecprivkey.pem:public_key_path=/mail_crypt/ecpubkey.pem:posix:prefix=/ \
  "$file" "$file"
  chmod 600 "$file"
  chown 5000:5000 "$file"
fi
done

**Comment by BarsMonster** [comment]
Updated to latest nightly ARM64. Everything works. rspam error "bad hs database" is gone. 
Now I am getting "regexp map is empty" which is probably still relevant to vectorscan/hyperscan, but everything works.

If anyone still uses original ARM64 build, I suggest to check cache files (*.hs*) at /var/lib/rspamd/ inside rspamd-mailcow container. 
I had 5.5G of broken cache files which is hopefully fixed now.

**Comment by zoro16** [comment]
Hello, 

Everything worked from the first try so thanks a lot!

At this moment in time there are no `arm64` image for `mailcow/sogo:1.19` yet so docker just pulls the latest tag/image which is not the correct arch (`amd64`) and that caused the SoGo service to keep restarting.

Making the following changes did it for me. Note that no changes were needed for the other services.

```yaml
...
    sogo-mailcow:
      image: mailcow/sogo:nightly-1.119
      platform: linux/arm64
...
```

**Comment by DerLinkman** [comment]
Just a update for the current situation:

https://mailcow.email/posts/2023/arm64-delay/

**Comment by zoro16** [comment]
@DerLinkman Please correct me if I am wrong, 

I still can install Mailcow on ARM64 with no issues given that I don't have old emails that were migrated from a system that uses OpenSSL 1.1.1X ?

In another word, fresh installation of Mailcow ARM64 on Debian 12 (OpenSSL 3.X) has no issues ?

**Comment by BarsMonster** [comment]
@zoro16 I am using fresh installation of ARM64 build in (personal) production with no issues. So this should be true. I will stay on ARM64.

**Comment by zoro16** [comment]
@BarsMonster I am using now too with no issues. So its not so bad after all :smile:

**Comment by DerLinkman** [comment]
> @DerLinkman Please correct me if I am wrong,
> 
> I still can install Mailcow on ARM64 with no issues given that I don't have old emails that were migrated from a system that uses OpenSSL 1.1.1X ?
> 
> In another word, fresh installation of Mailcow ARM64 on Debian 12 (OpenSSL 3.X) has no issues ?

Yes as far as we know a fresh mailcow ARM64 installation has no issues. It's only for migration things to ARM64 and from ARM64 were this issue exists.

**Comment by jsbrain** [comment]
@lincft and everyone else stumbling across this:

> 3. Encypt the emails with the script. But i had to remove "-regextype egrep"

The reason for this is actually that I think the busybox image used in the new arm images has some missing deps for `find`, so running `apk -U add findutils` before fixes that and you can use the full command as stated in the docs.

**Comment by Vcele** [comment]
I just moved a bunch of mails to the archive folder and after they had been moved I got the encryption error again.

`imap(victor@vlanius.de)<292977><elX/u1wKjeAucm/2>: Error: Mailbox Archive: UID=43: read() failed: read(/var/vmail/vlanius.de/victor/Maildir/.Archive/cur/1700242112.M286839P291915.134e14b0a238,S=26520,W=26988:2,S) failed: Decryption error: no private key available (read reason=prefetch)`

**Comment by Vcele** [comment]
I just moved a bunch of mails to the archive folder and after they had been moved I got the encryption error again.
`
imap(victor@vlanius.de)<292977><elX/u1wKjeAucm/2>: Error: Mailbox Archive: UID=43: read() failed: read(/var/vmail/[domain]/victor/Maildir/.Archive/cur/1700242112.M286839P291915.134e14b0a238,S=26520,W=26988:2,S) failed: Decryption error: no private key available (read reason=prefetch)`

**Comment by Vcele** [comment]
> I just moved a bunch of mails to the archive folder and after they had been moved I got the encryption error again. ` imap(victor@vlanius.de)<292977><elX/u1wKjeAucm/2>: Error: Mailbox Archive: UID=43: read() failed: read(/var/vmail/[domain]/victor/Maildir/.Archive/cur/1700242112.M286839P291915.134e14b0a238,S=26520,W=26988:2,S) failed: Decryption error: no private key available (read reason=prefetch)`

I've made a backup and then used `doveadm expunge` to delete all emails. After this I could not reproduce this again. Although it's not my main E-Mail is there anyway to decrypt the emails from the backup again?

**Comment by timscha** [comment]
I can confirm the issue when moving mails into a different folder with the latest nightly. Any way to fix this?

**Comment by DerLinkman** [comment]
I cannot reproduce that... freshly migrated from x86 to ARM64 latest nightly

**Comment by DerLinkman** [comment]
New PR: https://github.com/mailcow/mailcow-dockerized/pull/5587 (final one to be merged)

**Pull request closed without merging**
