### PR TITLE
[Postfix] Default SMTP server security grade for EECDH key exchange

### PR DESCRIPTION
**Pull request by elcore**
Currently mailcow can´t negotiate a successful TLS Handshake with a P-384 certificate (sec384r1)

This PR modifies the Postfix configuration to "use the most preferred curve that is supported by both the client and the server", thus enabling a successful TLS Handshake.

http://www.postfix.org/postconf.5.html#smtpd_tls_eecdh_grade
http://www.postfix.org/FORWARD_SECRECY_README.html

### CODE REVIEW

**Comment by elcore** [comment]
This might be related to #1491, I experienced the same issue.

**Comment by andryyy** [comment]
And untested.

**Comment by elcore** [comment]
> And untested.

Well, it fixed the issue for me.

**Comment by andryyy** [comment]
How? It is available in Postfix 3.2. Check your logs. It should report that error.

**Comment by elcore** [comment]
> How? It is available in Postfix 3.2. Check your logs. It should report that error.

@andryyy I have checked the logs and yes, it reports this error, yet my mailcow instance is working now.

**Comment by elcore** [comment]
This config works too `smtpd_tls_eecdh_grade = ultra` (no errors in the logs)

**Comment by elcore** [comment]
I have a proposal, we should update the TLS documentation until mailcow is using Postfix ≥ 3.2.

"You must replace `smtpd_tls_eecdh_grade = strong` with `smtpd_tls_eecdh_grade = ultra` in `data/conf/postfix/main.cf` if you are using a P-384 certificate."

**Comment by elcore** [comment]
> I have a proposal, we should update the TLS documentation until mailcow is using Postfix ≥ 3.2.
>
>"You must replace smtpd_tls_eecdh_grade = strong with smtpd_tls_eecdh_grade = ultra in data/conf/postfix/main.cf if you are using a P-384 certificate."

@andryyy What do you think?

**Comment by andryyy** [comment]
I will push a new image very soon. :-)

**Pull request merged**
