### PR TITLE
Revert "php: Rebase on Debian 12"

### PR DESCRIPTION
**Pull request by DerLinkman**
Reverts mailcow/mailcow-dockerized#5951

### CODE REVIEW

**Comment by MaxXor** [comment]
?

**Comment by gerwim** [comment]
Is this PR even correct? https://github.com/mailcow/mailcow-dockerized/pull/5951/files changed it to version 1.89 of the container from 1.88. Now we're back on 1.87.

**Comment by MaxXor** [comment]
I'm a bit confused about the purpose of the staging branch? isn't the branch supposed to catch such mistakes?

**Comment by fm** [comment]
> Is this PR even correct? https://github.com/mailcow/mailcow-dockerized/pull/5951/files changed it to version 1.89 of the container from 1.88. Now we're back on 1.87.

Yes, see [here](https://mailcow.social/@doncow/112773948265377657) for explanation

**Pull request merged**
