### PR TITLE
Integrating DMARC reports

### PR DESCRIPTION
**Pull request by Clete2**
Integrates DMARC reports as per #1341.

Please provide feedback -- it is my first time contributing here!

You should:
- Create a postmaster mailbox
- Set up DMARC reports to go there
- Configure DMARC as shown in the config file, giving it the IMAP credentials
- Go to admin console and find the new link in the dropdown

### CODE REVIEW

**Comment by ntimo** [comment]
This is awesome 😍 I really hope that @andryyy will approve your merge request this would be such a awesome feature.

**Comment by ntimo** [comment]
Could it be that the dmarcts-report-viewer.php is missing? :)

**Comment by Clete2** [comment]
Probably. I’ll sign on my laptop later and make sure I commit it.

**Comment by mkuron** [comment]
This looks interesting, thanks for posting. Before we merge this, we should try to get a smoother and tighter integration though. The user should not need to manually create an IMAP inbox, that needs to somehow happen automatically. One shouldn’t use the postmaster mailbox as that is intended for a human admin; instead something like dmarc-reports@$MAILCOW_HOSTNAME should be the default.

Also, the DNS diagnostics page should show how to put the reporting address into DNS.

Futhermore, do we really need a separate container? There are PHP solutions available too (linked in #1341) that could run directly from the web interface.

**Comment by andryyy** [comment]
Thanks, but I think a new container is too much for those reports. I’m not a supporter of this integration anyway, so it should really be as easy and smooth as possible.

**Comment by Knight1** [comment]
If the PHP solutions are great I would prefer them. Also it is not really necessary because there are so many solutions out there. Also the setup should be automated inside the Admin page and we need a configurator for the DMARC system.

**Comment by Clete2** [comment]
I’m personally not very fond of the solution I found because it involves storing credentials in the script. I’d rather make a custom solution but I thought that integrating existing scripts would be an easier route to at least get some kind of reporting done.

I’m ok with putting it in another container but have no idea which one to use as a cron job or event loop. Hence I made another container for it.

I didn’t see any PHP solutions linked in the issue. I just saw 3rd party cloud based ones and the Perl one I pulled in. Totally understand trying to keep with 1 language.

**Comment by Clete2** [comment]
Also I’m not a php dev. While I can hack it together I’m not sure I’d be able to do it quickly.

**Comment by Clete2** [comment]
Hey all,
I did some research. I recommend [parsedmarc](https://domainaware.github.io/parsedmarc/) as a self-hosted solution.

I run Splunk on my internal network at home. Parsedmarc is a Python utility that parses DMARC reports from an inbox and will ingest them into either Elasticache (for Graylog or Kibana) or Splunk.

For anyone reading this wanting to use it with Splunk, here's the command I use!

`parsedmarc -u <DMARCEmail> -p <MyPassword> -H <MyMailServer> --save-aggregate --save-forensic --hec https://<MySplunk>:8088 --hec-token <MyToken> --hec-index Default --hec-skip-certificate-verification --test`

**Pull request closed without merging**
