### PR TITLE
Add `--dry` IMAPsync Parameter as Button to select for SyncJobs

### PR DESCRIPTION
**Pull request by raph-topo**
Without this, setting Edit sync job > Custom parameters > `--dry` fails with:
image
(Even though `--dry` is a placeholder suggestion)

### CODE REVIEW

**Comment by MAGICCC** [comment]
I guess we can also allow `--releasecheck` @DerLinkman

**Comment by raph-topo** [comment]
I also added the very useful `--f1f2` in my instance, what do you think about that?

**Comment by DerLinkman** [comment]
> I guess we can also allow `--releasecheck` @DerLinkman

Nah that is not necessarily i think.

**Comment by DerLinkman** [comment]
`--dry` is not a problem. That dry option might make more sense as a clickable selection button in my eyes though.

**Comment by DerLinkman** [comment]
Tested it and it works but don't trust my php skills here. @FreddleSpl0it can you take a look at this whole thing?

**Comment by DerLinkman** [comment]
Looks like this now:

image

(Enabled for the Screenshot, disabled per default)

**Comment by DerLinkman** [comment]
Btw, don't see a problem why `--f1f2` should not be allowed.

**Comment by raph-topo** [comment]
Thank you for having accepted and improved this!

**Pull request merged**
