### PR TITLE
Update Dockerfiles to Alpine 3.19

### PR DESCRIPTION
**Pull request by MAGICCC**
Updates all relevant Dockerfiles to Alpine 3.19
For images with python I added `PIP_BREAK_SYSTEM_PACKAGES` variable to 'fix' https://peps.python.org/pep-0668/

### CODE REVIEW

**Comment by MAGICCC** [comment]
Superseeds https://github.com/mailcow/mailcow-dockerized/pull/5525

**Comment by MAGICCC** [comment]
Works fine on my server

**Comment by DerLinkman** [comment]
Not merging this for now.

Currently adding the missing pip packages to the Alpine Repo themselves to not use the PIP_BREAK_SYSTEM_PACKAGES method as i don't like this :/

**Comment by DerLinkman** [comment]
Will modify your commit though when these packages are included into Alpine.

**Comment by DerLinkman** [comment]
However we'll use the PIP_BREAK_SYSTEM_PACKAGES flag for olefy as it is using the olefy tools which they install manually via pip.

**Comment by MAGICCC** [comment]
Sounds good!

**Comment by DerLinkman** [comment]
Will merge this after all as we can swap out the native alpine packages in the long run.

**Review by DerLinkman — APPROVED** [review]
Looks fine now!

**Pull request merged**
