### PR TITLE
[BS5] Migrating Web UI to Bootstrap 5

### PR DESCRIPTION
**Pull request by FreddleSpl0it**
This is a draft PR to show the process of the migration to Bootstrap v5.
Here is a list with most of the steps [#4528](https://github.com/mailcow/mailcow-dockerized/issues/4528)
Maybe we should create a new feature branch for this.

### CODE REVIEW

**Comment by feldsam** [comment]
Hi, I just created new branch `bootstrap5`, so we can merge to this branch partial features and when all will be done, them we merge to staging.

**Comment by feldsam** [comment]
I think this plan/process should be a Issue and use PRs only for merging

**Comment by FreddleSpl0it** [comment]
> I think this plan/process should be a Issue and use PRs only for merging

I've moved the list to [#4528](https://github.com/mailcow/mailcow-dockerized/issues/4528)

**Comment by FreddleSpl0it** [comment]
I'm having a hard time finding a proper replacement for FooTable, as it's no longer maintained and doesn't support Bootstrap 5. My suggestion was to use [GridJS](https://gridjs.io/), but it doesn't support child rows (collapsing rows with details) and therefore not as responsive as Footable.

The only idea I have is to use a button that opens a modal with the item details that are not displayed in the table.

or maybe this jquery plugin [https://datatables.net/](https://datatables.net/)
any other ideas?

**Comment by andryyy** [comment]
I think switching to DataTables is a good idea. Seriously, DT is rock solid and well written and jQuery is just a fucking help in so many ways.

I like allans comment on this in https://datatables.net/forums/discussion/67258/will-datatables-2-0-require-jquery

**Comment by feldsam** [comment]
Hi all, I like progress on this PR. I want to implement Datatables with AJAX pagination support. It speedup loading times on servers with plenty domains and mailboxes. I have to find time for this, but it should be easy https://datatables.net/manual/server-side

**Comment by DerLinkman** [comment]
Hyped for it to see it guys! Nice work so far!

**Comment by FreddleSpl0it** [comment]
> Hi all, I like progress on this PR. I want to implement Datatables with AJAX pagination support. It speedup loading times on servers with plenty domains and mailboxes. I have to find time for this, but it should be easy https://datatables.net/manual/server-side

I'd say I'll replace all the FooTables for now and then we can merge the PR into the feature branch for further development.

**Comment by FreddleSpl0it** [comment]
Most of it should be done. We could now push the whole thing into the bootstrap5 branch and polish/test it

**Pull request merged**
