### PR TITLE
[Postfix] Fix DMARC aligment for bounces

### PR DESCRIPTION
**Pull request by dragoangel**

### CODE REVIEW

**Comment by dragoangel** [comment]
Let's assume `MAILCOW_HOSTNAME=mail.example.com`, then this settings will change email of bounce from `MAILER-DAEMON@mail.example.com` to `MAILER-DAEMON@example.com` and in this case ARC signing will aling checks and DMARC will not fail.

I run mailcow with this setting more then a year and have strict DMARC without issues.
@navossoc asked for help and this change fixed his situation when gmail reject bounces due to strick not aligned DMARC.
@DerLinkman I sure it safe to apply, but can you please double check in your setup?

**Comment by DerLinkman** [comment]
> Let's assume `MAILCOW_HOSTNAME=mail.example.com`, then this settings will change email of bounce from `MAILER-DAEMON@mail.example.com` to `MAILER-DAEMON@example.com` and in this case ARC signing will aling checks and DMARC will not fail.
> 
> I run mailcow with this setting more then a year and have strict DMARC without issues. @navossoc asked for help and this change fixed his situation when gmail reject bounces due to strick not aligned DMARC. @DerLinkman I sure it safe to apply, but can you please double check in your setup?

Is there a way how i can test this?

**Comment by dragoangel** [comment]
Send email to user which over quotas in imap for example and check what bounce dmarc status will be without this PR and with it :)
Note: better send from gmail

**Comment by DerLinkman** [comment]
Tested:

Before: 
image

After:
image

**Comment by andryyy** [comment]
This will change the sender origin to a domain that might be a mailcow domain. I don't really want this. The origin should imo remain the mail host as it is mailer daemon sending the mail. The service accounts belong to the mailcow hostnames fqdn.

This does "fix" dmarc alignment with a strange workaround and might not be wanted.

**Comment by andryyy** [comment]
Furthermore there are hints to setup dmarc in the config which this PR would not remove or edit.

**Comment by andryyy** [comment]
Furthermore there are hints to setup dmarc in the config which this PR would not remove or edit.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
