### PR TITLE
Update Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by yhdsl**
I have made a complete update of the Chinese Translation, in summary, i have completed the translation and proofreading of all the translation, the complete fix text will be attached later.

I've read the translation guide on this [site](https://community.mailcow.email/d/659-common-translation-platformknow-how-to), as well as read this #4657 notes on Chinese Translation, and verified it inside a self-deployed Docker container.

The complete revision includes:
+ Ensure that all entries are covered (previously untranslated entries and translations that have become obsolete due to text changes)
+ Unified translation style (I made some adjustments for Chinese pages and reading habits)
+ Adjusted the grammar of some translations, such as placing the verb first instead of last
+ Go through all the translations and fix multiple typos and incorrectly used HTML tags (that are no longer used in the English entry) in conjunction with the UI
+ Adjust the order of the entries to make sure they match the English entries (I think this will look easier :D)

I hope this will be helpful

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Review by MAGICCC — APPROVED** [review]

**Comment by MAGICCC** [comment]
Looks fine for me, can't speak chinese but didnt spot any json issues.
Next time you can use https://translate.mailcow.email/engage/mailcow-dockerized/ for translating

**Comment by MAGICCC** [comment]
May I ask why you closed this PR @yhdsl?

**Comment by yhdsl** [comment]
I got confused about the meaning of the button, due to I am not familiar with the operation of github

I hope I didn't screw anything up @MAGICCC

**Comment by MAGICCC** [comment]
Hah it's ok, don't worry

**Pull request merged**
