### PR TITLE
Add ability to define if Mailcow is running behind Reverse Proxy 

### PR DESCRIPTION
**Pull request by Knight1**
This Setting defines if Mailcow is running behind a proxy Server. If we don't do this Plugins like IPFuck spoof all those Headers and Mailcow is logging random IP's generated by a Plugin :o 

https://chrome.google.com/webstore/detail/ipfuck/bjgmbpodpcgmnpfjmigcckcjfldcicnd?hl=de

### CODE REVIEW

**Comment by andryyy** [comment]
This PR would be fatal to merge to master. You cannot set this to false, not adding any docs and let everyone merge it.

It allows to set IPs from set_real_ip_from. Not sure, but you probably set your local reverse proxy to accept these headers from anywhere? mailcow would indeed accept this, as the last hop is a local network address.

It should not accept these headers from elsewhere.

**Comment by andryyy** [comment]
But it does and it is a bug. I will update the Nginx config and PHP stuff. Thanks!

**Comment by andryyy** [comment]
It is fixed. REMOTE_ADDR will always be set to what we tell Nginx to use as real ip (x-forwarded-for).

Thank you very much for this hint!

**Comment by Knight1** [comment]
Thanks! But behind a proxy I guess that the IP is now the Proxy itself AFAIK.

**Comment by andryyy** [comment]
I checked, Nginx sets the real ip to what it finds in x-forwarded-for - as long as it was set by a trusted source.

**Comment by Knight1** [comment]
Jup I see it. Thanks!

**Pull request closed without merging**
