### PR TITLE
Update docker-entrypoint.sh

### PR DESCRIPTION
**Pull request by extremeshok**
Removed the # from curl -#o

### CODE REVIEW

**Comment by andryyy** [comment]
Why?

**Comment by phpfs** [comment]
Seems to be a typo which got fixed?!

**Comment by andryyy** [comment]
No, it just outputs the progress like this, when set: `"######------------ 40%"`

**Comment by phpfs** [comment]
Ok - then this PR seems to be misunderstanding :)

**Comment by ghost** [comment]
This equivalent of `-# -o`

**Pull request closed without merging**
