### PR TITLE
Only generate a LE certificate for domains that have a mailbox

### PR DESCRIPTION
**Pull request by develth**
This SQL query will just provide Domains that have a Mailbox created.
With this change we can reduce the amount of certificate requests that are not necessary.

### CODE REVIEW

**Comment by mkuron** [comment]
Good idea, but this change is going to be extremely annoying for people who set up a new Mailcow. They would need to manually restart the acme container after they add their first mailbox to a domain.

**Comment by develth** [comment]
I can´t find a trigger for acme container restart on Domain add (or i don´t see it). So when the acme container is triggered when you add a domain?
Edit: maybe i can trigger the same (if exists) when adding the first mailbox to a domain

**Comment by develth** [comment]
I just wanted to check my latest added Domains and recognized, that the script added a domain and requested a certificate that is not listed by this query.
How can this happen?

**Comment by andryyy** [comment]
Why would a domain without mailboxes exist?

**Comment by develth** [comment]
When you want to setup a Domain that just redirects named based and not a exact match.
Example:

```info@example.com``` to ```userxy@gmail.com```
```post@example.com```to ```useryz@web.de```

**Comment by andryyy** [comment]
I see. :)

**Comment by Adorfer** [comment]
Aren't those ceritificates as well used for smtp-tls? 
In that case: What will happen to alias-domains? And what about backup-MX? those do not have any mailbox as well.

**Comment by ntimo** [comment]
@Adorfer No the cert is not used for smtp-TLS the cert that is used for that is the mail server Hostnamen certificate (mail.domain.com). The other domains are just added to cert for autoconfig.

**Comment by Adorfer** [comment]
perhaps i am missing the point. So the LE certificates for the different mx-hostnames  (e.g. mail.domain1.com, mail.domain2.net, mail.domain3.org) come from another validation-script, which runs independend? Or are those only self-signed?

**Comment by develth** [comment]
There are no different mx hostnames

**Comment by Adorfer** [comment]
Perhaps setups differ. either with cnames or with a/aaaa inside every domain.
in other words: for this PR i would recommend an option/warning, that no mx-fqdn in a domain is possible if no mailboxes are created.

**Comment by develth** [comment]
But a certificate for mail.[domain] will not be generated. 
So why warn for something that currently not exists?

**Pull request closed without merging**
