### PR TITLE
Allow local_part to be "0"

### LINKED ISSUE #5563: Not able to create a mailbow "0@example.com"
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
I'm not able to create a mailbox with a local_part "0".
```

### Steps to reproduce:

```plain text
Try to create a mailbow with "0" as local_part.
```

The error comes from [this line](https://github.com/mailcow/mailcow-dockerized/blob/nightly/data/web/inc/functions.mailbox.inc.php#L1002), as "0" is evaluated as empty.

### PR DESCRIPTION
**Pull request by Quiwy**
Fixes #5563

### CODE REVIEW

**Comment by Skylsmoi** [comment]
Should we also check if $_data['local_part'] is different from 0 (as int)?

**Comment by Quiwy** [comment]
Hi @DerLinkman , do you have any news on this ?

Regards

**Comment by FreddleSpl0it** [comment]
Hi @Quiwy, thanks for the PR. I will review it after the holiday season. It will likely be merged in the January update.

**Comment by FreddleSpl0it** [comment]
I think fixing this specific line alone does not resolve all the issues. There is also an open issue (https://github.com/mailcow/mailcow-dockerized/issues/5190) regarding the use of '/' in mailbox names. It would be better to create a function that checks for a valid mailbox name and replace most of the `filter_var(username, FILTER_VALIDATE_EMAIL)` occurrences with this function.

PR https://github.com/mailcow/mailcow-dockerized/pull/5619

**Pull request closed without merging**
