### PR TITLE
Change default HTTP_BIND, HTTPS_BIND

### PR DESCRIPTION
**Pull request by aminvakil**
https://github.com/mailcow/mailcow-dockerized/issues/4315#issuecomment-1083034329

Fixes a part of https://github.com/mailcow/mailcow-dockerized/issues/4315.

### CODE REVIEW

**Comment by aminvakil** [comment]
It's effectively reverting https://github.com/mailcow/mailcow-dockerized/commit/64c12d50bc99a4d00e2603e9155ebd93f2c08f03 :)

**Comment by aminvakil** [comment]
And there is
```
# Important! Specifying an IPv4 address will skip all IPv6 bindings since Docker 20.x.
```
in https://mailcow.github.io/mailcow-dockerized-docs/post_installation/firststeps-ip_bindings/
It's working for me though using:
```
Docker version 20.10.14, build a224086
Docker Compose version v2.3.4
```
Also upgraded to docker-compose 2.4.0 and it worked ok too.

**Comment by andryyy** [comment]
Needs more tests.

This includes all options and overrides we offer in the helper-scripts directory via overrides, they all need to be verified.

Furthermore all mentions of override options in the docs should be tested and verified.

**Comment by aminvakil** [comment]
Maybe related to this?

20.10.6: https://docs.docker.com/engine/release-notes/#20106:
Networking:

- Fix implicit IPv6 port-mappings not included in API response. Before docker 20.10, published ports were accessible through both IPv4 and IPv6 by default, but the API only included information about the IPv4 (0.0.0.0) mapping [moby/moby#42205](https://github.com/moby/moby/pull/42205)

**Comment by DerLinkman** [comment]
Merging to feature/compose-v2 for detailed testing.

**Comment by aminvakil** [comment]
@Cerberus-ik @hugalafutro @gsloop I'd suggest helping the mailcow maintainers to fix the issues if you really care instead of demanding them to fix them for you.

At the end of the day you decide if you want to use this software or not, if you want to use it, help them, if you don't want to for any reason switch to another one.

But I can't think of a reason that gives the users right to demand maintainers of this repository or any other open-source software to fix issues for themselves.

P.S. Sorry for commenting on this PR, I was going to comment on issue, but just saw it has been limited.

**Comment by philipp-tty** [comment]
Would you quote me where I demanded a fix or anything else? I literally added my experiences and thoughts why this issue is of high priority in my opinion. Did you even read the closed thread?

**Comment by andryyy** [comment]
Thank you, we are now working on it.

Thank you, thank you, thank you. It's really what we need: help. This is an OS project, let's work on this together. And yes, if you don't like it, you can fork it and/or leave it. It's okay.

**Pull request merged**
