### PR TITLE
[Web] Danish lang. 🇩🇰

### PR DESCRIPTION
**Pull request by ghost**
will update more soon.

### CODE REVIEW

**Comment by andryyy** [comment]
Tak!

Shall we wait with merging?

**Comment by MAGICCC** [comment]
Also needs to be added to https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/vars.inc.php#L80 (should be 'da'?)
@Ylacat You may also add some danish words here: https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/dovecot.conf#L86

**Comment by ghost** [comment]
Så lidt!

I'll do that @MAGICCC 😅

**Comment by MAGICCC** [comment]
If you want you can reopen the PR and let open until you are done :)

**Comment by ghost** [comment]
@andryyy @MAGICCC I'm done

**Comment by MAGICCC** [comment]
thanks!

**Pull request merged**
