### PR TITLE
make footable-toggle bigger for fat finger user like me

### PR DESCRIPTION
**Pull request by tinect**
It's annoying to hit the "plus" in current size of 14px on mobile-device :-)

### CODE REVIEW

**Comment by dragoangel** [comment]
I think problem not in size. Problem in that it too close to checkbox. Additional space between them will help. Or checkbox can be swapped with ID column. Because ID by itself have no action it will easy to click on + button, and at same time on checkbox too.

**Comment by andryyy** [comment]
Hm. I'm also not sure. Can we move it a bit? :)

**Comment by tinect** [comment]
Good point. But ID isn't in every table :-)
Where can we move it? Increasing space? Or move it to last (new) column (but before action)?

**Comment by andryyy** [comment]
Hmmmm, not sure actually. :( I'd need to try it in the dev console.

**Pull request closed without merging**
