### PR TITLE
quarantine quick_release & quick_delete without buttonclick

### PR DESCRIPTION
**Pull request by tinect**
This will add possibility to quick_delete or quick_release in quarantine email-template by prepending "quick_". So there is no need to press button.

### CODE REVIEW

**Comment by ntimo** [comment]
Could you please elaborate more on this quick release feature? I would guess it just changes the way the release is handled and removes the need to click the release button.

**Comment by tinect** [comment]
will inspect it more

**Comment by tinect** [comment]
I don't get any possibility to close the window automatically or something else.

In addition to this PR I'll work on more improvements to the quarantine-management :-)

**Comment by Adorfer** [comment]
"Oneclick Release/Delete&Autolearn" would be very helpful. Because it would avoid enless "back and forth" in the browser with at least 2 clicks and one keypress per individually treated mail in the quarantine.

**Pull request closed without merging**
