### PR TITLE
introduce json-files for translations

### PR DESCRIPTION
**Pull request by tinect**
Benefits: Structure data and add ability using translation managements

Had this idea while checking in translation-files. The blocks are random in every translation file.

### CODE REVIEW

**Comment by andryyy** [comment]
This adds more overhead and makes maintaining not easier at all. :( you could transform the php arrays in a more readable format.

**Comment by tinect** [comment]
Oh, you're talking about encoded content? These do not have to be encoded, so it would be more readable and maintainable 🤔

**Comment by andryyy** [comment]
...access_denied": "Acc\u00e9s...


Looks much easier to maintain the PHP files if we just pretty-print them. 

We already have PHP and read it into Json. I don't see the point for turning this around. There are other more important things to be changed.

**Comment by tinect** [comment]
Will update nederlands soon :-)

**Comment by tinect** [comment]
Based on current texts (including https://github.com/mailcow/mailcow-dockerized/commit/62a17737801793088b58a296536428fcb810a931). Added existing and same translations on different keys.

**Comment by andryyy** [comment]
Let's do it. :)

**Pull request merged**
