### PR TITLE
[Clamd] fix whitelist

### PR DESCRIPTION
**Pull request by feldsam**
@MAGICCC 

Signed-off-by: Kristian Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by dragoangel** [comment]
Maybe add `if [[ ! -f /etc/clamav/whitelist.ign2 ]]; then` condition before https://github.com/mailcow/mailcow-dockerized/blob/020cb8b35cd7a330764dbc1e894b524eb5f71af0/data/Dockerfiles/clamd/clamd.sh#L43

What you think? As we also before that copy `/etc/clamav/whitelist.ign2` to `/var/lib/clamav/whitelist.ign2` if it exist...

**Comment by feldsam** [comment]
@dragoangel check line 22

**Comment by feldsam** [comment]
this clamd.sh file doesn't need any changes, I just reverting back what was removed

**Comment by dragoangel** [comment]
Yes, I checked line 22 :)
We have data/conf mounted to etc. If we have file there we copy it from etc to var where it actually apply whitelist. Then we always copy it back from var to etc and I don't get why we need do it if we already have it :P. This not big issue, but just additonal unesesary copying of file on each container restart

**Comment by feldsam** [comment]
because it is there for years, so why change it? it doesnt cause overwriting. Probably we can remove that line, because it is useless

**Comment by dragoangel** [comment]
Oh, missed that maybe. It not useless as it create default whitelist if it missing once

**Comment by MAGICCC** [comment]
Seems I did some other things thats why I commented it. What about using clamd:1.50 then I can repush with same version and we dont need to merge into master for this change?

**Comment by DerLinkman** [comment]
Yeah but please move that into staging anyways for the integrity you know what I mean guys 😉

**Pull request merged**
