### PR TITLE
Added new feature request Github template and edited bugs template

### PR DESCRIPTION
**Pull request by ntimo**
Hello,
I added a new feature request template and also edited the bugs template to be a bit more clear and added a logs section :)

### CODE REVIEW

**Comment by andryyy** [comment]
Thanks, but why is there a „Merge pull request #3 from mailcow/master“? Can you please fix it?

Why did you decide to remove the hint from notice? :/

An issue template change should be discussed, it is not something that is open for the community to be changed. The logs stuff is mentioned in the docs, just link there, please.

**Comment by andryyy** [comment]
What was your intention to remove the notice stuff? Maybe I am missing something. :)

**Comment by ntimo** [comment]
Hello André, I can't remove the "Merge pull request #3 from mailcow/master" because I needed to update my clone of the mailcow-docerized repo to the latest master from the official one. If you know how I can remove it without deleting the repo and recloning it please let me know.

My intention to remove the notice stuff was that it is a bit a confusing to tell the user that he can remove this paragraph therefor I thought it would be better to just leave it in there.

**Comment by andryyy** [comment]
My intention to remove the notice stuff was that it is a bit a confusing to tell the user that he can remove this paragraph therefor I thought it would be better to just leave it in there.

I see. Hm, yes, it can be confusing. But at least we know people actually read the template. 😄 

Thanks!

**Pull request merged**
