### PR TITLE
[Web] Make TLS policy toggles accessible

### LINKED ISSUE #4554: A11y: Mailcow UI, Edit Mailbox: The toggle states of the Enforce TLS incoming / outgoing buttons are not exposed for screenreaders
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

On the Edit Mailbox page of the Mailcow web UI, the toggle states of the "Enforce TLS outgoing" and "Enforce TLS incoming" buttons are not exposed to screenreaders.
For me as a blind screenreader user, this means I only hear an announcement of, for example, "Enforce TLS outgoing, button" without knowing whether this is currently on or off.

There's probably some visual treatment on these buttons to represent the current state, but no attribute that could be utilized by a screenreader to convey this appropriately.

### Logs

```bash
As this is purely a UI bug I can't think of any relevant logs to include here.
```

### Steps to reproduce

1. On a windows machine, download and install the free, open-source NVDA screenreader from https://www.nvaccess.org/download/.
Alternatively, on a Linux system with a graphical desktop the Orca screenreader can be installed from package repositories in most cases.
2. Open a browser (tested with Brave and Firefox in my case) and login to the Mailcow UI.
3. Open Configure > Mail Setup > Mailboxes and click the Edit link next to a mailbox.
4. Move screenreader focus to the "Enforce TLS incoming" and "Enforce TLS outgoing" buttons and observe speech output.

### System information

Again, this is probably irrelevant due to the nature of this bug - please advice if I'm wrong and I'll be happy to provide any missing details.

### PR DESCRIPTION
**Pull request by mkuron**
Fixes #4554 reported by @robin24.

### CODE REVIEW

**Comment by DerLinkman** [comment]
Function still works as intended?

Did you test the screenreader function as well?

**Comment by mkuron** [comment]
The setting still gets saved correctly and https://github.com/mailcow/mailcow-dockerized/issues/4554#issuecomment-1107830704 confirmed that a screenreader now gives a reasonable description.

**Comment by DerLinkman** [comment]
👍

**Review by DerLinkman — APPROVED** [review]
Looks good to me.

Function works like intended.

**Pull request merged**
