### PR TITLE
[Rspamd] Block spoofing for free mail domains

### PR DESCRIPTION
**Pull request by dragoangel**

### CODE REVIEW

**Comment by mkuron** [comment]
So what exactly does this rule do? It requires free mail providers to be DMARC-compliant, or is there more to it?

**Comment by dragoangel** [comment]
Hi @mkuron, in short - yes. Gmail and Outlook and most of free mail providers set their DMARC policy to none, but at same time they not send from IPs not listed at SPF or mail that signed DKIM incorrectly. So p=none for them only allow spammers to get in junk or even to inbox. With this policy such spoofing will be rejected.

**Comment by mkuron** [comment]
So basically you're suggesting to treat free mail providers differently from all other providers and pretending they set their DMARC policy to something like `p=reject`? What if there's a reason why these providers don't have DMARC policies?

**Comment by dragoangel** [comment]
> What if there's a reason why these providers don't have DMARC policies?

Don't know why exactly most of free mail providers set p=none and by this allowing spoofing, but for me this rule works for a while and stop spoofing attempts and it don't ban legal mail (not have false positive side effect).

**Comment by andryyy** [comment]
This should work, let's give it a try. I run it a few days.

**Comment by berkaycagir** [comment]
This policy made (or contributed hugely) rspamd classify a post to a mailman list from a gmail account as spam. What logs/sources should I post? Not sure if I should post a rspamd screenshot or something else.

**Comment by andryyy** [comment]
The symbols of the message in its header.

**Comment by berkaycagir** [comment]
I kind of censored some of the information, if there'd be anything you need happy to send it somehow private.

```
FREEMAIL_POLICY_FAILURE (16)
R_DKIM_REJECT (8) [gmail.com:s=20161025]
FORGED_W_BAD_POLICY (3)
R_MIXED_CHARSET (0.574074) [subject]
RCVD_NO_TLS_LAST (0.1)
MAILLIST (-0.2) [mailman]
MIME_GOOD (-0.1) [multipart/mixed, multipart/alternative, text/plain]
MX_GOOD (-0.01) []
HAS_LIST_UNSUB (-0.01)
RCPT_COUNT_ONE (0) [1]
PREVIOUSLY_DELIVERED (0) [****@****.****.****.****]
DMARC_POLICY_SOFTFAIL (0) [gmail.com : No valid SPF, none]
RCPT_MAILCOW_DOMAIN (0) [****.****]
TAGGED_FROM (0)
DKIM_TRACE (0) [gmail.com:-]
RCVD_COUNT_THREE (0) [4]
FORGED_SENDER (0) [****@gmail.com, ****-bounces@****.****.****.****]
ARC_NA (0)
MIME_TRACE (0) [0:+, 1:+, 2:+, 3:~, 4:+]
ASN (0) [asn:****, ipnet:****, country:TR]
CTYPE_MIXED_BOGUS (0)
ARC_SIGNED (0) [****.****:s=mx:i=1]
FORGED_SENDER_MAILLIST (0)
FROM_NEQ_ENVFROM (0) [****@gmail.com, ****-bounces@****.****.****.****]
HAS_REPLYTO (0) [****@****.****.****.****]
R_SPF_NA (0) [no SPF record]
TO_DN_ALL (0)
FROM_HAS_DN (0)
```

**Comment by andryyy** [comment]
What list is this?

DKIM reject with mailman sounds more like a misconfiguration on their side.

**Comment by dragoangel** [comment]
Without my proposed policy it will be lend in junk. Why Dkim failed? Mailman intercepted headers or body?

**Comment by berkaycagir** [comment]
I think Mailman does something there, and I'll get in touch with that list's administrators, however there are perfectly fine messages with no DKIM:

```
FORGED_W_BAD_POLICY (3)
AUTH_NA (1)
R_MIXED_CHARSET (0.782609) [subject]
RCVD_NO_TLS_LAST (0.1)
MAILLIST (-0.2) [mailman]
MIME_GOOD (-0.1) [text/plain]
MX_IMPLICIT (-0.01)
HAS_LIST_UNSUB (-0.01)
RCVD_COUNT_SEVEN (0) [8]
PREVIOUSLY_DELIVERED (0) [****@****.****.****.****]
RCPT_MAILCOW_DOMAIN (0) [****.****]
RECEIVED_SPAMHAUS_PBL (0) [***.***.***.***:received]
MID_RHS_MATCH_FROM (0)
MIME_TRACE (0) [0:+]
FORGED_SENDER (0) [****@****.****.****, ****-bounces@****.****.****.****]
ARC_NA (0)
DMARC_NA (0) [****.****.****]
R_DKIM_NA (0)
ASN (0) [asn:****, ipnet:****, country:TR]
ARC_SIGNED (0) [****.****:s=mx:i=1]
FORGED_SENDER_MAILLIST (0)
RCVD_VIA_SMTP_AUTH (0)
FROM_NEQ_ENVFROM (0) [****@****.****.****, ****-bounces@****.****.****.****]
HAS_REPLYTO (0) [****@****.****.****.****]
R_SPF_NA (0) [no SPF record]
RCPT_COUNT_ONE (0) [1]
TO_DN_NONE (0)
FROM_HAS_DN (0)
```

While this specific Mailman installation might have some problems, wouldn't this policy in general be a problem with mailing lists? For sure Env From or From will be the sender's address which will be a freemail, and the sender IP won't be in their SPF for sure; even if the DKIM was or was not done properly.

**Comment by dragoangel** [comment]
It's will not trigger if DMARC_POLICY_ALLOW will be in place or if this mail was been received via from trusted forwarder of mailcow.

**Comment by andryyy** [comment]
They may want to remove "old" DKIM signatures, I think.

**Comment by dragoangel** [comment]
@berkaycagir here is a good article which quite fine explain how mail lists can work with dkim/dmarc/spf: https://begriffs.com/posts/2018-09-18-dmarc-mailing-list.html

**Comment by mkuron** [comment]
Most mailing lists I have seen are misconfigured in ways that break DKIM. If they modify the body but don‘t rewrite the sender, the signature gets broken. Since that will likely remain a problem for a long time, and we won‘t get all admins to fix their configs, we should consider removing the FREEMAIL_POLICY_FAILURE symbol when a MAILLIST symbol is also present.

**Comment by dragoangel** [comment]
Not secure, but not bad idea, I will create PR tommorow or you can change it now if you are near PC @mkuron ? I also curious how they getting inbox if they permanently each time breathing someone dkim and do not get to some rbl etc.

Update: created PR #3918

**Comment by berkaycagir** [comment]
> They may want to remove "old" DKIM signatures, I think.

Thank you, I'll convey that.

> @berkaycagir here is a good article which quite fine explain how mail lists can work with dkim/dmarc/spf: https://begriffs.com/posts/2018-09-18-dmarc-mailing-list.html

Thanks, I'll check that out.

> Most mailing lists I have seen are misconfigured in ways that break DKIM. If they modify the body but don‘t rewrite the sender, the signature gets broken. Since that will likely remain a problem for a long time, and we won‘t get all admins to fix their configs, we should consider removing the FREEMAIL_POLICY_FAILURE symbol when a MAILLIST symbol is also present.

I was thinking this (or adding a lower score if MAILLIST symbol is present) too. I mean I'm fine with it landing to junk but I myself wouldn't want to send bounces to lists every time with broken DKIM.

**Pull request merged**
