### PR TITLE
🌐 Add Traditional Chinese Translation

### PR DESCRIPTION
**Pull request by tomy0000000**
As title, I'm adding a new translation.

Simplified Chinese (简体中文): Used in China, Singapore, ....
Traditional Chinese (繁體中文): Used in Taiwan, Hong Kong, ...

This is a working progress, the translation data available now is translated by machine, and I'll walk through the data in the next few days and request merged after everything is done.

Feedbacks are welcomed.

### CODE REVIEW

**Comment by tomy0000000** [comment]
Progress (Rolling Updating): 

- [x] acl (29)
- [x] add (77)
- [x] admin (235)
- [x] danger (117)
- [x] debug (24)
- [x] diagnostics (9)
- [x] edit (111)
- [x] fido2 (13)
- [x] footer (13)
- [x] header (9)
- [x] info (3)
- [x] login (7)
- [x] mailbox (156)
- [x] oauth2 (7)
- [x] quarantine (51)
- [x] ratelimit (5)
- [x] start (4)
- [x] success (77)
- [x] tfa (25)
- [x] user (159)
- [x] warning (11)

<details>
<summary>List of generic converted terms</summary>
<ul>
<li>啓用 -> 啟用</li>
<li>重啓 -> 重新啟動</li>
<li>登錄 -> 登入</li>
<li>用戶名 -> 使用者名稱</li>
<li>用戶 -> 使用者</li>
<li>設備 -> 裝置</li>
<li>默認 -> 預設</li>
<li>配置 -> 組態</li>
<li>重置 -> 重設</li>
<li>設置 -> 設定</li>
<li>策略 -> 規則</li>
<li>映射 -> 規則表</li>
<li>服務器 -> 伺服器</li>
<li>內存 -> 記憶體</li>
<li>日誌 -> 紀錄</li>
<li>搜索 -> 搜尋</li>
<li>訪問 -> 存取</li>
<li>保存 -> 儲存</li>
<li>信息 -> 訊息</li>
<li>郵箱 -> 信箱</li>
<li>屏幕 -> 畫面</li>
<li>周 -> 週</li>
<li>紀錄 -> 記錄</li>
<li>磁盤 -> 硬碟</li>
<li>添加 -> 新增</li>
<li>端口 -> 通訊埠</li>
<li>證書 -> 憑證</li>
<li>自定義 -> 自訂</li>
<li>文件夾 -> 資料夾</li>
<li>遠程 -> 遠端</li>
<li>數據 -> 資料</li>
<li>高級 -> 進階</li>
<li>網絡 -> 網路</li>
<li>密鑰 -> 金鑰</li>
<li>鏈接 -> 連結</li>
<li>封禁-> 禁止</li>
<li>正則表達式 -> 正規表示式</li>
<li>列表 -> 清單</li>
<li>隊列 -> 佇列</li>
<li>禁用 -> 停用</li>
<li>支持 -> 支援</li>
<li>客戶端 -> 用戶端</li>
<li>模板 -> 模版</li>
<li>刷新 -> 重新整理</li>
<li>示例 -> 範例</li>
<li>發件人 -> 寄件人</li>
<li>全局 -> 全域</li>
<li>主題 -> 主旨</li>
<li>協議 -> 協定</li>
</ul>
</details>

**Comment by tomy0000000** [comment]
@DerLinkman I think everything is ready to go, please have a look.

In addition to the translation, I did some research about different language codes specification, and suggest we should change to IETF language tag which is a superset of the current ISO 639-1 standard. Specifically, it consists with two codes: `{lanugage}-{region}`, so this also fix a bug where some language (Ukrainian) can not display a proper flag icon.

A Full conversion table is as follow: 

| **Old Code** | **New Code** | **Display Name**               |
| ------------ | ------------ | ------------------------------ |
| cs           | cs-cz        | Čeština (Czech)                |
| da           | da-dk        | Danish (Dansk)                 |
| de           | de-de        | Deutsch (German)               |
| en           | en-gb        | English                        |
| es           | es-es        | Español (Spanish)              |
| fi           | fi-fi        | Suomi (Finish)                 |
| fr           | fr-fr        | Français (French)              |
| hu           | hu-hu        | Magyar (Hungarian)             |
| it           | it-it        | Italiano (Italian)             |
| ko           | ko-kr        | 한국어 (Korean)                |
| lv           | lv-lv        | latviešu (Latvian)             |
| nl           | nl-nl        | Nederlands (Dutch)             |
| pl           | pl-pl        | Język Polski (Polish)          |
| pt           | pt-pt        | Português (Portuguese)         |
| ro           | ro-ro        | Română (Romanian)              |
| ru           | ru-ru        | Pусский (Russian)              |
| sk           | sk-sk        | Slovenčina (Slovak)            |
| sv           | sv-se        | Svenska (Swedish)              |
| uk           | uk-ua        | Українська (Ukrainian)         |
| zh           | zh-cn        | 简体中文 (Simplified Chinese)  |
|              | zh-tw        | 繁體中文 (Traditional Chinese) |

**Comment by MAGICCC** [comment]
> In addition to the translation, I did some research about different language codes specification, and suggest we should change to IETF language tag which is a superset of the current ISO 639-1 standard. Specifically, it consists with two codes: `{lanugage}-{region}`, so this also fix a bug where some language (Ukrainian) can not display a proper flag icon.

I'd need to check if I can easily transform from ISO 639-1 to IETF in weblate

**Comment by tomy0000000** [comment]
> > In addition to the translation, I did some research about different language codes specification, and suggest we should change to IETF language tag which is a superset of the current ISO 639-1 standard. Specifically, it consists with two codes: `{lanugage}-{region}`, so this also fix a bug where some language (Ukrainian) can not display a proper flag icon.
> 
> I'd need to check if I can easily transform from ISO 639-1 to IETF in weblate

I don't have any experience with weblate, but I found [this page](https://docs.weblate.org/en/latest/contributing/schemas.html?highlight=IETF#weblate-translation-memory-schema) in their docs, hope this might help.

**Comment by MAGICCC** [comment]
I guess, when I'll follow https://github.com/WeblateOrg/weblate/discussions/7996 it'll be fine

**Comment by tomy0000000** [comment]
I saw this PR had been stale for a while, so do let me know if there's anything I can do to help.

**Comment by MAGICCC** [comment]
> I saw this PR had been stale for a while, so do let me know if there's anything I can do to help.

You can resolve the conflicts and then we can maybe try to merge it maybe? Do you have concerns about this @DerLinkman? For weblate I would try to fix it after the merge.

**Comment by DerLinkman** [comment]
@MAGICCC please check if you can change that in Weblate before we merge it.

And yes. The merge conflicts should be fixed.

**Comment by tomy0000000** [comment]
@MAGICCC @DerLinkman I've resolved the conflict, please have a look.

**Comment by DerLinkman** [comment]
Hm. That don´t work at all :(

grafik

I´ve checked out the PR here but now all Strings are empty.

Interestingly is this:

grafik

**Comment by tomy0000000** [comment]
Is there a document about how to start the modified backend server for debugging?

**Comment by DerLinkman** [comment]
> Is there a document about how to start the modified backend server for debugging?

You can set DEV_MODE=y in your mailcow.conf.

Then PHP is logging more to debug.

**Comment by tomy0000000** [comment]
> > Is there a document about how to start the modified backend server for debugging?
> 
> You can set DEV_MODE=y in your mailcow.conf.
> 
> Then PHP is logging more to debug.

I mean spawning a new backend instance without interfering the production one

**Comment by DerLinkman** [comment]
Just tested it. Works better but the english language is not completely correct i guess.

grafik

I think it´s only the logo.

**Comment by DerLinkman** [comment]
And also: the automatic language detection does not work anymore. It´s standardly english now.

Just some quick feedback :)

**Comment by tomy0000000** [comment]
> And also: the automatic language detection does not work anymore. It´s standardly english now.
> 
> Just some quick feedback :)

Can you paste your `accept-language` entry in the request headers, this will be helpful

Screen Shot 2022-10-06 at 10 39 33 PM

**Comment by tomy0000000** [comment]
I've made some improvements to the algorithms for determining language. Here are the rules, run sequentially:

1. Perfect match (Match a full 2-2 code)
2. Partial match (Match the first 2 characters of code, language but not country)
3. Suggestion match (Match the first 2 characters from the user's first 2 characters of the 2-2 code)
4. Fallback to `en-gb`

Some examples (keep in mind we only have `en-gb` but not `en-us`):

- `en-us, zh-tw` => `zh-tw` (Perfect match)
- `en-us, en, zh-tw` => `en-gb` (Partial match)
- `en-us` => `en-gb` (Suggest match)

**Comment by tomy0000000** [comment]
Regarding the missing English flag, it's a bug originated in [007-languages.min.css](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/css/build/007-languages.min.css).

You can see there are [gb.svg](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/css/flags/4x3/gb.svg) in both 1x1 and 4x3 format, but when the css is compiled in da20d5dc38ef79ca87179080323491a50e9eb222, they are somehow not included.

I could fix it manually, but I'm worry if it will be overwrite in future updates. @andryyy do you mind take a look or explain how css is compiled?

**Comment by DerLinkman** [comment]
Feedback Round 2 :)

Looks good so far in case of translations and autorecognition etc.

@FreddleSpl0it may also can explain your question about CSS?

**Comment by DerLinkman** [comment]
> I could fix it manually, but I'm worry if it will be overwrite in future updates.

It will definately (at least once with Bootstrap 5) but we´ll test it anyways and repair it during the finalization of the update.

**Comment by tomy0000000** [comment]
> > I could fix it manually, but I'm worry if it will be overwrite in future updates.
> 
> It will definately (at least once with Bootstrap 5) but we´ll test it anyways and repair it during the finalization of the update.

Great, that will work.

Is there anything else I should do/fix to merge this PR?

**Comment by DerLinkman** [comment]
I would merge it into the special bs5 featured branch first to make sure the whole thing still works when we merge bs5 into master.

This PR will merged before BS5 i guess so it´s only for dev purposes so to say (that special branch)

**Comment by DerLinkman** [comment]
Alrighty!

Then it looks fine to me.

Thank you for this. @MAGICCC you wanted to check it on Weblate right?

**Review by DerLinkman — APPROVED** [review]
Looks fine to me :)

**Comment by MAGICCC** [comment]
Yes I fixed it on Weblate too

**Comment by cjw0202** [comment]
Hi, on inbox page, the searchinput do not support chinese

**Pull request merged**
