### PR TITLE
Optimize updating of docker-compose

### PR DESCRIPTION
**Pull request by Linus9000**
This pull request aims to prevent a download of docker-compose if the latest version is the same we have already installed.

While most servers connection should be fast enough to download docker-compose without any issues, I'm having some problems with the approach of first stopping the containers, then downloading docker-compose before restarting the containers. The approach itself is reasonable, considering the compose file might introduce changes requiring a recent docker-compose version, however waiting some minutes (assuming a bad connection) before restarting the containers bugs me. While it should be possible to download docker-compose before stopping the containers (assuming no change in docker-compose breaks `docker-compose down`, obviously) this propose leads to less wasted bandwith and was quite easy to implement.

Feel free to share your thoughts if you think this is a bad idea :)

### CODE REVIEW

**Comment by stevesbrain** [comment]
I agree; my routes to download it often go fairly slow for the size of the file, and the fact we bring the servers down before downloading it increases the downtime. Not a big deal, but any downtime saved is a bonus in my books :)

**Comment by chriscroome** [comment]
I have been using a [Ansible Playbook](https://git.coop/webarch/docker#install-or-upgrade-docker-compose) to upgrade Docker Compose, this results in it being owned by `root`. I manage Mailcow using a non-root account (that is a member of the `docker` group) and this means that the part of the script that tries to update `docker-compose` always fails due to the `mailcow` user not having write permissions, so my only suggestion would be that skipping the download if the `docker-compose` file isn't writable would be an additional check that could be added.

**Comment by Linus9000** [comment]
Seems like a reasonable change, so I just added the check.

**Comment by andryyy** [comment]
Thanks, but please push only to dev. Do not just change the base, that will probably break things.

**Comment by Linus9000** [comment]
Sorry, didn't know your workflow here :) Changed target branch accordingly. If you prefer I can also create a new pull request.

**Comment by andryyy** [comment]
No problem, but you did exactly that: you just changed the base. I cannot merge that.

**Pull request closed without merging**
