### PR TITLE
[web] helper script for detecting missing translations

### PR DESCRIPTION
**Pull request by feldsam**
Signed-off-by: Kristian Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by andryyy** [comment]
Cool! Could you add this to the docs? I'd just change some style in the PHP, ok? Not because it is wrong or bad, just for uniformity. :D :)

**Comment by MAGICCC** [comment]
ah nice, I always checked the CI results :)

**Comment by feldsam** [comment]
Hi @andryyy, no problem feel free to change the code style. Regarding docs, in which section should I add it? There is nothing about translations.

**Comment by ctrl-i** [comment]
That seems like a lot of code...  Would something like this one-liner be easier to maintain?

`comm -23 <( jq -r 'paths(scalars) | map(.|tostring)|join(" > ")' lang.en.json | sort ) <( jq -r 'paths(scalars) | map(.|tostring)|join(" > ")' lang.es.json | sort )`

This utilizes jq (downside, might need to be installed) to create a list of all the keys in lang.en.json,  We do this again for lang.es.json.  Finally we use comm to output all the keys that are in lang.en.json but not in lang.es.json. 

Obviously this could be automated further.

**Comment by feldsam** [comment]
Hi, looks great, but I don't think so. This is easy to maintain for folks working with jq, for regular people working with frontend technologies it can be hard to understand.

**Comment by andryyy** [comment]
We could add both I guess.

**Comment by ctrl-i** [comment]
> We could add both I guess.

Let me know if you would like me to expand my one-liner into a script and I can work on it.

**Comment by andryyy** [comment]
That would be very much appreciated :)

**Comment by andryyy** [comment]
We should also add it to the docs.

**Pull request merged**
