### PR TITLE
Fix typo in generate_config.sh

### PR DESCRIPTION
**Pull request by ThomDietrich**
🤷‍♂

### CODE REVIEW

**Comment by gamil2010** [comment]
I am a beginner in UAV simulation  and  I want to know what protocol used in ThomDietrich/multiUAV-simulation?
if any one can help me?

**Comment by ThomDietrich** [comment]
Any reason for not merging this PR?

**Comment by andryyy** [comment]
No, sorry.

**Comment by ThomDietrich** [comment]
No worries. thanks

**Pull request merged**
