### PR TITLE
Update imapsync to 2.148

### PR DESCRIPTION
**Pull request by MAGICCC**
Also needs a rebuild of dovecot container

### **Changelog:**

- **2.140**
- **General:** New release numbering from 1.999 directly to 2.100; I want to avoid 1.1000 and sorting issues in directory listing.
- **Dependencies removed:** None
- **Dependencies added:** None
- **Enhancement:**  Check if SEARCH ALL works on both accounts and then add --noabletosearch if one can not. Use --nochecknoabletosearch to avoid that behavior.
- **Enhancement:**  Added an analyse and classification of the errors encountered. Most common error encountered is printed at the end. Exit value 112 (EXIT_WITH_ERRORS_MAX) is now replaced by the most common error encountered exit value:

         EX_OK          => 0  ; #/* successful termination */
         EX_USAGE       => 64 ; #/* command line usage error */
         EX_NOINPUT     => 66 ; #/* cannot open input */
         EX_UNAVAILABLE => 69 ; #/* service unavailable */
         EX_SOFTWARE    => 70 ; #/* internal software error */
         EXIT_CATCH_ALL              =>   1 ; # Any other error
         EXIT_BY_SIGNAL              =>   6 ; # Should be 128+n where n is the sig_num
         EXIT_BY_FILE                =>   7 ;
         EXIT_PID_FILE_ERROR         =>   8 ;
         EXIT_CONNECTION_FAILURE     =>  10 ;
         EXIT_TLS_FAILURE            =>  12 ;
         EXIT_AUTHENTICATION_FAILURE =>  16 ;
         EXIT_SUBFOLDER1_NO_EXISTS   =>  21 ;
         EXIT_WITH_ERRORS            => 111 ;
         EXIT_WITH_ERRORS_MAX        => 112 ;
         EXIT_OVERQUOTA              => 113 ;
         EXIT_ERR_APPEND             => 114 ;
         EXIT_ERR_FETCH              => 115 ;
         EXIT_ERR_CREATE             => 116 ;
         EXIT_ERR_SELECT             => 117 ;
         EXIT_TRANSFER_EXCEEDED      => 118 ;
         EXIT_ERR_APPEND_VIRUS       => 119 ;
         EXIT_TESTS_FAILED           => 254 ; # Like Test::More API
         EXIT_CONNECTION_FAILURE_HOST1     =>  101 ;
         EXIT_CONNECTION_FAILURE_HOST2     =>  102 ;
         EXIT_AUTHENTICATION_FAILURE_USER1 =>  161 ;
         EXIT_AUTHENTICATION_FAILURE_USER2 =>  162 ;

- **Enhancement:** Added option --dry1 it avoids to fetch the message on host1 in --dry mode. Option --dry1 is on when --dry is on. It speeds up --dry very much. To get the old --dry behavior, use --dry --nodry1
- **Enhancement:** Do both sides login and authentication before exiting on failure.
- **Enhancement:** --timeout can now be a float (was only integer). Same for --timeout1 --timeout2
- **Enhancement:**  Added option --syncduplicates to sync duplicates. On by default in CGI context. Off by default on command line.
- **Enhancement:**  Added option --trylogin. After a login failure of any kind, imapsync tries to login with the LOGIN command. Use --notrylogin to avoid that. --trylogin is on by default.
- **Enhancement:**  Added options --oauthaccesstoken1 and --oauthaccesstoken2 to support OAUTH2 authentication.
- **Enhancement:**  Added options --oauthdirect1 and --oauthdirect2 to support OAUTH2 authentication.
- **Enhancement:**  Added statistic line "CPU time and %cpu". Example: "CPU time and %cpu : 9.2 sec 39.8 %cpu 19.9 %allcpus".
- **Enhancement:**  Added option --filterbuggyflags to filter flags known to be buggy and generators of errors "BAD Invalid system flag" or "NO APPEND Invalid flag list".
   

-  **CGI context:** Back from Message-Id to Message-Id Received in cgisetcontext
-  **CGI context:** In CGI context, the log directory is no longer ./LOG_imapsync/ but simply ./ It should fasten the searches and grep
-  **CGI context:** Added --loglogfile option. Append ../list_all_logs_auto.txt with the logfile name. On by default in CGI context.
-  **Usability:** Changed time presentation on ETA and in final stats. Example: Wednesday 16 June 2021-06-16 00:32:05 +0200 CEST
- **Usability:** Do not check selectable folders for huge accounts with more than 152 folders, 98 percentile of /X; It could be very long and ended up with some users transformed in stone just by staring at the fixed output.
 - **Bug fix:** The number of detected cpus (cores) was accurate only on Linux. Added Freebsd and fixed Darwin and Windows parts.
 - **Refactoring:** Continuing to deglobalize the global variables.
 - **Refactoring:** 1734 unit tests.

### CODE REVIEW

**Comment by svengo** [comment]
I'm a little confused. Wouldn't it be better to download the `imapsync` script in the `dockerfile` directly from github? Such a download is already done [elsewhere](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dovecot/Dockerfile#L88).

**Comment by andryyy** [comment]
There seems to be an even newer version @ https://imapsync.lamiral.info/imapsync :)

I don't think we should auto-download, it may be necessary to add new dependencies.

**Comment by MAGICCC** [comment]
> 
> 
> There seems to be an even newer version @ https://imapsync.lamiral.info/imapsync :)

Indeed, but on his [changelog](https://imapsync.lamiral.info/S/news.shtml) he only mentioned 2.140 which I guess is somewhat stable maybe? I can upgrade the PR to 2.148, but no idea what got changed there without checking the whole code.

**Comment by feldsam** [comment]
> There seems to be an even newer version @ https://imapsync.lamiral.info/imapsync :)
> 
> I don't think we should auto-download, it may be necessary to add new dependencies.

This is an example Dockerfile https://imapsync.lamiral.info/INSTALL.d/INSTALL.Docker_build.txt, where is a script for checking dependencies.

**Comment by andryyy** [comment]
But that script does not really help. How would it? The dep check fails and then the images does not build. I don't quite get it. :/

**Comment by andryyy** [comment]
It would at least fail to build, hum. But I really prefer manual testing. Not sure yet. :)

**Comment by feldsam** [comment]
It was just reply to required dependencies check. Manual testing is of course better from QA perspective, so better for all users. I have in mind only autodownload of specific version defined in build arg, like in SOGo Dockerfile, so no need to store whole program in our repo. Missing tags in the Imapsync github repo can be problem.

**Comment by MAGICCC** [comment]
> 
> Missing tags in the Imapsync github repo can be problem.

Which indeed is a problem at the moment. I checked my imapsync and got an info that theres a new update available - like with my previous PR

**Comment by MAGICCC** [comment]
As seen on Telegram this morning @andryyy I updated to 2.148

**Pull request merged**
