### PR TITLE
Update generate_config.sh

### PR DESCRIPTION
**Pull request by idenkov**
Creating the log files for clamav, without them it gets stuck in a loop and never update the DB.

### CODE REVIEW

**Comment by andryyy** [comment]
I don't understand, why do you need to create them on your host?

We create those files as links to pipes inside the container. :-)

**Comment by tkorves** [comment]
Doesn't make sense - will not be added.

**Comment by idenkov** [comment]
You are right, however it was late and the logs were saying this so I didn't put much thinking. And after creating it on the host errors stop showing, which is weird.
However the container don't have that /var/log/clamav folder, there is touch for these two files in the bootstrap.sh but that does nothing because the directory does not exist. Will submit another proper pull when I get a bit of time.

**Comment by andryyy** [comment]
It does not care about what is on your host.

Please don't push stuff like that...

There is a relict from older versions which tries to chown files that are not necessary, I removed this line. It is a useless line that does nothing.

**Comment by idenkov** [comment]
My previous comment is about the container not the host. What line do you talk about that you removed? Agree the pull was stupid, it was the last thing I did before going to bed.

**Pull request closed without merging**
