### PR TITLE
[BS5] Support for pagination_size + some minor improvements (to quarantine)

### PR DESCRIPTION
**Pull request by realizelol**
- This will add support for "pagination_size" in DataTables which will be addressed to pageLength.
- Fix some indentations + line endings.
- Set all template tables to 100% width.
- Set max-width of senders column to 220px in quarantine.
- Sorting quarantine by newest/highest id. (column 2)
- Set default width of every column to 8,25%.
- Allow possible vertical-x-scrolling in quarantine.
- Allow showing all entries in quarantine. Also set other values: 10, 25, 50, 100.
- Set pagingType in quarantine to `first_last_numbers`: 'First' and 'Last' buttons, plus page numbers

Sorry for may being dump, this is my first PR. But we could start a discussion about the table layout.

* But first let me check this changes by myself.

### CODE REVIEW

**Comment by realizelol** [comment]
The tests myself are successful. So waiting for review.. (best by hiding whitespace and using split view)

Quarantine
-----------
Bildschirmfoto 2023-01-21 um 19 40 40
Bildschirmfoto 2023-01-21 um 19 41 01

Protocols
----------
Bildschirmfoto 2023-01-21 um 19 42 06
Bildschirmfoto 2023-01-21 um 19 42 23


PS:
quarantine filled by:
```bash
for i in {1..512}; do
  RND="$(( RANDOM<<15 | RANDOM ))"
  QID="${RND: -6}"
  SCORE="${RND: -3}"
  docker compose exec mysql-mailcow mysql -u"${DBUSER}" -p"${DBPASS}" "${DBNAME}" -e "\
INSERT INTO quarantine (qid, subject, score, sender, rcpt, symbols, user, ip, msg, action) VALUES ('${QID}', 'Test Subject ${i}', '${SCORE}', 'testuser${i}@example.tld', 'receiver@realizelol-mailcow.mc.vbox', '{\"name\": \"FROM_NEQ_ENVFROM\", \"group\": \"headers\", \"score\": ${SCORE}, \"groups\": [\"headers\"], \"options\": [\"info@versailors.gb.net.ch\", \"ayagar@akdeniz.edu.tr\"]}', 'receiver', '123.123.123.123', 'DUMPTEXT', 'rejected');"
done
```

**Review by vermium — APPROVED** [review]
Testing perms (Requested by @DerLinkman)

**Review by vermium — APPROVED** [review]
test

**Comment by FreddleSpl0it** [comment]
looks good but i think we don't need `Allow possible vertical-x-scrolling in quarantine.` as the tables should be responsive

Edit:
found some issues regarding page length.
Databales stateSave for page length doesn't work when using: `.page.len(pagination_size);`
instead use it like this:
```
    var table = $('#mailbox_table').DataTable({
      responsive: true,
      processing: true,
      serverSide: false,
      stateSave: true,
      pageLength: pagination_size,
```

**Comment by realizelol** [comment]
Okay, let me recheck that, as I mentioned that `pageLength: pagination_size,` wasn't working for me. Maybe I should also test some different browsers.

**Comment by realizelol** [comment]
Okay, seems like pagination_size is a "dirty number" for e.g. sth. like 025 so I used `Math.trunc()` to bring it into correct number format so that `pageLength` is working now as intended.

Also `scrollX`has been removed.

**Comment by realizelol** [comment]
Sorry, I respected the newest changes as there was a conflict with queue.js.
Maybe a bit complicated.

**Review by FreddleSpl0it — APPROVED** [review]

**Pull request merged**
