### PR TITLE
Normalize line-endings

### PR DESCRIPTION
**Pull request by mirorauhala**
This PR fixes issue #3129 

It introduces a new file `.gitattributes` that enforces proper LF line-ending. This change also fixes an issue with the nginx container being in a "restarting" state due to CRLF line-endings. I came across this when installing mailcow under Windows 10 with Docker.

Also this PR touches every file to update the line-endings.

### CODE REVIEW

**Comment by MAGICCC** [comment]
Derp I totally forgot about this issue which was mentioned once in our telegram group :/

**Comment by mirorauhala** [comment]
No worries! I had to fix this as I couldn't get mailcow to run under Windows 10. My mac instance worked just fine.

**Comment by mirorauhala** [comment]
Also maybe touching every file was a bit unnecessary as they would have updated later. Come to think of this, me touching every file will most likely trigger a merge-conflict.

**Comment by andryyy** [comment]
I don't think we should merge this for various reasons...

**Comment by mkuron** [comment]
This is going to cause lots of merge conflicts. Is that really worth it?

Does Mailcow even work correctly on Windows 10? The networking is completely different, so you might be losing source IPs, fail2ban and IPv6 support.

**Comment by MAGICCC** [comment]
Hm shouldnt the attribute file avoid merge conflicts due to line endings anyway?

**Comment by mirorauhala** [comment]
Yeah in hindsight it was bad idea to touch every file. I will revert the file update so this PR will only add the `.gitattributes` file.

**Comment by mirorauhala** [comment]
> Does Mailcow even work correctly on Windows 10? The networking is completely different, so you might be losing source IPs, fail2ban and IPv6 support.

Well I'm running it under Docker so everything built under the docker-compose should work just fine. At least that's the idea of Docker. Anyway this is my development machine right now and CRLF line-endings were the culprit as bash scripts should have LF.

**Comment by mirorauhala** [comment]
Any update on this?

**Pull request closed without merging**
