### PR TITLE
[WIP] Allow setting sender name for notification mails

### PR DESCRIPTION
**Pull request by heavygale**
In the past it was possible to specify values like '"sender name" <sender-address@example.com>' as sender for the notification emails, but newly added checks currently prevent this. This PR adds a new field to specify the sender name to restore this functionality.

### CODE REVIEW

**Comment by andryyy** [comment]
Can you please add a placeholder for the name?

Please also test with each variable empty, both empty, both set and with special chars like é for both. Could you do that please and post the results?

**Comment by heavygale** [comment]
### Testresults: quarantine

|quarantine sender address  | quarantine sender name | resulting from header |
|------------- | ------------- | ------------- |
|custom-quarantine-sender@example.com | custom quarantine sender name | From: "custom quarantine sender name" <custom-quarantine-sender@example.com> |
|custom-quarantine-sender@example.com | _empty_ | From: custom-quarantine-sender@example.com |
|_empty_ | custom quarantine sender name | From: "custom quarantine sender name" <quarantine@localhost> |
|_empty_ |_empty_ | From: quarantine@localhost |
|andré@example.com<br><br>not accepted by FILTER_VALIDATE_EMAIL, value gets cleared:<br><br>_empty_| andré with fancy chars: 🤓<"*#'@%$<br><br>automatically shortened when saved:<br><br>andr with fancy chars: <*#'@%$ |	From: "andr with fancy chars: <*#'@%$" <quarantine@localhost>

### Testresults: quota

|quota sender address  | quota sender name | resulting from header |
|------------- | ------------- | ------------- |
|custom-quota-sender@example.com | custom quota sender name | "custom quota sender name" <custom-quota-sender@example.com> |
|custom-quota-sender@example.com | _empty_ | From: custom-quota-sender@example.com |
|_empty_ | custom quota sender name | From: "custom quota sender name" <quota-warning@localhost> |
|_empty_ |_empty_ | From: quota-warning@localhost |
|andré@example.com<br><br>not accepted by FILTER_VALIDATE_EMAIL, value gets cleared:<br><br>_empty_ | andré with fancy chars: 🤓<"*#'@%$<br><br>automatically shortened when saved:<br><br>andr with fancy chars: <*#'@%$ | From: "andr with fancy chars: <*#'@%$" <quota-warning@localhost> |

**Comment by heavygale** [comment]
The sender for sending Quoata mails to BCC recipients [gets replaced by the name of the respective mailbox](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dovecot/quota_notify.py#L68). Was this added to allow sending with the default address "quota-warning@localhost" to external addresses? Should we replace the sender only as fallback if no custom sender address is set?

I didn't add a placeholder for the name, as there is no default value. If no sender name is specified, only the sender address is used. What should we set as a placeholder value?

**Comment by heavygale** [comment]
Should we use $UI_TEXTS['title_name'] as a placeholder for the sender name? Maybe in square brackets, since it is an optional value and only the sender address is used by default?

**Comment by andryyy** [comment]
I do actually not know if this is tested at all. :/ Some things were pushed before I asked you to test it, your question was "how?". I don't want to experiment too much anymore. This applies to me, too, of course.

**Comment by heavygale** [comment]
I'm sorry that I lost your trust due to problems with previous PRs. I recognize that it was wrong not to test changes that seem insignificant to me and I will try to improve the quality of my contributions. However, I did not claim to have tested the PRs you were referring to. Also, I was surprised that it is even possible to contribute syntax errors in json files without being complained about by github.

To create the above table, I manually made the suggested changes on my mailcow, changed the quarantine sender address and quarantine sender name fields as specified using the GUI and then triggered an email by manually running each of the scripts from within the dovecot container. The information in the "resulting from header" column is taken from the email header of the actually sent email.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
