### PR TITLE
Make the default admin password random

### PR DESCRIPTION
**Pull request by Linus9000**
This aims to solve #1245 by implementing a random admin password. Also, the helper script for resetting the admin will now generate a random password.

If there's potential for optimization, please let me know.

### CODE REVIEW

**Comment by andryyy** [comment]
The variable shouldn’t exist in mailcow.conf when it is never reset to this value again. It just confuses users.

**Comment by herbetom** [comment]
I think it is okay that it stands in `mailcow.conf` (at the moment moohoo is also a coment within that), and also it useful for an automated installation where mailcow is only a component of many and the password to login should be printed to the console after other things happenend. 

But I would change it so that in `mailcow-reset-admin.sh` the password is read from `mailcow.conf` and reset to the value in that file. This way the password is generated once per installation and the user is always able to run the script and use the default password again if he messed up. That sounds to me logically and like quite a good solution.

**Comment by andryyy** [comment]
It is not a variable right now.

**Comment by herbetom** [comment]
yes, but the variable is called DEFAULTPASS so it should be clear that it is not the current password. But i would change the Comment to look like this: 
```
# ------------------------------
# mailcow web ui configuration
# ------------------------------
# example.org is _not_ a valid hostname, use a fqdn here.
# Default admin user is "admin"
# Default password is the value of DEFAULTPASS. 
# INFO: You can set it back to "admin" and the value of DEFAULTPASS 
#       by running ./helper-scripts/mailcow-reset-admin.sh
MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
DEFAULTPASS=moohoo
```

Of course how it is implemented by @Linus9000 probably wouldn't work because when updating from an older version it would come to an conflict because the mailcow.conf isn't updated by git (doesn't exist on GitHub so is their can't be easily done changes while updating). This has to be handeld. But that would be possible.

**Comment by nupplaphil** [comment]
Hm.. I think it would be better to have an alert that you have to change the password rather than to use a variable with a random password in the mailcow.conf

And to you could add a "Please change the default admin password after you successfully logged in the first time" in https://mailcow.github.io/mailcow-dockerized-docs/install/

**Comment by MAGICCC** [comment]
@nupplaphil Well the problem with that is still the same imho. Some random user detects a fresh mailcow installation and login with the current default password and changes it after seeing the popup.

To be honest. I wouldn't change anything. When an user can't wait some minutes until everything is started, then he may not use his own mailserver (regarding no time to check its status and update and such)
Don't get me wrong about password security and it's 'bad' to use everywhere the same password

**Comment by Linus9000** [comment]
This PR aims specifically to prevent the scenario outlined in the second paragraph of the original issue #1245, which could not be mitigated by an alert of some sort. 

To be honest, on my first installation of mailcow after logging in I thought the password change is mandatory (I mean, it's red and shows right after login). Also I hope everyone using software like this on a public server knows to change default passwords.

The problem which lead me to writing the password into mailcow.conf is that I wanted to output it to the user, while making it available to the PHP scripts with only small changes. 
As the generate_config.sh is the only place where a user gets an output in the installing phase it made sense for me to generate it there. The logical consequence was then to write it into mailcow.conf, because all the logic to get values from there into the containers is already present.

Of course this approach may have undesirable consequences, confusing users is certainly one of them. I could change the mailcow-reset-admin.sh to use this password, thereby eliminating the confusion (if I understood your comment correctly).

**Comment by andryyy** [comment]
Hm, we would need to update the docs, too.

**Comment by Linus9000** [comment]
Just noticed I put the DEFAULTPASS-block just in between database config and database password, whoops..

**Comment by Knight1** [comment]
Is there any intention to merge this?

**Pull request closed without merging**
