### PR TITLE
[GitHub Templates] Added funding template

### PR DESCRIPTION
**Pull request by ntimo**
Added funding configuration for the new GitHub Support button.

### CODE REVIEW

**Comment by patcon** [comment]
Sorry, may I ask why this was removed @andryyy? :)

I am reflecting on an initiative/tool to help people know funding options for opensource/free business tools that they use, ideally working only from source code to check, and I was just coming to Mailcow to add (at the very least) these two:
https://www.servercow.de/mailcow#support
https://www.servercow.de/mailcow#sal

But I see that funding.yml was removed for some reason. Would love to know why, as it's the closest thing we have to a standard <3

**Comment by andryyy** [comment]
The tax office. :(

They hunt you down and take your firstborn. It is easier for me this (=SAL) way. :)

**Comment by patcon** [comment]
OK, totally! Def don't want you to be troubled :)

Would we be able to bring it back and only link to the SAL/support tiers, or is just the using of the FUNDING.yml file what makes you nervous?

**Comment by andryyy** [comment]
The links you posted are totally fine. :)

**Comment by andryyy** [comment]
It is not that taxes were not paid, but it is hard to actually tax them, as I needed to see them as a kind of service I provided and create invoices etc. ... it is much easier the way it is now.

**Comment by patcon** [comment]
ok! will submit a PR to bring it back with those safe ones :) (correct me if i'm wrong)

**Pull request merged**
