### PR TITLE
Replace jqPlot with Google Charts

### PR DESCRIPTION
**Pull request by PhoenixPeca**
### Case:
Google Charts is lightweight, has better documentation, mobile ready and more pretty.
__________________________________

Normal view:
image

On-hover Tooltip:
image

### CODE REVIEW

**Comment by andryyy** [comment]
Nice. You tested if reloading etc. still works?

**Comment by PhoenixPeca** [comment]
Yes I did.. I just followed what you did in jqPlot, apparently both plugins works (more or less) the same way, just different designs.

**Comment by andryyy** [comment]
Ok. I trust you with this. But don’t push something like this to master without at least discussing it.

**Comment by ntimo** [comment]
Hey,
I actually think the flat chart from before looked better :(

**Comment by EnriqCG** [comment]
It is obviously a matter of opinions, but as @PhoenixPeca mentioned, Google Charts is a more modern and more responsive library. 

This design fits better into the panel theme imo.

**Pull request merged**
