### PR TITLE
Dynamically choose the Docker network subnet

### LINKED ISSUE #4878: Dynamic Docker network IP range
### Summary

The default ipv4 subnet  (`172.22.1.0/24`) may already be used with other Docker networks.
It'll be more convenient to find an available address to prevent the following error.
`ERROR: Pool overlaps with other one on this address space`

### Motivation

This will eliminate `Pool overlaps` error on `docker compose up`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Abbas-b-b**
Resolves #4878

### CODE REVIEW

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by Abbas-b-b** [comment]
Do I need to do anything about it?

**Comment by DerLinkman** [comment]
Hi there,

nope. No need for you by now.

A test is needed which i'll do today i think.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by cl445** [comment]
The current script attempts to generate a new Docker network subnet by incrementing the highest octet found in existing subnets. However, if the highest octet is 255, the script produces an invalid subnet, 172.256.*.*, which falls outside the valid IP range.

**Comment by cl445** [comment]
This PR addresses bug #4878 only partially! The script potentially generates a valid Docker network only once during the installation of Mailcow. However, if Docker is restarted (e.g., after an update), conflicts may arise again because Docker dynamically creates a network that conflicts with the one created by generate_config.sh .

**Pull request closed without merging**
