### PR TITLE
Python27 eol issue2291

### PR DESCRIPTION
**Pull request by famx-droid**
Update dovecot Python 2 scripts to be compatible with Python 3:
- quota_notify.py
- quarantine_notify.py
- Dockerfile

### CODE REVIEW

**Comment by patschi** [comment]
Related to #2291

**Comment by andryyy** [comment]
And really, really nice! Thank you! Let me test it. :)

**Comment by andryyy** [comment]
Sorry, will test asap.

**Comment by andryyy** [comment]
Please do not create PRs, when you think will they work, but you didn't actually test them at all. :(

I don't have time to fix this. If you want to (or any other), go ahead. :) 

```
root@mx:/# quarantine_notify.py
Traceback (most recent call last):
  File "/usr/local/bin/quarantine_notify.py", line 97, in <module>
    records = query_mysql('SELECT IFNULL(user_acl.quarantine, 0) AS quarantine_acl, count(id) AS counter, rcpt FROM quarantine LEFT OUTER JOIN user_acl ON user_acl.username = rcpt WHERE notified = 0 AND rcpt in (SELECT username FROM mailbox) GROUP BY rcpt')
  File "/usr/local/bin/quarantine_notify.py", line 43, in query_mysql
    columns = tuple( [d[0].decode('utf8') for d in cur.description] )
  File "/usr/local/bin/quarantine_notify.py", line 43, in <listcomp>
    columns = tuple( [d[0].decode('utf8') for d in cur.description] )
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by MaxXor** [comment]
@FaMux This should work -> `columns = tuple( [str(d[0]) for d in cur.description] )`

**Comment by famx-droid** [comment]
> Please do not create PRs, when you think will they work, but you didn't actually test them at all. :(
> 
> I don't have time to fix this. If you want to (or any other), go ahead. :)
> 
> ```
> root@mx:/# quarantine_notify.py
> Traceback (most recent call last):
>   File "/usr/local/bin/quarantine_notify.py", line 97, in <module>
>     records = query_mysql('SELECT IFNULL(user_acl.quarantine, 0) AS quarantine_acl, count(id) AS counter, rcpt FROM quarantine LEFT OUTER JOIN user_acl ON user_acl.username = rcpt WHERE notified = 0 AND rcpt in (SELECT username FROM mailbox) GROUP BY rcpt')
>   File "/usr/local/bin/quarantine_notify.py", line 43, in query_mysql
>     columns = tuple( [d[0].decode('utf8') for d in cur.description] )
>   File "/usr/local/bin/quarantine_notify.py", line 43, in <listcomp>
>     columns = tuple( [d[0].decode('utf8') for d in cur.description] )
> AttributeError: 'str' object has no attribute 'decode'
> ```
@andryyy 
Sorry, I will solve the problem and test it extensively this time. That was not my intention to steal your time unnecessarily. My first GitHub Merge Request, but that's no excuse.


> @FaMux This should work -> `columns = tuple( [str(d[0]) for d in cur.description] )`

@MaxXor  Thank you for that!

**Comment by famx-droid** [comment]
> @FaMux This should work -> `columns = tuple( [str(d[0]) for d in cur.description] )`

@MaxXor Tested on my own mailcow, that seems to work properly - thanks! I need some more time to test all possible cases in quarantine_notify.py.

Found also an issue with Python3 in quota_notify.py. The `p.communicate(input=msg.as_string())` needs a byte-like object, i solved that with `p.communicate(input=msg.as_bytes())`. Testing quota_notify.py like described in #2289. I will do a new merge request soon.

**Pull request merged**
