### PR TITLE
fix: changed "Twitter" to "𝕏 (Twitter)" in README.md in Cowmunity Section

### PR DESCRIPTION
**Pull request by BandhiyaHardik**
changed the name of Twitter to 𝕏.

Badge is already Updated:
image

Current Behaviour:  
image

Expected Behaviour: 
image

This fixes https://github.com/mailcow/mailcow-dockerized/issues/5506

### CODE REVIEW

**Comment by DerLinkman** [comment]
Merci 🙏

**Comment by aveao** [comment]
The correct spelling is X, not 𝕏.

**Comment by BandhiyaHardik** [comment]
> The correct spelling is X, not 𝕏.

I added 𝕏 so it looks just like the new logo of 𝕏(Twitter)

**Comment by aveao** [comment]
> > The correct spelling is X, not 𝕏.
> 
> I added 𝕏 so it looks just like the new logo of 𝕏(Twitter)

The name of the site is X tho. [Brand guidelines](https://about.twitter.com/en/who-we-are/brand-toolkit) call it X while showing the new logo as just that, a logo.

ps. 𝕏 will be read by screen readers as "Mathematical Double-Struck Capital X".

**Pull request merged**
