### PR TITLE
update postscreen whitelist by using postwhite

### PR DESCRIPTION
**Pull request by friedPotat0**
Updated postscreen whitelist by using the latest postwhite version (v3.4 from master@https://github.com/stevejenkins/postwhite) and latest SPF-Tools (from master@https://github.com/spf-tools/spf-tools). The default postwhite.conf with no additional custom hosts was used to generate the list.

#2948

### CODE REVIEW

**Comment by mkuron** [comment]
Could you please check whether there are any other big email providers that should be added to this list? T-Online from #2948 is certainly a candidate, but there certainly are more. Also, can you please add a script to Mailcow that can be run manually to update the list?

**Comment by friedPotat0** [comment]
I wrote a short shell script to update the postscreen whitelist manually. More custom hosts that need to be whitelisted can be added to the `COSTOM_HOSTS` variable (I've already added the big providers). I've also included the t-online subnet as a static host that is additionally appended to the whitelist after running postwhite.

Should I also add the command for reloading postfix to the end of the update script?

**Comment by mkuron** [comment]
No need to reload Postfix. I didn't intend this script to be used by the average user, just to make it easier for us to update the postwhite list.

**Comment by andryyy** [comment]
Yes, should not be run by the user but us to update the list. :)

**Comment by andryyy** [comment]
Thank you!

**Pull request merged**
