### PR TITLE
[ACME] Hotfix acme openssl

### PR DESCRIPTION
**Pull request by dragoangel**

### CODE REVIEW

**Comment by ghost** [comment]
Breaking change introduced by Alpine v3.15??

**Comment by dragoangel** [comment]
Nope, actually clean builded image has correct file location, I dropped this PR due this. @andryyy looks like image that you build just have issues.

**Comment by MAGICCC** [comment]
I repushed the image, looks fine now

**Comment by andryyy** [comment]
Thank you

**Pull request closed without merging**
