### PR TITLE
[Feature] Added Policyd

### PR DESCRIPTION
**Pull request by zkryakgul**
[What is policyd?](https://wiki.policyd.org/)

### CODE REVIEW

**Comment by andryyy** [comment]
Thanks, that’s very nice, but why? We have Rspamd which does not only cover everything Policyd does but is even much more flexible.

**Comment by zkryakgul** [comment]
Can we do spesific user based limitaions on rspamd? For example; block some users mail to gmail or allow some users only send mail on local domains.

**Comment by andryyy** [comment]
Yes. There are multiple ways, I think. There already is a map containing mailcow domains you could use to identify local mail. Specific policies could be forced with a settings map containing references to that map. Like “if it’s coming from this and going there, reject”.

**Comment by extremeshok** [comment]
policyd has been superseded by rspamd. Please do NOT add this.

Rather customize rspamd to add the missing features or develop a custom module for it https://rspamd.com/doc/modules/

**Comment by zkryakgul** [comment]
Im little confused because im pretty new on rspamd; for example: how can i do like this;
```
from: testuser@mailcow.email
to: *@gmail.com
verdict: reject
```

or 

```
from: testuser@mailcow.email
to: !not_local_domain_group
verdict: reject
```

**Comment by andryyy** [comment]
grafik

```
authenticated = yes;
priority = 10;
rcpt = "/.*@gmail\.com/";
apply "default" {
  GMAIL_OUTGOING_BL = 9999.0;
}
symbols [
  "GMAIL_OUTGOING_BL"
]
```

**Pull request closed without merging**
