### PR TITLE
chore: :truck: rename fail2ban to netfilter

### PR DESCRIPTION
**Pull request by vermium**
Netfilter is a lot more correct than fail2ban since the implementation does not use fail2ban

**This release needs to be reviewed and I need help on how to migrate previous data from fail2ban tables to Netfilter tables**

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by vermium** [comment]
> Thanks for contributing!
> 
> I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`. See the attached picture on how to change the base branch to `staging`:
> 
> 

Fixed

**Comment by vermium** [comment]
What do you think @DerLinkman?

**Comment by vermium** [comment]
This is missing migration schemes. Is this something anyone that has worked in this project for a longer time, fix?

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
