### PR TITLE
hardening http headers

### PR DESCRIPTION
**Pull request by apoc4lyps**
add X-Frame-Options and Referrer-Policy to nginx config

### CODE REVIEW

**Comment by mritzmann** [comment]
I like the idea of improving the security headers.

Regarding `Referrer-Policy`:

In my opinion, there is no reason why the referer should be sent to external websites at all. Doesn't it make sense to put it directly on `same-origin`?

**Comment by Knight1** [comment]
Indeed. If the SOGo Domain does not match the Mail domain it is hidden with same-origin. I personally would use strict-origin to prevent downgrade attacks.

**Comment by mritzmann** [comment]
> I personally would use strict-origin to prevent downgrade attacks.

`strict-origin` also sends the reffer to external sites.

table

(Screenshot from [scotthelme.co.uk](https://scotthelme.co.uk/a-new-security-header-referrer-policy/))

----

Maybe `no-referrer` makes sense? Is the reffer being used for something useful?

**Comment by Knight1** [comment]
Any intention to merge this?

**Pull request merged**
