### PR TITLE
JanMooary (January) 2022 Update (Merge staging to master)

### LINKED ISSUE #4392: Possible regression in acme-mailcow 1.80
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Just testing with the newest mailcow-dockerized version from the repo. After `docker-compose up -d` the containers running, but `acme-mailcow` has an error obtaining the certificates:

```
cat: can’t open ‘/etc/ssl/openssl.cnf’: No such file or directory
acme-mailcow_1 | unable to find ‘distinguished_name’ in config
acme-mailcow_1 | problems making Certificate Request
...
```

If I change the `acme-mailcow` version in the `docker-compose.yml` to **1.79** the error is gone and the certificates are obtained.

## Logs
```
Attaching to piratemail_acme-mailcow_1
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Waiting for Docker API...
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Docker API OK
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Waiting for Postfix...
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Postfix OK
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Waiting for Dovecot...
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Dovecot OK
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Waiting for database...
acme-mailcow_1       | Sat Dec 18 15:56:32 CET 2021 - Database OK
acme-mailcow_1       | Sat Dec 18 15:56:32 CET 2021 - Waiting for Nginx...
acme-mailcow_1       | Sat Dec 18 15:56:40 CET 2021 - Nginx OK
acme-mailcow_1       | Sat Dec 18 15:56:40 CET 2021 - Waiting for resolver...
acme-mailcow_1       | Sat Dec 18 15:56:40 CET 2021 - Resolver OK
acme-mailcow_1       | Sat Dec 18 15:56:40 CET 2021 - Waiting for domain table...
acme-mailcow_1       | OK
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - Initializing, please wait...
acme-mailcow_1       | unable to load certificate
acme-mailcow_1       | 139686046726984:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
acme-mailcow_1       | unable to load certificate
acme-mailcow_1       | 139752372075336:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - Using existing domain rsa key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - Detecting IP addresses...
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - OK: 1.2.3.4, dead::beef
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Found AAAA record for my.domain.de: dead::beef - skipping A record check
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Confirmed AAAA record with IP dead:beef
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Certificate /var/lib/acme/my.domainde/cert.pem missing or changed domains 'my.domain.de' - start obtaining
acme-mailcow_1       | cat: can't open '/etc/ssl/openssl.cnf': No such file or directory
acme-mailcow_1       | unable to find 'distinguished_name' in config
acme-mailcow_1       | problems making Certificate Request
acme-mailcow_1       | 140678094932808:error:0E06D06C:configuration file routines:NCONF_get_string:no value:crypto/conf/conf_lib.c:273:group=req name=distinguished_name
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Checking resolver...
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Resolver OK
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Using command acme-tiny   --account-key /var/lib/acme/acme/account.pem --disable-check --csr /var/lib/acme/my.domain.de/acme.csr --acme-dir /var/www/acme/
acme-mailcow_1       | Parsing account key...
acme-mailcow_1       | Parsing CSR...
acme-mailcow_1       | Traceback (most recent call last):
acme-mailcow_1       |   File "/usr/bin/acme-tiny", line 8, in <module>
acme-mailcow_1       |     sys.exit(main())
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 195, in main
acme-mailcow_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 90, in get_crt
acme-mailcow_1       |     out = _cmd(["openssl", "req", "-in", csr, "-noout", "-text"], err_msg="Error loading {0}".format(csr))
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 28, in _cmd
acme-mailcow_1       |     raise IOError("{0}\n{1}".format(err_msg, err))
acme-mailcow_1       | OSError: Error loading /var/lib/acme/my.domain.de/acme.csr
acme-mailcow_1       | b'unable to load X509 request\n140383324310344:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE REQUEST\n'
acme-mailcow_1       | Sat Dec 18 15:56:44 CET 2021 - Failed to obtain certificate /var/lib/acme/my.domain.de/cert.pem for domains 'my.domain.de'
acme-mailcow_1       | OK
acme-mailcow_1       | Sat Dec 18 15:56:44 CET 2021 - Some errors occurred, retrying in 30 minutes...
acme-mailcow_1       | OK
```

## Reproduction
Just do `docker-compose up -d` and the error persists.

If I change the `acme-mailcow` version in the `docker-compose.yml` to **1.79** the error is gone.

## System information
| Question | Answer |
| --- | --- |
| My operating system | Debian Buster |
| Is Apparmor, SELinux or similar active? | No. |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | 2GB + 6G Swap, 1 CPU (local staging environement) |
| Docker Version (`docker version`) | 20.10.12 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | No |

### LINKED ISSUE #4401: Olefy 1.8 broken
## Sumarry
Hi, since the olefy update to image 1.8, olefy don't start anymore with the error below.
After a downgrade to 1.7 image this is OK.

It's maybe related to this ? https://github.com/HeinleinSupport/olefy/commit/fee073b1ee44f014ace848ed3d31a972a7c61baf
https://github.com/HeinleinSupport/olefy/pull/14
## Logs

```
olefy-mailcow_1      | olefy ERROR default_exception_handler Fatal error: protocol.eof_received() call failed.
olefy-mailcow_1      | protocol: <__main__.AIO object at 0x7f2295529910>
olefy-mailcow_1      | transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
olefy-mailcow_1      | Traceback (most recent call last):
olefy-mailcow_1      |   File "/usr/lib/python3.9/asyncio/selector_events.py", line 882, in _read_ready__on_eof
olefy-mailcow_1      |     keep_open = self._protocol.eof_received()
olefy-mailcow_1      |   File "/app/olefy.py", line 171, in eof_received
olefy-mailcow_1      |     rspamd_id = olefy_headers['Rspamd-ID'][:6] or ''
olefy-mailcow_1      | KeyError: 'Rspamd-ID'
```

### PR DESCRIPTION
**Pull request by DerLinkman**
**Images which get a new tag (on docker hub):**
- unbound-mailcow (Tag 1.15)
- acme-mailcow (Tag 1.81)
- dockerapi-mailcow (Tag 1.41)
- netfilter-mailcow (Tag 1.46)
- watchdog-mailcow (Tag 1.96)
> These docker tag changes include the Alpine Update to 3.15
- clamd-mailcow (Tag 1.43)
- sogo-mailcow (Tag 1.106)
- olefy-mailcow (Tag 1.8.1)
- dovecot-mailcow (Tag  1.159)
- solr-mailcow (Tag 1.8.1)

Very important changes:
- U2F API Removal --> Replaced with WebAuthn API (TFA) [[More Details here](https://mailcow.github.io/mailcow-dockerized-docs/u_e-mailcow_ui-tfa/)] (Thanks to @FreddleSpl0it)

Important changes:
- Dovecot Update to 2.3.17.1
- SOGO Update to 5.5.0
- ClamAV Update to 0.103.5 (DDOS Fix)
- Solr Security Fix Fix (Removed breached log4j Class)
- Alpine Linux Update to 3.15
- Better Acme SSL Path recognition for Alpine Versions after 3.15 (Thanks to @mkuron) --> Fixing issue: https://github.com/mailcow/mailcow-dockerized/issues/4392
- Olefy Ping Fix (Will fix: https://github.com/mailcow/mailcow-dockerized/issues/4401) (Thanks to @a16bitsysop for the Fix!)
- Netfilter GeoIP Fix (Thanks to @marcvorwerk) --> Fixing issue: https://github.com/mailcow/mailcow-dockerized/issues/2668

### CODE REVIEW

**Comment by MAGICCC** [comment]
Hm seems I know where this issue comes from: https://github.com/mailcow/mailcow-dockerized/issues/4392
Somehow they changed the folder from /etc/ssl to /etc/ssl1.1 in Alpine 3.15.

**Comment by DerLinkman** [comment]
Is it fixable? With a folder remapping?

**Comment by andryyy** [comment]
I think @mkuron already looked into it and described it pretty good.

**Comment by DerLinkman** [comment]
Is there something missing or wrong besides that (if there is a problem, i didn´t got it to be honest)?

**Comment by DerLinkman** [comment]
https://github.com/mailcow/mailcow-dockerized/pull/4397 is fixing the greyed out save button, it has been testet a few times with customer mailcows. (That wasn´t sure before)

I´ll test the Alpine build images today and give feedback here.

**Comment by BonGoo** [comment]
Hi i think that if the tests are open, we should add to update clamav there is 103.5 lts version

**Comment by DerLinkman** [comment]
Good call. I'll add this new clamav version to my test system and include the pull request into this one after it is successfully tested.

**Comment by DerLinkman** [comment]
https://github.com/mailcow/mailcow-dockerized/pull/4422 will include the clamd Update. I would say after that we can merge this pull request into master (after the final tests). What do you think @andryyy ?

**Comment by DerLinkman** [comment]
I would like to wait for https://github.com/mailcow/mailcow-dockerized/issues/4421 until we merge that.

**Pull request merged**
