### PR TITLE
Add support for pre hashed passwords via API

### PR DESCRIPTION
**Pull request by cybersholt**
@mkuron this is the patch for #3282 I think my editor ( PhpStorm ) had a field day with the line endings and line spacing, if this is an issue let me know.

### CODE REVIEW

**Comment by mkuron** [comment]
Please undo the whitespace changes so we get a clean diff.

**Comment by Programmierus** [comment]
Why was it closed and not merged?

**Comment by andryyy** [comment]
It contained a bunch of whitespace changes in multiple files. It will be merged, when it is fixed.

**Comment by Programmierus** [comment]
Is it OK if I'll create a new pull request with proper formatting?

**Comment by andryyy** [comment]
Yes :) Sure.

**Pull request closed without merging**
