### PR TITLE
JSON API Consume json in request body.

### PR DESCRIPTION
**Pull request by feldsam**
There are small changes to have ability to do json api requests with json in request body - more standard way in world of rest apis.

Draft docs https://feldhostmailhosting.docs.apiary.io

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by ntimo** [comment]
@andryyy what do you think? I think being able to send json to the API would defiantly be nice.

**Comment by feldsam** [comment]
Hi @ntimo, api already consume json, but not in standard way - request body. It must be in post param `attr` and/or `items` .


I am also open to rename our project on Apiary to MailCow Api Docs and share write access with other people, who want contribute to docs.

**Comment by ntimo** [comment]
@andryyy What do you think about this? 
Having some documentation for the API like the one you created would defiantly be nice.

**Comment by andryyy** [comment]
@feldsam 

    I am also open to rename our project on Apiary to MailCow Api Docs and share write access with other people, who want contribute to docs.

That would be nice. You want to do that?

**Comment by feldsam** [comment]
Thanks, @andryyy for merging this PR. I can share write access with you or better you can create a new project, share write access with me and I add docs what I have done because we have forked version with some new attributes on the domain, which are not in upstream.

**Comment by andryyy** [comment]
I can add you with read/write access, just need your mail.

**Comment by andryyy** [comment]
Can you send to info@servercow.de?

**Comment by feldsam** [comment]
feldsam@gmail.com

**Comment by andryyy** [comment]
Sent you a mail.

Cannot find your forked project, btw. Where is it?

**Comment by andryyy** [comment]
The listed fork in your profile is not what you actually modified. Please at least share your changes, if you decide to name mailcow "FeldMail" and sell it...

And please don't use the issue tracker for support requests anymore.

**Comment by feldsam** [comment]
Hi, FeldMail is newsletter service based on https://mailtrain.org. We use mailcow for shared mailhosting. I contribute back to this project things, which I think will be accepted and usefull for comunity. For ex. there are bcc on in/outbound for each mailbox, but in meantime you create bcc maps sections, so we use both, but feels, that it is not usefull for community, when there are bcc maps....

Only one thing, is "default" quota on domain and used when user creat emailboxes...I can make PR.

I also make decision to give back this json PR and share docs what I write.... so when I have problem with mailcow on our shared mailhosting, I like to open issue here and get help...

**Comment by feldsam** [comment]
I added docs to mailcow apiary https://mailcow.docs.apiary.io

**Comment by akaillidan** [comment]
> I added docs to mailcow apiary https://mailcow.docs.apiary.io

Hi, we found a discrepancy in the documents for API for PHP. In the code, an array is expected to be sent (as form data), and the documentation indicates that it is expected to send a json string with account parameters.

https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/json_api.php#L121-L124

**Comment by feldsam** [comment]
Hi, look on code above, starting on L66, which this PR was about that code block.

**Pull request merged**
