### PR TITLE
Quarantine notifications - exclude blacklisted sender

### PR DESCRIPTION
**Pull request by feldsam**
The final version, fixed syntax. I see my prev PR was reverted and I also hit the error with syntax problem. In this version, the syntax is fixed and it is working.

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by andryyy** [comment]
Thanks. :) Query works fine, but did you test some cases? :)

**Comment by feldsam** [comment]
Hi, currently in production on two servers. This feature was requested by my client. I tested cases you wrote me in prev PR. We can wait a bit to see if client reports some issues or no.

**Comment by andryyy** [comment]
Okay, sounds cool. Perhaps in 2-3 days? :)

**Comment by vain90** [comment]
It would be gorgeous if a mail from a blacklisted sender would never go to the quarantaine. =)

**Comment by feldsam** [comment]
@andryyy, no issues reported from customers, so I think you can merge this.

**Pull request merged**
