### PR TITLE
Adds 'do nothing' as default for sub-addressing

### PR DESCRIPTION
**Pull request by TiiFuchs**
You can still change your sub-addressing configuration on the user.php in the mailcow backend.
There are three options now: subject, subfolder and none.

Subject adds the tag in [] to the subject, as before.
Subfolder moves the mail in a Subfolder with the Tag as name, as before.
None does nothing of the above and just puts that mail in your inbox. You can see the tag in the To field of the mail.

### CODE REVIEW

**Comment by TiiFuchs** [comment]
As discussed in #748

**Comment by andryyy** [comment]
That's very cool! Have you checked all functions?

**Comment by TiiFuchs** [comment]
Jap, all three functions work fine and as expected. :)

**Comment by andryyy** [comment]
Upgrading mailcows will all be reset to "do nothing", that's something we should have seen coming. :-(

**Comment by TiiFuchs** [comment]
Ooh >.<

**Comment by TiiFuchs** [comment]
Any mechanism for an update script that checks the value for any user and updates it on update? (At least for the users that haven‘t updated until now)

I would rather not change the default back since I think „do nothing“ is a sane default here.

**Comment by andryyy** [comment]
Yes, I also think "do nothing" is the best default. 👍 We could add this to mailcow.email. 

I used to add the migration stuff to the docker entrypoints. Btw. .. need to clean that up.

Edit: Don't get me wrong, I really like your implementation! I just add this as a note for us to remember what happens with default values on updates. 😄

**Pull request merged**
