### PR TITLE
Discarded: Refactor: `update.sh` script with `--help` should exit with status code 0

### PR DESCRIPTION
**Pull request by h3ssan**
Hello all,

This PR re-opened in [`https://github.com/mailcow/mailcow-dockerized/pull/5991`](https://github.com/mailcow/mailcow-dockerized/pull/5991)

### CODE REVIEW

**Comment by h3ssan** [comment]
Hey all,

Sorry I've opened this pr based on my [last pr's branch](https://github.com/mailcow/mailcow-dockerized/pull/5987), but since it all based on the staging branch then I think it's OK.

**Comment by DerLinkman** [comment]
Please rebase your branch on the current staging branch as it includes content from PR https://github.com/mailcow/mailcow-dockerized/pull/5987

**Comment by h3ssan** [comment]
OK first I am sorry, don't know what happened with this PR! Will try to fix it

**Comment by h3ssan** [comment]
Hey @DerLinkman 

There's many conflicts happened, I clean it up. Please take action about my other PRs. Then, I'll re-open this PR.

**Comment by DerLinkman** [comment]
No problem! Done :)

**Pull request closed without merging**
