### PR TITLE
Update notify.xml

### PR DESCRIPTION
**Pull request by baimard**
#5246 correction for this bug report

### CODE REVIEW

**Comment by milkmaker** [comment]
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

**Comment by tomudding** [comment]
For the Mailcow maintainers; as I pointed out in GH-5246 I think that a better longterm solution would be the removal of the `notify` extension/module and replace it with `enotify` (the command will still be `notify`).

This not only ensures that you cannot use a heavily deprecated function, it also makes it easier for people who like to use the sieve as they do not have to scour the internet in search for an RFC _draft_ because the syntax they found in the Dovecot documentation does not match with the errors they receive from the sieve validation in Mailcow.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
